### ISSUE TITLE
Add colors to tailwind

### ISSUE THREAD

**Issue by yovanoc** [modulz/stitches#10]
Hello i've tried to add colors to the tailwind config but it seems it doesn't work.

I've tried to add it like that:

![image](https://user-images.githubusercontent.com/7302317/79869757-25e78980-83e2-11ea-9c0e-0586767c3925.png)

or 

![image](https://user-images.githubusercontent.com/7302317/79869839-4fa0b080-83e2-11ea-8730-4e8c36266fe9.png)

but it doesn't work here

![image](https://user-images.githubusercontent.com/7302317/79869940-74952380-83e2-11ea-8de2-43f7be95c4f7.png)

so how can we add colors?

**Comment by christianalfoni** [comment]
Oh, hi @yovanoc, the colors for text is under `textColor`. If you look at : https://github.com/christianalfoni/stitches/blob/master/packages/tailwind/src/theme.ts

I can list the theme properties in the documentation :)

**Comment by yovanoc** [comment]
I've no textColor

![image](https://user-images.githubusercontent.com/7302317/79999836-b2667a80-84bc-11ea-9417-19f5117ce250.png)


and even look for the `.bg` one

![image](https://user-images.githubusercontent.com/7302317/79999887-c27e5a00-84bc-11ea-972d-7e21cef3d497.png)

there are tailwind colors in there but not mines

**Comment by yovanoc** [comment]
Oh yeah textColor is in configuration, so can't add tokens for colors to be taken everywhere we have to repeat them all over each theme things? :(

**Comment by christianalfoni** [comment]
Ah, yes, I did a blunt implementation first where the config is just a plain object. Tailwind has a bit of logic which derives some theme values from others. It was just a lot of work getting it to this state so I had to down prioritize something or I would have gone crazy 😂 

But yeah, we can give theme values functions to derive from other values. 

Noted 😄

**Comment by yovanoc** [comment]
Ahah no worries you make a really good job here. I really love how this project has step up! Keep me posted when you have ideas about that :) Don't be crazy and take care of you :)

Thanks

**Comment by sanscheese** [comment]
Will the future plan be to still just work off the `tailwind.config.js` file for customizing? A big win for me with tailwind css is it's portability so hoping this won't be a new layer on TW config handling.

Also, sorry if this is starting to tangent too far from this issue, but are tailwind plugins able to work (or in the future plan)?

Really like the potential of this project. Congrats so far!

**Comment by christianalfoni** [comment]
Yeah, this project will follow Tailwind, so we are not doing anything on top. The change mentioned here is basically getting closer to Tailwind. Allowing you to define a theme value with a function, deriving off the other theme values :-)

It is likely possible to support plugins, though it would need some research. Do you have an example of a popular plugin? Just to see what it would be used for 😄 

The reason adding `utils` in this library is by just using the `utils` object is that now it is typed. It is not possible to type the plugin API of Tailwind CSS. So this would be like to support existing plugins, not necessarily to use that API to build new ones. At least my current thoughts 😄

**Comment by oorestisime** [comment]
This is quite popular https://github.com/tailwindcss/custom-forms

**Comment by Suniron** [comment]
Hi there ! 

You can now fix yours colors like that:

Configure:
![image](https://user-images.githubusercontent.com/36677774/88394628-0df81b00-cdc0-11ea-83bd-82d7068aa433.png)

... And use:
![image](https://user-images.githubusercontent.com/36677774/88394655-1a7c7380-cdc0-11ea-9c3d-bf727c76bb25.png)

Enjoy 👍

**Comment by Suniron** [comment]
I think that you can close this issue now
