### ISSUE TITLE
Tailwind package safe to use?

### ISSUE THREAD

**Issue by allforabit** [modulz/stitches#100]
Hi this really looks like a fantastic approach to styling components and brings a lot of really good ideas together. I see there's an issue mentioning that the tailwind package will be removed. I'm just wondering if it's advisable to depend on it for a project if that's the case or will it be just moved to another repo. Thanks v much :-)

**Comment by peduarte** [comment]
@allforabit we're planning on removing the Tailwind package from this repo, but I believe @christianalfoni will move it to his personal repo and continue maintaining it from there.

**Comment by allforabit** [comment]
Great thanks @peduarte !
