### ISSUE TITLE
Not Recognizing Variants with a dot

### ISSUE THREAD

**Issue by Lschulzes** [modulz/stitches#1003]
# Bug report

## Describe the bug
Not applying styles if there is a dot in the variable name, even being a valid TS object key

## To Reproduce 
1. Follow stitches.config.ts documentation and set the theme colors, name them with a dot, i.e. "red.500":"#fff"
2. Export it and import into a component

## Expected behavior
To style normally, but it does not apply the styles, the autocomplete works fine.

## Screenshots
Expected to work (But doesn't)
![image](https://user-images.githubusercontent.com/77251840/163075330-e448f0eb-904d-421f-ae5d-9e2bfe3ef7fe.png)

Workaround
![image](https://user-images.githubusercontent.com/77251840/163075394-bda16d70-acc8-49bc-8249-b0c3a6822edd.png)

## System information

- OS: Arch Linux
- Browser (if applies) Latest Chrome
- Version of Stitches: 1.2.7
- Version of Node.js: 16.14.2

**Comment by emrysal** [comment]
Have a look at https://github.com/modulz/stitches/issues/493#issuecomment-801241038

**Comment by Lschulzes** [comment]
Understood, thanks!
