### ISSUE TITLE
fontDisplay: "swap" Typescript error

### ISSUE THREAD

**Issue by hdennison** [modulz/stitches#1010]
# Bug report

## Describe the bug
Typescript complains about invalid `styles` object when a `@font-face` uses `fontDisplay: "swap"`
The swap of the font works correctly in the browser, but the error is present in the IDE and Jest tests.

## To Reproduce

1. See example at https://codesandbox.io/s/stitches-fontdsiplay-error-7bh0l4?file=/src/App.tsx
2. Comment/uncomment `fontDisplay: "swap"` on line 12 to see the error on line 23.

## Expected behavior
No Typescript error.

## System information
- OS: macOS
- Version of Stitches: 1.2.7 (localhost) and 1.2.8 (codesandbox)
- Version of Node.js: 16.14.0 (localhost) and 14.18.1 (codesandbox)

**Comment by hdennison** [comment]
That was quick!

Thanks a lot :)

**Comment by iamskok** [comment]
@hdennison I believe #1011 was reverted, and the error still persists. Can you please re-open this issue?
