### ISSUE TITLE
Cannot style a component that uses hooks

### ISSUE THREAD

**Issue by jjenzz** [modulz/stitches#102]
> Invalid hook call. Hooks can only be called inside of the body of a function component.

https://codesandbox.io/s/dreamy-visvesvaraya-hqt0u

**Comment by peduarte** [comment]
Ouch 😄 

@christianalfoni will prob know whats up

**Comment by jjenzz** [comment]
I WAS BEING AN IDIOT! I used the `styled-components` API instead of stitches... i.e. `styled(Component)({})` instead of `styled(Component, {})`

**Comment by peduarte** [comment]
😂
