### ISSUE TITLE
Extra Shorthands

### ISSUE THREAD

**Issue by colmtuite** [modulz/stitches#103]
I think we forgot to mention shorthands for `flex` and `flex-flow`.

**Comment by peduarte** [comment]
Also:
- `grid`
- `overflow`
- `outline`
- `list-style`

**Comment by richardbruskowski** [comment]
Not really sure if I simply did something wrong on my side, but couldn't get these to work, while `border-top` etc. worked fine, maybe they are missing as well:
- `border-block-start`
- `border-block-end`
- ...

**Comment by rafgraph** [comment]
Tokens in outline shorthand are not working for me, e.g. `outline: '2px solid $green600'`

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.
