### ISSUE TITLE
stroke property not working with color tokens

### ISSUE THREAD

**Issue by rubenmoya** [modulz/stitches#124]
Hello!

I'm on the latest `9.0.0-alpha.0` version and I found out that the `stroke` property is not working with color tokens, here is an example:

```tsx
import * as React from "react";
import { createStyled } from "@stitches/styled";

const { styled } = createStyled({
  tokens: {
    colors: {
      "custom-red": "red",
      "custom-black": "black"
    }
  }
});

const Svg = styled("svg", {
  width: "120px",
  height: "120px",
  backgroundColor: "custom-red",
  "> line": {
    strokeWidth: "2",
    stroke: "custom-black"
  }
});

export default function App() {
  return (
    <div>
      <Svg xmlns="http://www.w3.org/2000/svg">
        <line x1={0} y1={0} x2="100%" y2="100%" />
        <line x1="100%" y1={0} x2={0} y2="100%" />
      </Svg>
    </div>
  );
}
```

**Comment by peduarte** [comment]
@rubenmoya 

Yo!

both of those issues should now be released under `9.0.0-alpha.1`

**Comment by rubenmoya** [comment]
I can't see it on npm, is it published?

**Comment by rubenmoya** [comment]
I've checked it out and the box shadow is working like a charm, but there is something weird happening, it looks like any of the elements are rendering the `children`, you can check it out in [this codesandbox](https://codesandbox.io/s/stitchesstyled-ref-rv0m9?file=/src/App.tsx), it breaks when changing `@stitches/styled` to the `9.0.0-alpha.1`

**Comment by peduarte** [comment]
@rubenmoya haha sorry was still publishing when I sent this, didnt know you were online 😂 

`9.0.0-alpha.2` should be published now! 🚀

**Comment by rubenmoya** [comment]
Working like a charm! ✨  Thank you!

**Comment by aljhmi** [comment]
Hello!
I'm having the same issue with **textShadow** not working with color tokens.
I'm working with v0.0.3-canary.3

**Comment by peduarte** [comment]
@aljhmi hey! 

`textShadow` is not being parsed yet

For now you can access your tokens via the CSS variable function
```js
{
  textShadow: '2px 2px var(--color-red500)'
}
```

**Comment by jonatassales** [comment]
`strokeWidth` is not working when using `@stitches/react@^1.2.8`. Any chance this will be fixed on this package too?
