### ISSUE TITLE
Pseudo element issue in SSR

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#127]
not sure what is going on, but this works in CRA: https://codesandbox.io/s/stitches-cra-pseudo-elements-cpimy

and the same code doesn't work in SSR https://codesandbox.io/s/stitches-ssr-pseudo-elements-vj3nk

To make it work in SSR, replace ``""`` with ``''`` (use single quotes)

**Comment by hadihallak** [comment]
ah yeah. so this an issue with how you're setting the styles on the style tags which makes it so that the styles aren't escaped.
if you set the styles using `dangerouslySetInnerHTML` then it should work as it handles double quotes correctly:

```
<style
  key={index}
  dangerouslySetInnerHTML={{ __html: content }}
/>
```

**Comment by peduarte** [comment]
Legend!
