### ISSUE TITLE
Allow to set a custom injection target for css rules when running client-side

### ISSUE THREAD

**Issue by hadihallak** [modulz/stitches#130]
in styled-components, we used `StyleSheetManager` to inject styles in iframes. 
we need to make sure that similar functionality is possible/implemented in Stitches for the Modulz composer.

**Comment by eddiewang** [comment]
is this possible yet? trying to get stitches isolated inside an iframe.

**Comment by peduarte** [comment]
@eddiewang Not yet, will update this issue when we have a PR for it

**Comment by peduarte** [comment]
Closing in favour of: https://github.com/modulz/stitches/issues/357
