### ISSUE TITLE
value autocomplete isn't working inside variants.

### ISSUE THREAD

**Issue by hadihallak** [modulz/stitches#133]
You will get the autocomplete for the property but not the value when typing CSS inside a variant

spent a fair bit of time on this and it seems connected to the use of generics and the only way I could get it to work was if I break variants typing.

**Steps to reproduce:**
Create a styled component with variants then try typing something like `backgroundColor` inside a variant. notice how only the key is autocompleted and the value itself is not typed or autocompleted

**Comment by hadihallak** [comment]
Fixed in #134

**Comment by Armadillidiid** [comment]
I'm experiencing the same issue on version `0.6.1`
