### ISSUE TITLE
Jest complains about createStyled

### ISSUE THREAD

**Issue by rubenmoya** [modulz/stitches#137]
Hello!

I'm trying to test a component with Jest and React Testing Library and I got this error:

![image](https://user-images.githubusercontent.com/905225/91470749-66c24400-e895-11ea-9d05-d3f8b211a98a.png)

I'm not sure if it's something I can fix on my end or is something related to stitches

**Comment by hadihallak** [comment]
Hey @rubenmoya 👋 
If you could provide us with a minimal example that contains this issue then I might be able to help as the error seems to be related to the library but would need a minimal reproduction repo to debug it.

**Comment by rubenmoya** [comment]
Hello!

I created [this codesandbox](https://codesandbox.io/s/stitches-jest-error-su14x) with a reproduction, I'm using: Next.js, Jest, React Testing Library and babel-jest

**Comment by hadihallak** [comment]
Awesome! will take a look asap.

**Comment by peduarte** [comment]
@christianalfoni may have some insights on this too 🙏
