### ISSUE TITLE
Parse `text-decoration` shorthand

### ISSUE THREAD

**Issue by colmtuite** [modulz/stitches#142]
The `text-decoration` longhand properties work in browsers these days, so we need to parse this with color tokens.

**Comment by vivek12345** [comment]
@peduarte Can I look into this with obviously some help from you? 
Note: Contributing for the first time to a css in js library.

**Comment by peduarte** [comment]
Sure. Make sure to add @hadihallak to the review and ping him if you need anything 👍

**Comment by vivek12345** [comment]
Thank you. @hadihallak I have done some initial work around text-decoration shorthand and long hand properties. Would be super helpful if I can get some feedback around it and improve it to make it ready.

**Comment by hadihallak** [comment]
@vivek12345 Thank you so much for the contribution. will be taking a look in a couple of hours.
