### ISSUE TITLE
Gatsby plugin

### ISSUE THREAD

**Issue by cometkim** [modulz/stitches#156]
I'm happy to see a CSS-in-JS solution that has all the features I've ever wanted. I just build a plugin to use it with GatsbyJS.

https://github.com/cometkim/gatsby-theme-stitches

Is there a place to document this?

If you plan to support it officially, I'm willing to donate the package.

**Comment by peduarte** [comment]
@cometkim this is awesome 🎉 

I'll put together some sections in the docs on how to use it with Gatsby and Next.js, I'll make sure to mention this.
