### ISSUE TITLE
Integrate codesandbox with this repo

### ISSUE THREAD

**Issue by hadihallak** [modulz/stitches#163]
We need to integrate codesandbox in a way where each PR is built and deployed to a codesandbox to allow for quick testing and validation of PRs

**Comment by peduarte** [comment]
Maybe @christianalfoni can help with this? Hahaha

**Comment by vivek12345** [comment]
I tried to do that here in a fork of this repo
https://github.com/vivek12345/stitches/pull/2

It seems to work - might need some minor tweaks.
