### ISSUE TITLE
Improve debugging styled components

### ISSUE THREAD

**Issue by denniscual** [modulz/stitches#167]
When defining a Styled Component, it is named `Anonymous`. 
![image](https://user-images.githubusercontent.com/17754712/92161932-e9ce3600-ee63-11ea-8f4d-30b98c681715.png)

This basically affects the debugging experience.
I've been thinking maybe stitches can provide a babel plugin to infer the names based on the file name, etc. Or stitches can name the Component like this "StyledComponent(section)". I'm not sure though what would be the better approach for this. But for now, I can say it's hard to determine the styled-components in React dev tool.

**Comment by peduarte** [comment]
That's a great suggestion! Thanks for raising it.

Let's see what we can do here.

**Comment by peduarte** [comment]
@denniscual One way to improve this _right now_, is to add `displayName` to your components. Here's a [CodeSandbox demo](https://codesandbox.io/s/stitches-167-demo-with-displayname-xnd6k).

![CleanShot 2020-09-04 at 11 50 48@2x](https://user-images.githubusercontent.com/372831/92226380-f161ff00-eea4-11ea-8d47-d0a3bd01b584.jpg)

---

@hadihallak @christianalfoni Do you guys have any ideas on the least obstructive way of improving the debugging experience?

If possible, I'd like to avoid the need for babel plugins. But I don't know

**Comment by hadihallak** [comment]
@peduarte yeah, we can create a default label internally similar to what @denniscual suggested: `StyledComponent(tagName)`.

Will push this today but I also think that a babel plugin will be needed later as it's a lot cleaner to infer the name from the constant containing the component instead of using a default based on the tag but we can do this as a step 2 kind of thing

**Comment by peduarte** [comment]
@hadihallak sounds great.

If we can provide a good default experience, I'm fine with using babel as an enhancement (opt-in)

Thanks! <3
