### ISSUE TITLE
Document "Browser support"

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#174]

**Comment by jonathantneal** [comment]
For all functionality, our support is:

- Last 2 versions of WebKit browsers, Safari for iOS and macOS.
- Last 2 versions of Chromium browsers, Google Chrome and Microsoft Edge for Linux, Windows, and MacOS.
- Last 2 versions of Gecko browsers, Firefox for Linux, Windows, and MacOS.

Specifically, the library will only work in browsers whose JavaScript engines support `Symbol`, `Set`, and `Proxy`.

For the ability to see complex, recursive CSS Nesting, our support is:

- Last 1 versions of WebKit browsers, Safari for iOS and macOS.
- Last 1 versions of Chromium browsers, Google Chrome and Microsoft Edge for Linux, Windows, and MacOS.
- Last 1 versions of Gecko browsers, Firefox for Linux, Windows, and MacOS.

Specifically, the experience of complex, recursive nesting styles will only be visible to browsers whose CSS engines support `:is()`.

**Comment by peduarte** [comment]
Done in FAQ
