### ISSUE TITLE
Transition tokens not working?

### ISSUE THREAD

**Issue by imjoshellis** [modulz/stitches#175]
## Describe the bug

Not if I'm missing something about the syntax, but I can't seem to get tokens working with transitions. 

## To Reproduce

minimal example: https://codesandbox.io/s/keen-fermat-4jnoz?file=/src/App.js

1. Setup stitches and stitches.config.js
2. Add transition token `$slow: "all 1000ms"`
3. Add `$slow` token as value for `transition` in `styled()`
4. Hover over the component 

Notes: 
- Setting the exact same transition "inline" within the `styled()` object like `transition: "all 1000ms"` works as expected.
- Color tokens are working as expected.

## Expected

"Inline Transition" and "Token Transition" in the example to have identical behavior.

**Comment by peduarte** [comment]
Looks like a bug 🐛 

Thanks for raising it!

**Comment by imjoshellis** [comment]
I also noticed after submitting this that `transitions` isn't listed in the property mapping table at the bottom of the  [token page of the docs](https://stitches.dev/docs/tokens#property-mapping).

**Comment by vivek12345** [comment]
I can take a look at fixing this

**Comment by hadihallak** [comment]
@vivek12345 That's awesome! looking forward to it 💯 
let me know if you need help with anything.

**Comment by vivek12345** [comment]
Sure I will 👍

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.
