### ISSUE TITLE
Consider introducing a token getter function

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#177]
I'm thinking we need a token getter function for two reasons:
1. Better refactorability (this is an alternative method of using the token-aware values)
2. Apply tokens to properties that they don't necessarily belong to

---

Let me explain a little:

Token-aware values are a great DX, but some people prefer to be more explicit and to prioritize refactorability. 
For example, if I'm using TS, I'd like to be able to rename a token, and have every instance of that token renamed where its used.

It's common that users may want to get access to taken and apply to a CSS Property that is not auto mapped. We should allow this to happen in a first-class manner.

Currently, this can be achieved by:
```jsx
// 1. abstract the tokens
const tokens = {
  colors: {
    $purple500: "hsl(252,78%,60%)",
  }
}

// 2. apply it in the config
const { styled } = createStyled({ tokens })

// 3. consume it
const Button = styled("button", {
  backgroundColor: tokens.colors.$purple500
})
```

Overall, I think this works great. You can click to go to definition. You can rename a `$purple500` and it'll be renamed everywhere. You get typing for free. If multiple values are needed in shorthand, people can rely on string interpolation. And it just works when you change themes too. 

Demo for all that I've mentioned here: https://codesandbox.io/s/nervous-murdock-7z68f?file=/src/App.tsx

**The question here is:**
Is there a better way to achieve this, that doesn't require exporting and importing the theme?

---

If everyone thinks this is a decent approach, then I'm also happy not to add unnecessary API weight to the library

**Comment by christianalfoni** [comment]
Hm, if you want the refactor thing with TS I do not think you can do it any differently. To make things more dynamic you could introduce functions:

```ts
const Button = styled("button", {
  backgroundColor: (tokens) => tokens.colors.$purple500
})
```

TS might refactor that automatically actually, not sure. But yeah, that is the way I think you would need to introduce it 😄

**Comment by peduarte** [comment]
Yeah, alright. Let's keep it simple for now 👍
