### ISSUE TITLE
Styles not applied on deployed/built site

### ISSUE THREAD

**Issue by albingroen** [modulz/stitches#183]
# Bug report

## Describe the bug

In for example Next.js, when running

    yarn build

and then

    yarn start

And then going to localhost:3000, the styles don't seem to get applied until the next rerender or something.

## To Reproduce

Build for example a button component with a lot of different variants. When using it, pass the props using state hooks. 

1. Make sure it works in dev mode
2. Build project
3. Run built project
4. See the styles not being applied until the state hook changes

## Expected behavior

The initial style should be applied as it gets in dev mode

### Dev (first render)

![image](https://user-images.githubusercontent.com/19674362/92293487-498c1600-ef24-11ea-894b-86de55527a88.png)

### Built (first render)

![image](https://user-images.githubusercontent.com/19674362/92293495-5f99d680-ef24-11ea-82cf-277641008788.png)

After changing one of the dropdowns (ie. updating props) it will look as expected

## System information

- OS: macOS
- Browser: Chrome
- Version of Next.js: 9.5.3

## Additional context

[Repository](https://github.com/albingroen/stitches-test)
[Demo](https://stitches-test.vercel.app/)

**Comment by hadihallak** [comment]
Thanks for submitting this @albingroen
looking into this now

**Comment by hadihallak** [comment]
Hey @albingroen 
Looking at your repo, it seems that you don't have [SSR setup](https://stitches.dev/docs/server-side-rendering)
Alternatively, you could also use our nextjs stitches template by creating a next project using the following command: 

```
npx create-next-app --example with-stitches
```

Will be closing this issue now as you haven't configured SSR in your next project.
Let me know if you need any help.
