### ISSUE TITLE
Global styles not working with SSR

### ISSUE THREAD

**Issue by albingroen** [modulz/stitches#185]
# Bug report

## Describe the bug

When using SSR using the following command

    yarn create next-app --example with-stitches

Global styles don't seem to work

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `yarn create next-app --example with-stitches`
2. Add global styles
3. See them not getting applied

## Expected behavior

The global styles should be applied as they get on a project not using SSR

## System information

- OS: macOS
- Browser: Chrome
- Version of Next.js: 9.5.3

**Comment by peduarte** [comment]
@albingroen Hey! Thanks for raising this issue.  Yep, it seems there's an issue with `css.global` and SSR.

We'll look into it

**Comment by peduarte** [comment]
This is fixed in `0.0.3-canary.1`

```bash
yarn install @stitches/react@0.0.3-canary.1`
```

Note, this release contains the following breaking change:
- Util API #209
