### ISSUE TITLE
TS autocomplete for inline style props is a bit slow

### ISSUE THREAD

**Issue by binhxn** [modulz/stitches#187]
# Bug report

## Describe the bug

Maybe this is more of a clarification than it is a bug. When adding styles to a `styled` component and referencing tokens from the config file, autocomplete has been great and fast.

However, when attempting to override the current styles by using the inline `css` prop, autocomplete is a bit slow. This behavior also occurs on non-style props as well (i.e. `onClick` and other event handlers). 

## To Reproduce

1. Create styled component using the `styled` function
2. Add CSS property referencing token in config file
3. With newly created styled component, override previous styles with `css` prop
4. Notice slow autocomplete on Styled component (on newly created CRA project)

## Expected behavior

Expected fast or same autocomplete speed when referencing tokens through both `styled` function and inline `css` props

## Screen recording

![stiches-autocomplete-slow](https://user-images.githubusercontent.com/8155387/92308523-fc736880-ef52-11ea-8296-b19dc347c6ed.gif)

## System information

- OS: macOS Catalina - v10.15.6
- Version of Node.js: v14.4.0

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.

**Comment by binhxn** [comment]
Hello @peduarte 

So it seems autocomplete speed has improved, which is great! However, I spotted two new issues. 

1. Previously, the value of my CSS property (in this case, backgroundColor/color) would autocomplete and map to my available theme values. It looks like autocomplete returns with raw CSS colors, but not colors from the theme. Now, it does not. I also tried abstracting the styles object and passing it to the component consuming the styled component, but no luck. 
2. When trying to apply native event handlers, such as `onClick`, my styled component does not capture that during autocomplete. It looks like it's not recognized.

Here's a screen recording for more context:

https://user-images.githubusercontent.com/8155387/107815954-ee5b1c80-6d28-11eb-8484-f3659e881b28.mov


Thoughts on this? Please let me know if I'm using Stitches incorrectly in any way.

**Comment by peduarte** [comment]
Thanks! 
Cc @jonathantneal @hadihallak

**Comment by peduarte** [comment]
Closing in favour of #393 and https://github.com/modulz/stitches/issues
