### ISSUE TITLE
getStyles() API escapes values unexpectedly

### ISSUE THREAD

**Issue by cometkim** [modulz/stitches#188]
# Bug report

## Describe the bug

When using `css.getStyles()` for SSR, it emits unexpected output for pseudo-elements

## To Reproduce

1. Use pseudo-elements with `content: ""`  
    ```ts
    const Box = styled('button', {
      '::before': {
        content: `""`,
        display: 'block',
        width: '100px',
        height: '100px',
      },
    });
    ```
2. Extract css using `css.getStyles(...)`

## Expected behavior

the output contains css like:

```css
./*X*/_VsQRV/*X*/::before { content: ""; }
```

## Screenshots

![image](https://user-images.githubusercontent.com/9696352/92313455-dd361300-f006-11ea-9b3b-d1b7fa08ec71.png)

the value gonna be escaped as `&quot;&quot;;` unexpectedly.

EDIT: also font families

![image](https://user-images.githubusercontent.com/9696352/92313996-e5914c80-f00c-11ea-9470-70fc5749ae88.png)

## System information

- OS: Ubuntu 20.04
- Browser: Chrome
- ~~Version of Next.js:~~
- Version of Gatsby: 2.24.49 (with [gatsby-theme-stitches](https://github.com/cometkim/gatsby-theme-stiches))
- Version of Node.js: 14.3.0

## Additional context

It just works on CSR env.

**Comment by peduarte** [comment]
Hey, thanks for raising this. 

Yeah, looks like we have some bugs. I tried creating a repro with Next.js and discovered some unexpected results too: https://codesandbox.io/s/188-sb60z?file=/pages/index.js

We'll look into it.

/cc @hadihallak @christianalfoni

**Comment by cometkim** [comment]
@peduarte Sorry, this is my bad.

Escaping XML entities is a behavior of react-dom/server, not stitches.
I fixed the GatsbyJs plugin to use dangerousInnerHTML to make SSR works properly.

**Comment by cometkim** [comment]
@peduarte your codesandbox example also needs to use `dangerousInnerHTML` instead of children to build `<style>` element.

Document this on SSR section would be helpful :)

**Comment by peduarte** [comment]
@cometkim yeah I think that's a good idea! I've made this mistake more than twice now 😂
