### ISSUE TITLE
Responsive styles doesn't work when the breakpoint token is started with `$`

### ISSUE THREAD

**Issue by cometkim** [modulz/stitches#189]
# Bug report

## Describe the bug

`breakpoints` doesn't work when they are started with `$`.

## To Reproduce

```ts
export const { styled } = createStyled({
  breakpoints: {
    $sm: rule => `@media (min-width: 640px) { ${rule} }`,
    $md: rule => `@media (min-width: 1024px) { ${rule} }`,
    $lg: rule => `@media (min-width: 1280px) { ${rule} }`,
  },
})

const Box = styled('div', {
  display: 'flex',
  variants: {
    direction: {
      row: {
        flexDirection: 'row',
      },
      column: {
        flexDirection: 'column',
      }
    }
  }
});

render(
  <Box direction={{ initial: 'row', $lg: 'column' }} />
);
```

And start with `gatsby develop`.

## Expected behavior

Box variants changed on the resizing screen

## System information

- OS: Ubuntu 20.04
- Browser: Chrome
- ~~Version of Next.js:~~
- Version of Gatsby: 2.24.49 (with [gatsby-theme-stitches](https://github.com/cometkim/gatsby-theme-stiches))
- Version of Node.js: 14.3.0

## Additional context

**Comment by peduarte** [comment]
This is fixed in `0.0.2`

Thanks!
