### ISSUE TITLE
css returned "strings" don't work with classname

### ISSUE THREAD

**Issue by xaviergonz** [modulz/stitches#190]
https://codesandbox.io/s/funny-wilson-gzyju?file=/src/App.tsx

Basically it seems classname doesn't use the .toString() of the object, but rather the enumerable properties and therefore returns "atoms toString" instead of the actual classes.

Is there a recommended method to join css produced class names? If not, any chance stitches can provide its own "classnames" alike function to solve this?

**Comment by peduarte** [comment]
@xaviergonz hey 👋 

Thanks for raising this. 

For now, you can use `classNames` with stitches via the dynamic keys object syntax:

```js
classnames({ [className]: true })
```

Here's a demo: https://codesandbox.io/s/httpsgithubcommodulzstitchesissues190-9reoj?file=/src/App.tsx:355-405

There is [an issue](https://github.com/JedWatson/classnames/issues/153) in the classNames repo about it not calling `toString`. It looks like this feature has actually [been implemented](https://github.com/JedWatson/classnames/pull/170) but not released. 

So yeah, I'll close this and we can track it over there, but for now you can use the object syntax.

Thanks!

**Comment by xaviergonz** [comment]
Thanks for the info. It looks like the issue is two years old and the last merge was from 5 months ago. 

Are you sure it is not better to provide one? (I could implement it if needed) 😉

**Comment by peduarte** [comment]
@xaviergonz I know, unfortunately classnames hasnt been maintained very much. You can see in the comments people are asking for it to be released 😂 

This project is too immature to add stuff to it. Our main priority is to get stitches stable and ready for v1. 

We may consider it in the future, for sure 👍
