### ISSUE TITLE
Stitches with Ionic components

### ISSUE THREAD

**Issue by olidotjpeg** [modulz/stitches#191]
# Bug report

## Describe the bug
I've been playing around with Stitches for various use cases, and so far so good. However I reached a point that was a "tipping point" for me to use it over styled-components permanently.

I cannot use it with Ionic Components example below. Maybe I am misunderstanding the docs, but it should accept React components.

```

const ToolBar = styled(IonToolbar, {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    svg: {
        position: "relative",
        zIndex: 2,
        color: "#000"
    }
})
```

## To Reproduce
Setup a standard Ionic with React project -> https://ionicframework.com/docs/intro/cli
Setup Stitches
Try and create a stitched component similar to my code above.

## Expected behavior
Should wrap the Ionic component so I can style them with either direct styles or css properties.

## Screenshots
![image](https://user-images.githubusercontent.com/1591885/92368667-519caf00-f0f8-11ea-9456-275a41029406.png)

## System information

- OS: macOS
- Browser: Chrome
- Version of Node.js: 12.8.0

**Comment by peduarte** [comment]
Thanks for raising this. Im not aware of how ionic works so this would need some digging. Do you have any idea why this may happen?

**Comment by olidotjpeg** [comment]
Not quite sure how this is working. 

However I do know the Ionic components are all based on Stenciljs so perhaps it's something related to WebComponents maybe? (Without knowing the specifics)

https://stenciljs.com/docs/introduction
