### ISSUE TITLE
Handle color functions with tokens

### ISSUE THREAD

**Issue by mattfelten** [modulz/stitches#196]
**Is your feature request related to a problem? Please describe.**
I have a token, let's say `$black: #000`, and I want to use that token with an rgba function to change the opacity.

```
background: 'rgba($black, .1)',
```
This unfortunately doesn't work. From #168, I learned that tokens are actually CSS variables. So I tried the same thing here.

```
background: 'rgba(var(--colors-black), .1)',
```
This doesn't work either. After googling it, [using color functions and CSS variables is very tricky](https://blog.jim-nielsen.com/2019/generating-shades-of-color-using-css-variables/).

**Describe the solution you'd like**
I don't know what the solve would be, but this might be something good to solve at a library level.

**Comment by peduarte** [comment]
@mattfelten thanks for that, theres some work going on around parsing tokens and I think this is included. Ill keep this open and update it as we progress.

Thanks!

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.
