### ISSUE TITLE
getStyles() does not close keyframes block

### ISSUE THREAD

**Issue by cometkim** [modulz/stitches#200]
# Bug report

## Describe the bug

Using keyframes API could make unpredictable behavior on SSR because of the unclosed block.

## To Reproduce

Use keyframes and extract css using getStyles() API

## Expected behavior

result of `css.getStyles()` has valid CSS.

## Screenshots

![image](https://user-images.githubusercontent.com/9696352/92614648-3d72d080-f2f7-11ea-8ba3-1f6e2ecd67bf.png)

![image](https://user-images.githubusercontent.com/9696352/92614604-3350d200-f2f7-11ea-93fa-bf74874ecc7f.png)

## System information

- OS: Ubuntu 20.04
- Browser: Chrome
- ~~Version of Next.js:~~
- Version of Gatsby: 2.24.49 (with [gatsby-theme-stitches](https://github.com/cometkim/gatsby-theme-stiches))
- Version of Node.js: 14.3.0

## Additional context

https://github.com/cometkim/gatsby-theme-stitches/issues/1 is blocked

**Comment by peduarte** [comment]
@cometkim Thanks for raising. We'll get to it. PR's welcome if you feel like contributing 🚀
