### ISSUE TITLE
Improve bundle size

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#205]
The bundle size has grown from ~6kb to ~8kb over the last few weeks. Fair enough, we added a bunch of features 😂 

But I think there's room for improvement. 

It would be great if we can bring that back down 🚀🚀🚀

**Comment by cometkim** [comment]
![image](https://user-images.githubusercontent.com/9696352/92761497-b728be00-f3cc-11ea-8f00-086e32e85e80.png)

maybe Closure Compiler helps? :thinking:

**Comment by peduarte** [comment]
hmm Im confused. Currently it's ~8kb though. This looks bigger.  😄 

![CleanShot 2020-09-10 at 18 47 06@2x](https://user-images.githubusercontent.com/372831/92765909-0c95a880-f396-11ea-8931-bddc11a9a3c2.jpg)

**Comment by cometkim** [comment]
Tested in [closure compiler service](https://closure-compiler.appspot.com/home) with the `dist/react.cjs.prod.js` file and the original contained some additional comments to annotate compiler options.
