### ISSUE TITLE
Color tokens not applying linear-gradient 

### ISSUE THREAD

**Issue by eykrehbein** [modulz/stitches#210]
# Bug report

## Describe the bug

Defining a `linear-gradient` as color token & using it afterwards does not work. But the direct use of `linear-gradient`, without token variable, works.

## To Reproduce

**1. Edit the stitches config**

Given the following config to include the following.
```json
{
    "tokens": {
        "colors": {
            "$primary": "linear-gradient(90deg, #FEAC5E 0%, #C779D0 50%, #4BC0C8 100%)"
       }
    }
}
```

**2. Define a component that uses the token**

```tsx
const Box = styled("div", {
    width: "100px",
    height: "100px",
    background: "$primary"
})
```

**3. Check whether the Box has the correct gradient background.**

3) _=> If falsy:_

**4. Define the same component with the gradient string instead of the variable/token**

```tsx
const BoxString = styled("div", {
    width: "100px",
    height: "100px",
    background: "linear-gradient(90deg, #FEAC5E 0%, #C779D0 50%, #4BC0C8 100%)"
})
```
**5. Check whether the Box has the correct gradient background.**
  

3) _=> If truthy:_

Resolve this issue.

## Expected behavior

The linear gradient should be applied as background.

## System information

- OS: Windows 10
- Browser: Chrome 85
- Version of Node.js: 12.18.3

**Comment by eykrehbein** [comment]
I've looked a bit into the DevTools and found sth interesting. When using the token as background with the given code above, the `background-color` attribute is set instead of the `background` attribute, even though I've explicitly defined `background: $primary`, not `background-color: $primary`. 

Looked in the docs afterwards and found that only `background-color`  is supported for the `colors` tokens so probably that's the issue. 

However, this brings me to the next question, namely, why is "background" not supported as well?

**Comment by peduarte** [comment]
Thanks for raising this. I'll take a look on Monday and run some tests.

Off the top of my head I'm not sure what's going on. But we do have a shorthand parser for the background property, so that should be working. 

Couple of questions:
- for now, can you use background-image instead? (Assuming that works - it should)
- which version of stitches are you running? Maybe check the node_modules folder to get the exact version

Thanks!

**Comment by eykrehbein** [comment]
Cool, thanks for the fast response!

1. Just copy/pasted the gradient into the `background` attribute directly for now, it's fine as well :D 
2. Yea it works with simple colors as tokens. I assume that behaviour is caused by the [difference](https://developer.mozilla.org/en/docs/Web/CSS/background) between `background-color` and `background` attributes 
3. `@stitches/react@0.0.2`

Have a nice weekend!

**Comment by vivek12345** [comment]
After taking a look at the code, it appears that linear-gradient becomes background-image and background-image does not use tokens.

We can put a token check for background-image as well, but I am not sure if this is the right way or not.

**Comment by eykrehbein** [comment]
Well, I think adding (color) token parsing for background-image isn't the perfect way, since background-image isn't using colors.

**Comment by eykrehbein** [comment]
I think in this case it is not a good idea to add token parsing for the background image attribute, since `background-image` isn't meant to use colors.

**Comment by AceroM** [comment]
The `background-image` docs in [mdn](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image) have examples for using background-image with `linear=gradient`, I can definitely see the use case for token parsing for the background image attribute.

**Comment by vivek12345** [comment]
@peduarte is anyone working on this already? If not then I can take a look.

**Comment by peduarte** [comment]
@vivek12345 What about https://github.com/modulz/stitches/issues/175 😄 

But don't think so, @jonathantneal may have started some work related to parsing and tokens

**Comment by vivek12345** [comment]
Definitely. That is mostly done. I actually need some help with that PR
https://github.com/modulz/stitches/pull/181

I have mentioned that in the comment

**Comment by peduarte** [comment]
@vivek12345 I'll let Abdul know, think he was on holiday 😄

**Comment by vivek12345** [comment]
Thank you 🎉

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.
