### ISSUE TITLE
Refer to the component being created

### ISSUE THREAD

**Issue by carlosfpo** [modulz/stitches#212]
**Is your feature request related to a problem? Please describe.**
This goes back to the same problem I've always had with styled-components, the ability when creating the to refer to the same component that is being created. At the moment it is necessary to create 2 separate components to be able to refer to the previous component

**Describe the solution you'd like**
It just feels weird to create an extra component for these types of css rules, unless I'm just missing something and I am doing it entirely wrong. This is what it would look like:

```javascript
const Button = styled('button', {
  /* styles */
  [`+ ${this}`]: {} // Use this or any other keyword that better fits
});

```
**Describe alternatives you've considered**
This is a small example of the way that I've always had to do is something like this (styled-components).

```javascript
const StyledButton = styled('button', {
  /* styles */
})

const Button = styled(StyledButton, {
  marginLeft: 8px;
})
```

EDIT:
Just realized the example was not correct:
```javascript
const StyledButton = styled('button', {
  /* styles */
})

const Button = styled(StyledButton, {
  [`+ ${StyledButton}}`]: {
    marginLeft: 8px;
  }
})
```

**Comment by fnky** [comment]
My suggestion would be to add something like a `+ &` selector, where `&` references the parent selector, like in `& .button`.

**Comment by peduarte** [comment]
Yeah, that's one of the goals of the `&` character. 

Based on your examples that should be a good use case.

**Comment by carlosfpo** [comment]
Ok I just realized that the `&` was special in that regard and will work wonders for several use cases.

Although, the `+ &` will not work.
I used the interactive docs and I would suggest adding an example for this use case which works with the `& + &`

**Comment by peduarte** [comment]
@carlosfpo great idea. Feel free to close, unless there's anything else you wanna ask 👍
