### ISSUE TITLE
Compose elements from styled components

### ISSUE THREAD

**Issue by fnky** [modulz/stitches#214]
**Is your feature request related to a problem? Please describe.**

I often create elements which can be used both as static elements (divs, spans, etc.) but also allow them to be used as interactive elements (buttons, inputs) with the same styling.

An example of this is a "Tag" component, which can be used as a static element (e.g. inline with text), but also a button, which is clickable in other contexts. Both the components share the same styling, except that the interactive element also can have styling for hover state, that shouldn't be reflected on the static element.

**Describe the solution you'd like**

To make composition easier, one solution could be to allow passing a component to a styled element:

```js
const Tag = styled.span({ ... });

// Compose a button element from a Tag component with shared styling, including variants.
const TagButton = styled.button(Tag, {
  ':hover': {
    // style hover state for button element
  }
});
```

**Describe alternatives you've considered**

Currently the way I compose styling between components for multiple types of elements, is to use a plain object with the properties and spread them in the styled component like so:

```js
const tagStyle = {
  fontSize: 11,
  fontFamily: "$sans",
  fontWeight: "500",
  lineHeight: 1,
  backgroundColor: "#1A1D1F",
  borderRadius: "$2",
  color: "#646D75",
  py: "$1",
  px: "$2",
  alignSelf: "center",
  border: "none",

  variants: {
    state: {
      selected: {
        color: "#7CB1FF",
        backgroundColor: "#133261"
      }
    }
  }
};

const Tag = styled.span({
  ...tagStyle,
  display: "inline-block"
});

const TagButton = styled.button({
  ...tagStyle,

  ":hover": {
    color: "red"
  }
});
```

This works well, but has a few pitfalls:

- Requires types to be manually exported from the config file to get the correct type definitions and provided to the variable.
  - This could be fixed by allowing composition with `css` function, instead of plain objects.
- Needs some extra work, such as moving styles into an object and re-declare styles for each component (not the biggest pain).

There may be other pitfalls which are more subjective. For example, if you have a single file with a bunch of components, this could be less readable.

**Comment by baryla** [comment]
You can kind of achieve what you want by using the `as` attribute. 

Example:
```tsx
const Tag = styled.span({
  color: 'red'
});

const Button = styled(Tag, {
  ':hover': {
    color: 'green'
  }
});

const App = () => {
  return <Button as="button">Hello World</Button>
}
```

or

```tsx
const Tag = styled.span({
  color: 'red',
  variants: {
    type: {
      button: {
        ':hover': {
          color: 'green'
        }
      }
    }
  }
});


const App = () => {
  return <Tag type="button" as="button">Hello World</Tag>
}
```

But yeah, it feels a little weird in this case to be using the `as` attribute and actually in theory, it should be relatively easy to add support for what you want. If I get some spare time tomorrow, I'll create a PR :)

**Comment by fnky** [comment]
@baryla I tried the examples that you gave and as you also pointed out it is a bit odd to indicate the meaning of the component twice.

Thanks for looking into it!

**Comment by peduarte** [comment]
@fnky Hey, thanks for raising this. Composition is very important to us, and Stitches was built with composition in mind. I think your example is great. It's something we want to facilitate with Stitches. 

The way I'd approach it is by relying on the `styled` and `as` prop, as suggested by @baryla but I'd make use of `defaultProps`  too

```jsx
const Tag = styled.span({ ... });

const TagButton = styled.button(Tag, {
  ':hover': {...}
});

TagButton.defaultProps = { as: 'button' }
```

I like it because it keeps the API surface low, and still makes it possible to change the element later. For example, if you wanted to render it as an `a`.

Alternatively, we have an open suggestion for a `withComponent` API here https://github.com/modulz/stitches/pull/207 But not sure if this will land yet or not.

**Comment by fnky** [comment]
@peduarte Much appreciated! I didn't even think of using `defaultProps`. That could be a good way to do it. I'll play a little more around with it to see if I can find some alternative ways to do it.

The `withComponent` suggestion is certainly something that I was looking for. It makes composition quite easy, and I think if it could be integrated to the top-level API (`styled`) it could make it feel more first-class.

**Comment by peduarte** [comment]
@fnky alright, glad that works for you! feel free to close this, unless you need anything else. meanwhile we'll keep the `withComponent` suggestion opened.

**Comment by fnky** [comment]
Great, thanks!

**Comment by alessiogmonti** [comment]
Hello, 
I would like to style the Radix [navigation menu ](https://www.radix-ui.com/docs/primitives/components/navigation-menu). 

The featured example uses CSS, but I'd like to use Stitches and create a shared style between NavigationMenu.Trigger and NavigationMenu.Link. 

Duplicating the styles is one option, but I would like to know what parent component (`as : ??`) I can use that could contain both of these elements. 
Here are some of the relevant lines of code:


Stitches: 
```
const NavMenuTrigger = styled(NavigationMenu.Trigger, {
  display: "flex",
  alignItems: "flex-end",
  justifyContent: "space-between",
  gap: "$2",

  //Dupes:
  padding: "$8 $12",
  outline: "none",
  userSelect: "none",
  fontWeight: 500,
  lineHeight: 1,
  borderRadius: "$4",
  fontSize: "$16",
  color: "$sand1",
  "&:focus": {
    boxShadow: "0 0 0 2px $amber2",
  },
  "&:hover": {
    backgroundColor: "$amber10",
  },
});

const NavMenuLink = styled(NavigationMenu.Link, {
  display: "block",
  textDecoration: "none",
  fontSize: "$16",
  lineHeight: 1,

  //Dupes:
  padding: "$8 $12",
  outline: "none",
  userSelect: "none",
  fontWeight: 500,
  lineHeight: 1,
  borderRadius: "$4",
  fontSize: "$16",
  color: "$sand1",
  "&:focus": {
    boxShadow: "0 0 0 2px $amber11",
  },
  "&:hover": {
    backgroundColor: "$amber10",
  },
});
```

Original CSS:
```
.NavigationMenuTrigger,
.NavigationMenuLink {
  padding: 8px 12px;
  outline: none;
  user-select: none;
  font-weight: 500;
  line-height: 1;
  border-radius: 4px;
  font-size: 15px;
  color: var(--violet11);
}
.NavigationMenuTrigger:focus,
.NavigationMenuLink:focus {
  box-shadow: 0 0 0 2px var(--amberA7);
}
.NavigationMenuTrigger:hover,
.NavigationMenuLink:hover {
  background-color: var(--amberA3);
}

.NavigationMenuTrigger {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 2px;
}

.NavigationMenuLink {
  display: block;
  text-decoration: none;
  font-size: 15px;
  line-height: 1;
}
```

Additionally, Radix colors don't seem to work in stitches when applied to BoxShadow.
