### ISSUE TITLE
Compound Variants not working as expected with breakpoints

### ISSUE THREAD

**Issue by loiacon** [modulz/stitches#216]
# Bug report

## Describe the bug

When using `compoundVariants`, if we don't specify all breakpoint cases, the style will not be applied correctly.

## To Reproduce
1. Go to https://stitches.dev/docs/variants
2. Scroll down to `Compound variants` section
2. Change the last `<Button>` with:
```jsx
    <Button color="gray" appearance={{ initial: null, bp1: 'outline' }}>
      Button
    </Button>
```

## Expected behavior

The compound variant works as expected with responsive styles

## Screenshots

Gray Button with `outline` variant:
![image](https://user-images.githubusercontent.com/32134586/93252795-569ed580-f76c-11ea-8fce-c56320d5d475.png)

Gray Button with `outline` variant and responsive style:
![image](https://user-images.githubusercontent.com/32134586/93252849-69190f00-f76c-11ea-90e2-efc57e8e2281.png)

## System information

- OS: macOS
- Browser: Chrome 85.0.4183.102 (64-bit)

**Comment by peduarte** [comment]
@loiacon thanks for catching this bug 🐛  we'll look into it.

**Comment by peduarte** [comment]
This is fixed in `0.0.3-canary.1`

```bash
yarn install @stitches/react@0.0.3-canary.1`
```

Note, this release contains the following breaking change:
- Util API #209

**Comment by hadihallak** [comment]
hey @loiacon 👋 
this is the expected results as the compound variant never matched for it to be applied.

Doing this:
```
  <Button color="gray" appearance={{ initial: null, bp1: 'outline' }}>
      Button
    </Button>
```

Translates to this:
```
  <Button color={{ initial: 'gray' }} appearance={{ initial: null, bp1: 'outline' }}>
      Button
    </Button>
```

and as you can see above, the compound variant isn't going to match at any breakpoint so the compound styles are never applied (for a compound styles to be applied, they need to match at the same breakpoint)

I do see how this is confusing tho -- curious if you have any idea in mind on how we should handle this.

**Comment by loiacon** [comment]
Hey, @hadihallak, first of all, thank you and all the team to the great work with stitches. I'm really enjoying using it!

How about translate to all breakpoints if no one is specified?

Doing this:
```jsx
<Button color="gray" appearance={{ initial: null, bp1: 'outline' }}>
  Button
</Button
```

Translated to this:
```jsx
<Button color={{ initial: 'gray', bp1: 'gray' }} appearance={{ initial: null, bp1: 'outline' }}>
  Button
</Button>
```

With this approach, the library can get closer to how CSS works:
```scss
.button {
  color: gray; // this will be applied to all media queries
}
@media (...) {
  ...
}
```

**Comment by hadihallak** [comment]
yeah, this is similar to what i had in mind. the only issue i could see with this is that this approach will lead to the creation of a lot of responsive atom classes so this might affect performance.

Maybe we could optimize it so that it only does this treatment when the variant is a part of a compound variant
**Example one:**
```jsx
<Button color="gray" appearance={{ initial: null, bp1: 'outline' }}>
  Button
</Button>
```
here if both the color variant and appearance variants were part of a compound variant, the color variant will be turned into 
```jsx
// we add the breakpoint to color
<Button color={{ initial: 'gray', bp1: 'gray' }} appearance={{ initial: null, bp1: 'outline' }}>
  Button
</Button>
``` 
like in your example

**Example two:**
variants aren't part of a single compound variant
```jsx
<Button color="gray" appearance={{ initial: null, bp1: 'outline' }}>
  Button
</Button>
```
will turn into:
```jsx
// we didn't add the breakpoint to the color variant
<Button color={{ initial: 'gray' }} appearance={{ initial: null, bp1: 'outline' }}>
  Button
</Button>
```

**Example three**:
if both were part of a compound variant but non of them had responsive values applied to them like

```jsx
<Button color="gray" appearance="outline">
  Button
</Button>
```

it will translate to
```jsx
<Button color={{ initial: 'gray' }} appearance={{ initial: 'outline' }}>
  Button
</Button>
```

hmm... will keep this open for a few days just to think this through some more...

**Comment by loiacon** [comment]
I think this bug only happens when the variant is a part of a compound variant, so it's fair to optimize this only to them.
Looks great to me your solution to this problem!

**Comment by peduarte** [comment]
Closing in favour of @jonathantneal who has this under control
