### ISSUE TITLE
Mixed dependencies

### ISSUE THREAD

**Issue by artola** [modulz/stitches#220]
# Bug report

These packages have mixed `dependencies` and `devDependencies` therefore the consumer end-up installing packages not needed.

## Describe the bug

These should just be listed as `devDependencies`:

```txt
    "@types/node": "^13.11.1",
    "@types/react-test-renderer": "^16.9.3",
    "tslib": "^1.11.1"
```

## To Reproduce

Install the package and see.

## Expected behavior

Clear separation of "deps" into: `dependencies`, `devDependencies`.
(Only `peerDependency` for `react` is properly listed).

**Comment by peduarte** [comment]
Thanks for this. You're right 🤙 feel free to create a PR. Otherwise I'll get round to it tomorrow.

**Comment by artola** [comment]
@peduarte Pls fix it and release at your will. It is not a limitation for consumers. Thanks.

**Comment by peduarte** [comment]
https://github.com/modulz/stitches/commit/2c188626f0b3a903d0f16ffeec9d4fd163fca15f
