### ISSUE TITLE
Missing element types when using `as` in `defaultProps`

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#223]
# Bug report

## Describe the bug

The element types are missing when `as` is used in `defaultProps`. It works when used inline

## To Reproduce

https://codesandbox.io/s/stitches-ts-issue-forked-op7gi?file=/src/App.tsx

## Expected behavior

The types should reflect the element props passed to the `as` prop, both inline and in `defaultProps`

**Comment by jjenzz** [comment]
`defaultProps` is being deprecated https://github.com/facebook/react/pull/16210

**Comment by hadihallak** [comment]
As prop is being deprecated as @jjenzz , in fact we've removed support for it in #264 
@peduarte Is this issue still applicable?
