### ISSUE TITLE
Support numeric values for tokens

### ISSUE THREAD

**Issue by afzalsayed96** [modulz/stitches#226]
Can we have numeric values allowed for tokens like `fontWeights, `zIndices`, `linHeights`, etc?
Example:  https://codesandbox.io/s/stitches-ts-issue-forked-voh43?file=/src/stitches.config.ts

**Comment by aarongarciah** [comment]
It actually works 😄  This is a slightly modified version of your sandbox, just adding some styles to the paragraph https://codesandbox.io/s/stitches-ts-issue-forked-nw0u8?file=/src/App.tsx

**Comment by afzalsayed96** [comment]
@aarongarciah Since config has typescript errors no tokens show up in suggestions

**Comment by aarongarciah** [comment]
Oh! Then you probably should update the issue description. Doesn't say anything about types.

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.
