### ISSUE TITLE
TS: Property `as` is missing in type

### ISSUE THREAD

**Issue by jon301** [modulz/stitches#236]
# Bug report

## Describe the bug

I get the following TS error in VSCode when trying the "Responsive variants" example in the docs

![image](https://user-images.githubusercontent.com/122108/93850363-37450280-fcae-11ea-9556-e9f4478a2fb3.png)

`MyComp` definition, just for info: 

```
export const MyComp = styled('button', {
  backgroundColor: 'gainsboro',
  borderRadius: '9999px',
  fontSize: '13px',
  lineHeight: '1',
  fontWeight: 500,
  paddingTop: '10px',
  paddingBottom: '10px',
  paddingLeft: '16px',
  paddingRight: '16px',
  border: '0',
  ':hover': {
    backgroundColor: 'red'
  },
  variants: {
    color: {
      violet: {
        backgroundColor: 'blueviolet',
        color: 'white',
        ':hover': {
          backgroundColor: 'darkviolet'
        }
      },
      gray: {
        backgroundColor: 'gainsboro',
        ':hover': {
          backgroundColor: 'lightgray'
        }
      }
    }
  }
});
```

## Expected behavior

There should not be any error

## System information

- macOS
- Node 12.18.2

## Additional context

"@stitches/react": "^0.0.2"
"typescript": "4.0.3"

**Comment by peduarte** [comment]
@jon301 thanks for raising this issue 👍 

I can confirm this is happening in version `0.0.2` but not in the latest canary `0.0.3-canary.1`

If you want to try the latest canary, bear in mind there were some breaking changes. Refer to the release notes here: https://github.com/modulz/stitches/releases/tag/v0.0.3-canary.1

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.
