### ISSUE TITLE
Strict mode issues with util types

### ISSUE THREAD

**Issue by emadabdulrahim** [modulz/stitches#240]
## Describe the bug

Adding `strict: true` causes type errors for utils even though the util arg type is correct. I think.

## To Reproduce

https://codesandbox.io/s/stitches-003-canary1-forked-fqvfs?file=/src/App.tsx

## Expected behavior

```jsx
paddingX : "$3"
``` 
should cause no type issues since the util definitions types `value` param as `keyof theme["space"]`

**Comment by hadihallak** [comment]
Haha, I spent more time on this than I should've 😄 

the squiggly lines and type error messages are misleading as this isn't related to utils at all. 
it's just that the size variants specify maxWidth with a value that isn't from the space scale so the whole thing errors. simply changing maxWidth to a scale value will fix it

Here is an updated sandbox:
https://codesandbox.io/s/stitches-003-canary1-forked-3rlkc
