### ISSUE TITLE
Theme styles conflict when lazy loaded

### ISSUE THREAD

**Issue by jon301** [modulz/stitches#247]
# Bug report

## Describe the bug

It seems theme styles can conflict when they are lazy loaded.
If `theme-0` is loaded server side, and then we try to lazy load another theme, the name returned for the latter can also be `theme-0`, and their styles might conflict.

## Expected behavior

There should not be any conflict between different themes.

It seems theme names have an incrementing index. Maybe we should be able to pass an optional name so their styles cannot conflict even when eagerly or lazily loaded.

```
css.theme({
  name: 'super-dark', // --> generates name `theme-super-dark`
  colors: { ... }
})
```

## Screenshots

![2020-09-26 10 22 52](https://user-images.githubusercontent.com/122108/94336358-ddf90e00-ffe2-11ea-9179-7dc259015c7c.gif)

## System information

- OS: macOS
- Browser: Chrome
- Version of Next.js: 9.5.3
- Version of Node.js: 12.18.2

## Additional context

"@stitches/react": "0.0.3-canary.1"
"typescript": "4.0.3"

**Comment by peduarte** [comment]
Ohh very interesting. We'll investigate. Thanks for raising this! 

I've actually been thinking about making the `theme` function accept a name as the first argument which would be used as the class name.

**Comment by hadihallak** [comment]
I think we can solve this issue by hashing the theme to create a unique class for each theme which is something I don't think we're currently doing.

**Comment by peduarte** [comment]
@hadihallak I think the theme class needs to be predictable though - this is important when dealing with the "white flash of death" where usually we need to store the theme class in local storage.

**Comment by hadihallak** [comment]
@peduarte would it be enough if it's consistent? not sure what predictable means here in this context but if we're both talking about consistency then hashing should work for us as it will guarantee that a theme will always generate the same hash regardless of the environment.

**Comment by peduarte** [comment]
@hadihallak if it's consistent it should be fine, but not sure it's a good DX? What do you think? 

Initially I was thinking something along these lines, but its just an idea:
```jsx
const darkTheme = css.theme('theme-dark', {})

() => <div className={darkTheme} />
```
for localstorage hacks:
```js
// script.js - for demo purposes
document.body.classList.add(darkMode ? 'theme-dark' : undefined);
```

https://github.com/modulz/stitches-site/blob/master/public/noflash.js

**Comment by hadihallak** [comment]
@peduarte I like your solution better and it wouldn't be the end of the world if the user defines their theme-class I actually think this is better than a hash as it makes working with themes easier and this would only need to happen for a couple of times depending on how many themes the user did define)

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.
