### ISSUE TITLE
React.ComponentProps not working as expected

### ISSUE THREAD

**Issue by julianbenegas** [modulz/stitches#248]
# Bug report

## Describe the bug

When wanting to get the type of the props a stitches component receives, for example to be able to compose other components on top of it, `React.ComponentProps<typeof StitchesComponent>` is not working as expected — it's signaling weird errors and not providing correct typings. More context [in this discussion](https://github.com/modulz/stitches/discussions/213).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [this sandbox](https://codesandbox.io/s/stitches-ts-issue-8stcu?file=/src/App.tsx).
2. Scroll down to the implementetion of `<LoadingButton />`.
3. See that `<LoadingButton />` has type errors. (property `as` is required).
4. Also, see that the props are not button-specific (see screenshot below).

## Expected behavior

I expected LoadingButton to be error free with the props provided, and for prop suggestions to be button-specific.

## Screenshots

<img width="549" alt="CleanShot 2020-09-26 at 10 54 37@2x" src="https://user-images.githubusercontent.com/40034115/94342326-c2900200-ffe6-11ea-8c37-22fdac450ead.png">

**Comment by peduarte** [comment]
@julianbenegas thanks for raising this. in the works ⚙️

**Comment by dbismut** [comment]
I know this is is a closed issue, but what should be the right way to extract props from a component? This seems to work in latest canary, but looks a bit ugly:

```ts
// before canary (fires error in Canary)
React.ComponentProps<typeof StyledInput>>

// in canary
Partial<StitchesComponent<typeof StyledInput>>
```

**Comment by peduarte** [comment]
@dbismut which props do you want to extract? IMO there's only one thing that makes sense to extract, the variants, which you can do with the `StitchesVariants` Type Helper.

**Comment by dbismut** [comment]
@peduarte consider this:

```jsx
function MyComponent({onClick, ...props}) {
  return (
    <div onClick={onClick}>
      <StyledInput {...props} />
    </div>
  )
}
```

How would you type `props`?

**Comment by peduarte** [comment]
@dbismut 

would this work?



```tsx
type InputProps = React.ComponentProps<typeof StyledInput>

function MyComponent({onClick, ...props}: InputProps) {...}
```

**Comment by dbismut** [comment]
That's what I thought, it used to work pre-canary (see my first post). But it doesn't now (at least this morning). I'll paste the type error in an hour or so.

**Comment by dbismut** [comment]
Here it is @peduarte 

The code (simplified for the purpose of this message):

<img width="431" alt="image" src="https://user-images.githubusercontent.com/5003380/107882297-c5818580-6ee8-11eb-8e67-f5f488e27328.png">


The error:
```
No overload matches this call.
  The last overload gave the following error.
    Type '{ as?: "div" | undefined; color?: string | undefined; translate?: "yes" | "no" | undefined; hidden?: boolean | undefined; slot?: string | undefined; style?: CSSProperties | undefined; ... 252 more ...; input?: boolean | undefined; }' is not assignable to type 'IntrinsicAttributes'.
      Types of property 'css' are incompatible.
        Type 'InternalCSS<{ initial: ""; }, { colors: { elevation1: string; elevation2: string; elevation3: string; accent1: string; accent2: string; accent3: string; highlight1: string; highlight2: string; highlight3: string; }; ... 7 more ...; fontWeights: { ...; }; }, { ...; }, {}> | undefined' is not assignable to type 'InterpolationWithTheme<any>'.
          Type 'InternalCSS<{ initial: ""; }, { colors: { elevation1: string; elevation2: string; elevation3: string; accent1: string; accent2: string; accent3: string; highlight1: string; highlight2: string; highlight3: string; }; ... 7 more ...; fontWeights: { ...; }; }, { ...; }, {}>' is not assignable to type 'InterpolationWithTheme<any>'.
            Type 'InternalCSS<{ initial: ""; }, { colors: { elevation1: string; elevation2: string; elevation3: string; accent1: string; accent2: string; accent3: string; highlight1: string; highlight2: string; highlight3: string; }; ... 7 more ...; fontWeights: { ...; }; }, { ...; }, {}>' is not assignable to type 'Keyframes'.
              Type 'InternalCSS<{ initial: ""; }, { colors: { elevation1: string; elevation2: string; elevation3: string; accent1: string; accent2: string; accent3: string; highlight1: string; highlight2: string; highlight3: string; }; ... 7 more ...; fontWeights: { ...; }; }, { ...; }, {}>' is missing the following properties from type '{ name: string; styles: string; anim: number; toString: () => string; }': name, styles, anim
```

**Comment by peduarte** [comment]
@dbismut I cant replicate it :/ https://codesandbox.io/s/stitches-component-props-26eyu?file=/src/App.tsx:548-705

Can you?

**Comment by dbismut** [comment]
I can't reproduce it either in the sandbox (even with my tsconfig and upgrading TS to 4.1.5), I'll dig further tomorrow. Note that if I do this (spreading `css` out from the props), no more errors.

```tsx
type RowProps = React.ComponentProps<typeof StyledRow>

function Row({ css, ...props }: RowProps) {
  return <StyledRow {...props} />
}
```

**Comment by tmilewski** [comment]
Any updates here? I'm running into the same issue. If I spread out `css`, everything works.

```tsx
type ContainerCSSProp = { css?: CSS }
type ContainerVariants = StitchesVariants<typeof Container>
type ContainerOwnProps = ContainerCSSProp & ContainerVariants &  {
  name: string
  label: string
  helpId: string
  helpText?: string
  errors: Record<'message' | 'type', string>
}

type LabelComponent = Polymorphic.ForwardRefComponent<typeof DEFAULT_CONTAINER_TAG, ContainerOwnProps>

export const Label: LabelComponent = React.forwardRef(
  ({ id, name, label, helpId, helpText, errors, ...props  }, ref) => (
    <Container ref={ref} {...props}>
      <label id={id} htmlFor={name}>
        {label}
      </label>
```

**Comment by tmilewski** [comment]
@peduarte And put another way with the exact same outcome:

```tsx
// stitches.config.ts
// export type CSS = StitchesCss<typeof stitches>

// Label.tsx
type ContainerOwnProps = React.ComponentProps<typeof Container> & {
  name: string
  label: string
  helpId: string
  helpText?: string
  css?: CSS
  children: React.ReactNode[]
  errors: Record<'message' | 'type', string>
}

export const Label = React.forwardRef<HTMLDivElement, ContainerOwnProps>(
  ({ id, name, label, helpId, helpText, errors, ...props  }, ref) => (
    <Container ref={ref} {...props}>
```

**Comment by tmilewski** [comment]
Hey @dbismut, do you happen to have `@emotion` or any other styling library in your project... maybe as a sub-dependency?

**Comment by dbismut** [comment]
Nope.

**Comment by tmilewski** [comment]
@dbismut The reason I ask is `Emotion` types might be causing some issues with gems like the one below. You have the same error in yours:

`is not assignable to type 'InterpolationWithTheme<any>`

```ts
declare module 'react' {
  interface DOMAttributes<T> {
    css?: InterpolationWithTheme<any>
  }
}

declare global {
  namespace JSX {
    /**
     * Do we need to modify `LibraryManagedAttributes` too,
     * to make `className` props optional when `css` props is specified?
     */

    interface IntrinsicAttributes {
      css?: InterpolationWithTheme<any>
    }
  }
}
```

**Comment by dbismut** [comment]
@tmilewski in my case, Stitches is the only styling lib I'm using.

**Comment by tmilewski** [comment]
@dbismut I would maybe dig a bit deeper. This appears to be classic Emotion.

@peduarte I'm still trying to see what I can do, but, in my case, the issue is most likely Emotion. I have Storybook in my project, which pulls in Emotion and Emotion [sets global `css` props](https://github.com/modulz/stitches/issues/248#issuecomment-820629251).

If I figure anything else out, I'll report back, but if you have any ideas, I'd love to hear them!

**Comment by dbismut** [comment]
@tmilewski you're definitely right actually, I completely overlooked dev-deps, sorry for the over confidence above. I also have Storybook installed and removing it clears the error.

**Comment by dbismut** [comment]
I think I'm going to patch-package this...

**Comment by tmilewski** [comment]
@dbismut I'm glad that helped.

Upon further research, it appears that the issue is resolved in Emotion 11. However Storybook uses Emotion 10.

# The Fix
Here's the less-than-ideal but better than `patch-package` fix:

### Step 1: Install Emotion 11
`yarn add --dev @emotion/react`


### Step 2: Force Emotion 11

Force `@emotion/core` to use your updated `@emotion/react` by adding this in `tsconfig.json`:

```json
{
   "paths": {
      "@emotion/core": ["node_modules/@emotion/react"]
    }
}
```

### Step 3: Hope Storybook Updates Soon

### Step 4: Profit!

**Comment by dbismut** [comment]
Perfect! Thanks a lot!

**Comment by derekr** [comment]
Not sure what the implications here are in most scenarios (I'm just using storybook), but this workaround is effective without installing `@emotion/react`. You can route to an empty files.

```json
{
  "compilerOptions": {
    "paths": {
      "@emotion/core": ["./typings/index.d.ts"]
    }
  }
}
```

```tsx
// cribbed from stitches/design-system
import type * as Polymorphic from '@radix-ui/react-polymorphic'
import React from 'react'

import { styled, CSS, StitchesVariants } from '../../stitches.config'

const DEFAULT_TAG = 'span'

export const StyledText = styled(DEFAULT_TAG, {
	// reset
	lineHeight: 1,
	margin: '0',
	fontWeight: 400,
	fontVariantNumeric: 'tabular-nums',
	display: 'block',
	fontFamily: '$body',

	variants: {
		size: {
			1: {
				fontSize: '$1',
			},
			2: {
				fontSize: '$2',
			},
			3: {
				fontSize: '$3',
			},
			4: {
				fontSize: '$4',
			},
		},
		weight: {
			regular: {
				fontWeight: '$regular',
			},
			medium: {
				fontWeight: '$medium',
			},
		},
		variant: {
			gray: {
				color: '$gray950',
			},
			purple: {
				color: '$purple700',
			},
		},
	},

	defaultVariants: {
		size: '4',
		variant: 'gray',
		weight: 'regular',
	},
})

type TextCSSProp = { css?: CSS }
type TextVariants = StitchesVariants<typeof StyledText>
type TextOwnProps = TextCSSProp & TextVariants

type TextComponent = Polymorphic.ForwardRefComponent<
	typeof DEFAULT_TAG,
	TextOwnProps
>

export const Text = React.forwardRef((props, forwardedRef) => {
	return <StyledText {...props} ref={forwardedRef} />
}) as TextComponent

Text.toString = () => `.${StyledText.className}`
```

![CleanShot 2021-05-10 at 16 22 13](https://user-images.githubusercontent.com/22249/117736173-e5ed7300-b1ab-11eb-89c3-9a937212ff8e.png)

![CleanShot 2021-05-10 at 16 21 32](https://user-images.githubusercontent.com/22249/117736136-cd7d5880-b1ab-11eb-91c1-c06363e90dda.png)

**Comment by cr0cK** [comment]
An improvement of https://github.com/modulz/stitches/issues/248#issuecomment-778858393:

```typescript
// Helper in your app
export type StyledComponentProps<
  C extends keyof JSX.IntrinsicElements | React.JSXElementConstructor<any>
> = Omit<React.ComponentProps<C>, 'css'>


interface ICustomButton extends StyledComponentProps<typeof Button> {}

function CustomButton(props: ICustomButton) {
  return <Button {...props} />
}
```
