### ISSUE TITLE
font inherit does not work

### ISSUE THREAD

**Issue by rothsandro** [modulz/stitches#249]
# Bug report

## Describe the bug

The property `{ font: "inherit" }` on a button element (or any other) does not work. There will be no class for that property and the button will get the default font defined by your browser.

`{ fontFamily: "inherit" }` works fine.

## To Reproduce

1. Go to https://codesandbox.io/s/laughing-dream-xml7w?file=/src/App.js
2. Inspect the red button in DevTools (Computed > Search for "font-family")
3. The button has the default font of your browser instead of "Times" (defined on body)

## Expected behavior

The button should inherit the font.

**Comment by peduarte** [comment]
Thanks for raising this. @hadihallak probably related to the parser?

**Comment by hadihallak** [comment]
@peduarte yep.

**Comment by VaibhavAcharya** [comment]
Any updates ?

**Comment by peduarte** [comment]
We're working towards a stable version of Stitches, and all this will be fixed then. 

This new version is a whole re-write, taking into account all the learnings from the Beta. 

Should be released in a couple of weeks. Hang tight, it'll be worth it.

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.

**Comment by rothsandro** [comment]
Thanks, I've tested it with the pre-release and it works.
