### ISSUE TITLE
styled is not adding styles properly to custom React Components

### ISSUE THREAD

**Issue by carlesba** [modulz/stitches#250]
# Bug report

## Describe the bug

When a React component is wrapped with `styled`, the styles are not applied properly to the component.

## To Reproduce

check this [codesandbox](https://codesandbox.io/s/focused-kirch-bb5cf?file=/src/App.js). It's using Material UI Icons.

## Additional context

I noticed there's a `toString` and a `atoms` class in the html. It seems that creating classnames with `css()` needs to be stringified with `toString` so this may be related.

**Comment by carlesba** [comment]
I just found https://github.com/modulz/stitches/issues/229 
it may be related.

**Comment by peduarte** [comment]
@carlesba hey! thanks for this. looks related. I'll do a new canary release later, I'll let you know.

**Comment by peduarte** [comment]
Can you test it out in the latest release and report back? Thanks!

https://github.com/modulz/stitches/releases/tag/v0.0.3-canary.4
