### ISSUE TITLE
Roadmap to 1.0.0 🧘

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#252]
This is the roadmap to get Stitches to a stable 1.0.0 release. 

# Stitches

### Creation

<details><summary>Create CSS instance 

- [ ] done
</summary>

- export a `createCss` function
- `createCss` function can be called empty
- `createCss` function can be called with a config
- `createCss` returns a `css` function
- the `css` function is what we'll use to style things

```jsx
import { createCss } from ''@stitches/core'

const css = createCss()
```

> **JN**: The React version exports an object. Can we do that here, too?
</details>

<details><summary>Create config

- [ ] done
</summary>

We should be able to create a config

```jsx
const css = createCss({
  prefix: '',
  theme: {},
  utils: {},
  breakpoints: {},
  fonts: {}, // TBD
})
```
</details>

<details><summary>Create prefix

- [ ] done
</summary>

We should be able to create a `prefix`, which will be added to all generated class names

```jsx
const css = createCss({
  prefix: '',
})  
```
</details>

<details><summary>Create default theme

- [ ] done
</summary>

We should be able to create a default theme. This is done via the config

```jsx
const css = createCss({
  theme: {
    colors: {},
    space: {},
    fontSizes: {},
    fonts: {},
    fontWeights: {},
    lineHeights: {},
    letterSpacings: {},
    sizes: {},
    borderWidths: {},
    borderStyles: {},
    radii: {},
    shadows: {},
    zIndices: {},
    transitions: {},
  },
})
```
</details>

<details><summary>Create utils

- [ ] done
</summary>
  
We should be able to create utils
```jsx
const css = createCss({
  utils: {
    marginY: (value) => ({
      marginTop: value,
      marginBottom: value
    })
  }
})
  
// They can then be used like this
const component = css({
  marginY: '10px'
})
```

Question, should the util function be provided the config? Maybe for typing purposes?
```jsx
const css = createCss({
  utils: {
    marginY: (value) => ({
      marginTop: value,
      marginBottom: value
    })
  }
})
```
</details>

<details><summary>Create breakpoints

- [ ] done
</summary>
</details>

### Authoring

<details><summary>Style base

- [ ] done
</summary>

```jsx
css({
  backgroundColor: 'red',
  padding: '10px'
})
```
</details>

<details><summary>Style basic selectors

- [ ] done
</summary>

All [basic selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors) should work. Such ID selectors, attribute selectors, universal selectors, and type selectors.

```jsx
css({
  '&.extra-class': { color: 'red' },
  '&[extra-attribute]': {color: 'red'},
  '&#extra-id': { color: 'red' }
})
```

</details>

<details><summary>Style pseudo selectors

- [ ] done
</summary>

[Pseudo classes](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes) and [pseudo elements](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements) should work

```jsx
css({
  '&:hover': { color: 'black' },
  '&::before': { content: 'before' }
})
```
</details>

<details><summary>Style descendants

- [ ] done
</summary>

To style a descendant we omit the `&`

```jsx
css({
  '.descendant-class': { color: 'red' },
  'descendant-type': { color: 'red' },
  '[descendant-attr]': { color: 'red' },
  '#descendant-id': { color: 'red' }
})
```

</details>

<details><summary>Style chained selectors

- [ ] done
</summary>

To chain a selector, we use the `&` followed by the selector

```jsx
css({
  '&.extra-class': { color: 'red' },
  '&[extra-attribute]': {color: 'red'},
  '&#extra-id': { color: 'red' }
})
```
</details>

<details><summary>Style combinator selectors <sup>*</sup>

- [ ] done
</summary>

[Combinator selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors#Combinators) should work

> Question: Should it start with `&` or is it optional?

```jsx
css({
  '& + .adjacent-class': { color: 'red' },
  '& > .immediate-class': { color: 'red' }
})
```

> **JN**: I think it should be mandatory. We can support any non-`&` as implying a space. However, we should decide if a colon (like in `:hover`) should imply a space (where `:hover` is like `& :hover`), or if it should imply a combination like `&` (where `:hover` is like `&:hover`).
</details>

<details><summary>Style comma separated selectors

- [ ] done
</summary>

Comma separated selectors should work

```jsx
css({
  '&:hover, &:focus': { color: 'red' }
})
```
</details>

<details><summary>Style inline at-media rules <sup>*</sup>

- [ ] done
</summary>

[At-rules](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule) should work

> Question: with the exception of `@font-face` and `@keyframes`, correct?

```jsx
css({
  color: 'red',
  '@media (min-width: 480px)': { color: 'blue' },
  '@media print': { fontSize: '16px' }
})
```
</details>

<details><summary>Style Stitches components

- [ ] done
</summary>

We should be able to target other Stitches Components

```jsx
const componentA = css({ color: 'red' })

const componentB = css({
  [${componentA}]: { color: 'blue' }
})

// Based on this HTML
// <div className={componentB}>
//   <button className={componentA}>Hey</button> // this should be `color:blue`
// </div>
```
</details>

<details><summary>Extend Stitches components <sup>*</sup>

- [ ] done
</summary>

We should be able to extend other Stitches Components via the `css` function

> Question: or should we?

```jsx
const componentA = css({ color: 'red' })

const componentB = css(componentA, {
  color: 'blue'
})
```
</details>

<details><summary>Usage of <code>&amp;</code>

- [ ] done
</summary>

The `&` is useful for:
- chaining a selector
- qualifying a selector

```jsx
// chaining
css({
  '&:hover': { color: 'red' }, // => .component:hover { color: red }
  '&.some-element': { color: 'red' } // => .component.some-element { color: red }
})

// qualifying
css({
  '.some-element &': { color: 'red' } // => .some-element .component { color: red }
})
```

If the `&` isn't used, the selector will be treated as a descendant
```jsx
css({
  ':hover': { color: 'red' }, // => .component :hover { color: red }
  '.some-element': { color: 'red' } // => .some-element .component { color: red }
})
```
</details>

<details><summary>Create global styles <sup>*</sup>

- [ ] done
</summary>

We should be able to add global styles. All selector types should work here, with the exception of:
- `@font-face`
- `@keyframes`

```jsx
const globalStyles = css.global({
  body: {
    margin: 0
  }
})

() => {
  globalStyles();
  return <div />
}
```

This is our current API, but it's open for change. Related https://github.com/modulz/stitches/discussions/285

Tokens, breakpoints, utils, inline at-rules should also work.

We need to define how the global style object works. For example, are these equivalent? Should we support both?
```jsx
const globalStyles = css.global({
  body: {
    margin: 0,
    '@media (min-width: 480px)': {
      margin: '10px'
    }
  },
  '@media (min-width: 480px)': {
    body: { margin: '10px' }
  }
})

() => {
  globalStyles();
  return <div />
}
```
</details>

<details><summary>Create keyframes declarations

- [ ] done
</summary>

We should be able to create keyframes:
```jsx
const fade = css.keyframes({
  '0%': { opacity: 0 },
  '100%': { opacity: 1 }
})

css({
  animation: `${fade} 400ms ease-out`
})
```
</details>

<details><summary>Create font-face declarations <sup>*</sup>

- [ ] done
</summary>

We should be able to define custom fonts. This is something we currently don't support. 

There are 3 different ways we can support this.

1. Via `css.font`
Calling this function creates a new declaration and this gets injected as part of the global styles. Not sure if we'd need to assign a variable to this function and call it in the App's render? (as we do for `css.global`)

```jsx
css.font({
  fontFamily: 'UntitledSans',
  fontWeight: 400,
  src: '...'
})
```

2. Via `css.global`
```jsx
const globalStyles = css.global({
  body: {
    margin: 0
  },
  '@font-face': {
    fontFamily: 'UntitledSans',
    fontWeight: 400,
    src: '...'
  }
})

() => {
  globalStyles();
  return <div />
}
```

3. Via `createCss`
```jsx
createCss({
  fonts: [
    {
      fontFamily: 'UntitledSans',
      fontWeight: 400,
      src: '...'
    }
  ]
})
```
</details>

<details><summary>Parse token in values

- [ ] done
</summary>
</details>

<details><summary>Parse negative tokens in values

- [ ] done
</summary>
</details>

<details><summary>Create and parse scoped tokens

- [ ] done
</summary>
</details>

<details><summary>Vendor prefixing

- [ ] done
</summary>
</details>

### Variants

<details><summary>Add variants

- [ ] done
</summary>

We should be able to create variation of styles via `variants`
```jsx
css({
  color: 'black',
  variants: {
    variant: {
      red: {
        color: 'red'
      }
    }
  }
})
```
</details>

<details><summary>Set default variant <sup>*</sup>

- [ ] done
</summary>

We should be able to define a default variant
```jsx
const component = css({
  variants: {    
    variant: {
      red: {
        color: 'red'
      },
      blue: {
        color: 'blue'
      }  
    },
    size: {
      small: {
        fontSize: '12px'
      },
      large: {
        fontSize: '20px'
      }  
    }  
  }
})
  
component.defaultVariants = {
  variant: 'red',
  size: {
    // should also support initial
    initial: 'large',
  
    // should also work with at-rules or config breakpoints
    '@media (min-width: 480)': 'small'
  }
}

() => <button className={component} />
  
/*
  Generates:
  <button class="component123 component123--variant-red component123--size-large component123--size-small-123" />
*/
```
</details>

<details><summary>Apply variants

- [ ] done
</summary>

We need to be able to apply variants
```jsx
const Component = css({
  color: 'black',
  variants: {
    variant: {
      red: {
        color: 'red'
      }
    }
  }
})

() => <Component className={Component({ variant: 'red' })} />
```
</details>

<details><summary>Apply responsive variants <sup>*</sup>

- [ ] done
</summary>

We need to be able to apply variants responsively (or via an at-rule)
```jsx
const Component = css({
  fontSize: '16px',
  variants: {
    size: {
      medium: {
        fontSize: '18px'
      },
      large: {
        fontSize: '20px'
      }
    }
  }
})

() => <Component className={Component({ 
  size: { 
    '@media (min-width: 480px)': 'medium'
  }   
})}/>
```

To set different variants as the initial variant:
```jsx
() => <Component className={Component({ 
  size: { 
    // what should we call this key?
    initial: 'medium',
    '@media (min-width: 480px)': 'large',
  }   
})}/>
```
</details>

<details><summary>Add compound variants <sup>*</sup>

- [ ] done
</summary>

TBD
</details>

### Themes

<details><summary>Create additional themes <sup>*</sup>

- [ ] done
</summary>
    
We should be able to add themes
- use the `css.theme` function
- `css.theme` accepts a `tokens` object
- `css.theme` returns a classname which overrides the css variables
  
```jsx
const darkTheme = css.theme('theme-class', {
  colors: {
    $primary: 'tomato'  
  }    
});
 
```
This generates:
```css
.theme-class {
  --colors-primary: tomato
}
``` 
  
  
Should the theme class be optional?  
- optional class as 1st argument?
- optional class as last argument?
```
const darkTheme = css.theme('with-class', {})
const darkTheme = css.theme({}, 'with-class')

// without class, we need to ensure we generated a hashed class for this
// https://github.com/modulz/stitches/issues/247#issuecomment-699795587
const darkTheme = css.theme({})
```
</details>

<details><summary>Apply themes

- [ ] done
</summary>
    
We should be able to apply themes

```jsx
const darkTheme = css.theme('theme-class', {
  colors: {
    $primary: 'tomato'  
  }    
});

  
() => <div className={darkTheme}>Hello world.</div>
```
</details>

<details><summary>Theme getter <sup>*</sup>

- [ ] done
</summary>
    
We should be able to get tokens values
- get the CSS Custom Property 
- get the actual token value
  
```jsx
const css = createCss({
  theme: {
    colors: {
      red500: 'red'
    }
  }  
});
  
// get CSS Custom Property  
console.log(css.theme.colors.red500) // => var(--colors-red500)
  
// get actual token value
console.log(css.theme.colors.red500.value) // => red

// We need to apply un-mapped tokens to CSS properties
// in these cases, we want the CSS Custom Property to be returned
// so if later on a new theme is applied, this is updated
const component = css({
  boxShadow: `0 0 2px ${css.theme.colors.red500}`, // var(--colors-red500)
})
  
// We need to have access to the actual value, for when using with 3rd party libraries
// in this example the Chart lib draws in canvas, so we cant use CSS Custom Properties
new Chart({
  colors: {
    bar: css.theme.colors.red500.value, // red  
  }
})  
```
  
We also need to be able to get the theme tokens from additional themes
```jsx
// create an additional theme, overriding the red500 token
const darkTheme = css.theme('dark-theme', {
  colors: {
    red500: 'tomato'
  }
})

darkTheme.colors.red500 // => var(--colors-red500)
darkTheme.colors.red500.value // => tomato
```
</details>

### SSR

<details><summary>Server side rendering

- [ ] done
</summary>
</details>

<details><summary>Convert numeric values to <code>px</code>

- [ ] done
</summary>

Numbers should be converted to `px`. With the exception of the following properties:
- `line-height` 
- `font-weight`

```jsx
css({
  fontSize: 12, // => font-size: 12px
  width: 500, // => width: 500px
})
```
</details>

## Tech spec 

<details><summary>The `css` function 

- [ ] done
</summary>

- accepts a style object
- returns a Component function (link to component section)
- calling the Component function returns the class names
- the Component function accepts an object

```jsx
const component = css(stitchesStyleObject)

() => <button className={component} />
```
</details>

**Comment by VWSCoronaDashboard8** [comment]
Care to comment? I get the impression this project is being abandoned but I see no other mentions.

**Comment by colmtuite** [comment]
Definitely not abandoned @VWSCoronaDashboard8, the opposite, in fact! https://github.com/modulz/stitches/pull/338

**Comment by kylemh** [comment]
@VWSCoronaDashboard8 notice all the issues labelled by "fixed-in-beta".

**Comment by VWSCoronaDashboard8** [comment]
For people like me who are just watching this issue for updates on a stable version, things are not so apparent. Seeing this being closed, and the library still officially at version 0.0.2 for months gave me the wrong impression. Happy to hear things are moving forward! 👍
