### ISSUE TITLE
Specificity changed after upgrading to v0.0.3-canary.2

### ISSUE THREAD

**Issue by afzalsayed96** [modulz/stitches#256]
# Bug report

## Describe the bug

After upgrading to latest canary version specificity seems to have changed.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Check this sandbox: https://codesandbox.io/s/heuristic-zhukovsky-pec21?file=/src/App.tsx

## Expected behavior

Link color should have been $purple600 but it stays $gray600

**Comment by peduarte** [comment]
Thanks for raising this, really appreciate it. 

@hadihallak @jonathantneal I wonder what caused this regression, do you guys have any idea 🤔 I think the only piece of work we did that was somewhat related was https://github.com/modulz/stitches/pull/245

In any case, I think this is a good opportunity to add some test cases for these types of scenarios, what do you think?
