### ISSUE TITLE
[Question] Boolean Variants

### ISSUE THREAD

**Issue by rathesDot** [modulz/stitches#259]
I have a component that needs a "boolean variant" and I was wondering what the best way would be to achieve this:

```tsx
<Link underlined>My Link underlined</Link>
```

I thought about using something like

```ts
const Link = styled("a", {
  variants: {
    underlined: {
      textDecoration: "underlined",
    },
  },
})
```

but looks like this doesn't work.

So my current alternative is using true/false as strings.

```ts
const Link = styled("a", {
  variants: {
    underlined: {
      true: {
        textDecoration: "underlined",
      }
    },
  },
})
```

```tsx
<Link underlined="true">My Link underlined</Link>
```

Is there a better way to do this, or is this the only workaround for now?

**Comment by peduarte** [comment]
@rathesDot hey! 👋 

The way to define boolean variants is exactly as you've done it. Stitches will cast the boolean variants to strings internally, so you can use it as a normal boolean

For example, your `Link` Component
```jsx
const Link = styled("a", {
  textDecoration: "none",
  variants: {
    underlined: {
      true: {
        textDecoration: "underline"
      }
    }
  }
});
```

Can be used like this:
```js
<Link underlined href="https://stitches.dev">stitches.dev</Link>
```

Demo: https://codesandbox.io/s/lively-leaf-446vc?file=/src/App.tsx:871-927

**Comment by rathesDot** [comment]
Hey @peduarte, 

thanks for the quick reply! I'm surprised why it didn't work for me when I tried it two days ago. Let me get back to it this afternoon and see if I can somehow reproduce it!

**Comment by peduarte** [comment]
@rathesDot ok! feel free to close this issue when ready 👍  Thanks!

**Comment by rathesDot** [comment]
I've double-checked and it looks like it's another problem. The `Link` component of Gatsby is creating troubles when used as `as={GatsbyLink}` ... So this issue is resolved!

Thanks again for your help @peduarte!

**Comment by peduarte** [comment]
Oh, yeah. Related: https://twitter.com/peduarte/status/1303008101851897856

**Comment by rathesDot** [comment]
Yep, that's it! Same problem. I'm trying to create a component library that does not rely on framework components but looks like I will need to create one that wraps around the gatsby link
