### ISSUE TITLE
[Request] allow a function for variants

### ISSUE THREAD

**Issue by effectiveduck** [modulz/stitches#265]
**Is your feature request related to a problem? Please describe.**
I'm trying to build the stack component from [every-layout.dev](https://every-layout.dev/layouts/stack/) but to set styles based on a prop I need to create an override css object which I can't mix with the top level css prop so I've had to ignore it.

```tsx
import React from "react";
import { TCssWithBreakpoints } from "@stitches/react";
import { MarginTopProperty } from "@stitches/core";
import { styled, Config } from "stitches.config";

declare type $ElementProps<T> = T extends React.ComponentType<infer Props>
  ? Props extends object
    ? Props
    : never
  : never;

type StackBaseProps = Omit<$ElementProps<typeof StackBase>, "as">;

type StackProps = StackBaseProps & {
  space?: MarginTopProperty<keyof Config["tokens"]["space"]>;
  splitAfter?: number;
};

const Stack: React.FC<StackProps> = ({
  space = "$1",
  splitAfter,
  css: _,
  ...props
}) => {
  const override = React.useMemo((): TCssWithBreakpoints<Config> => {
    if (!splitAfter)
      return {
        " > * + *": {
          marginTop: space,
        },
      };
    else
      return {
        " > * + *": {
          marginTop: space,
        },
        ":only-child": {
          height: "100%",
        },
        [` > :nth-child(${splitAfter})`]: {
          marginBottom: "auto",
        },
      };
  }, [space, splitAfter]);

  return <StackBase css={override} {...props}></StackBase>;
};

export default Stack;

const StackBase = styled("div", {
  display: "flex",
  flexDirection: "column",
  justifyContent: "flex-start",
});

```

**Describe the solution you'd like**
I'd like the variants api to accept a function to handle theoretically endless variants.

```tsx
import { styled } from "stitches.config";

const Stack = styled("div", {
  display: "flex",
  flexDirection: "column",
  justifyContent: "flex-start",
  variants: {
    space: (value) => ({
      " > * + *": {
        marginTop: value,
      }
    }),
    splitAfter: (value) => ({
      ":only-child": {
        height: "100%",
      },
      [` > :nth-child(${splitAfter})`]: {
        marginBottom: "auto",
      }
    })
  }
});

export default Stack;

```

As far as I can tell these solutions are functionally the same except I can still use the css prop.

**Comment by effectiveduck** [comment]
This could be done using locally scoped css variables, this wouldn't work for half my example but it's still be a really nice feature. Also the api doesn't have to be variant functions, that just made sense to me but anything that allows an unspecified value (not a defined variant) to be passed in to apply some styles would b very handy, kind of like styled system but more deliberate and powerful.

**Comment by peduarte** [comment]
@effectiveduck thanks for the suggestions. At this time we're not considering this API. Stitches has a very high focus on performance and a goal to keep the API surface as simple as possible.

I'll keep this in mind and wait until we are out of beta to see if there are more requests. 

thanks so much I really appreciate it <3
