### ISSUE TITLE
Allow standard CSS properties to have their types overwriten by utilities

### ISSUE THREAD

**Issue by djgrant** [modulz/stitches#266]
First of all, thanks for creating a very cool library! 

Since using styled-styem, I've wanted to take their concept of [responsive values](https://styled-system.com/responsive-styles) and implement it within styled components:

```js
styled.div({
	padding: [10, 20]
})
```

With previous CSS-in-JS solutions (emotion, styled-components etc.) this can't be done, but with stiches' utils it's suddenly on the cards!

I appreciate that array scales are not very popular around here (and understand the reasons!) so in a more stitches fashion we'd have:

```js
styled('div', {
	padding: { initial: 10, $bp1: 20 }
})
```

And, in the component itself, there would be a way of composing styles similar to styled-system:

```js
<Box css={{ padding: { initial: 10, $bp1: 20 } }} />
```

I've built out a solution, however, I've stumbled with overriding default CSS properties. Even with `utilityFirst` enabled, type definitions from the util will not be used.

You see a repro of the problem here https://codesandbox.io/s/stitches-responsive-values-69u4x?file=/src/Button.ts.

**Comment by djgrant** [comment]
Actually, how would you feel about this being a core feature?

**Comment by peduarte** [comment]
@djgrant thanks for raising this issue. great work there 👏 we'll take a look at the overriding issue you're referring

> Actually, how would you feel about this being a core feature?
I'm not sure. Are you proposing that over what we currently have, or have both?

What's your opinion about this API when a component requires different styles on different breakpoints?


**Proposal:**
```js
{
  display: {
    initial: 'flex',
    bp5: {
      display: 'grid'
    }
  },
  flexDirection: {
    initial: 'column',
    bp3: 'row'
  },
  alignItems: {
    initial: 'center',
    bp5: 'start'
  },
  gap: {
    initial: '$4',
    bp3: '$5',
    bp5: '$6
  },
  maxWidth: {
    bp3: '600px'
  },
  marginY: {
    bp5: {
      marginY: '$5'
    }
  }
}
```

**Current:**
```js
{
  display: 'flex',
  flexDirection: 'column',
  alignItems: 'center',
  gap: '$4',

  bp3: {
    flexDirection: 'row',
    gap: '$5',
    maxWidth: '600px'
  },

  bp5: {
    display: 'grid',
    algignItems: 'start',
    gap: '$6',
    marginY: '$9'
  }
}
```

**Comment by djgrant** [comment]
The proposed would be bang on the buck. I'd definitely use it! 

> Are you proposing that over what we currently have, or have both?

Both! I think there are some use cases better suited to single-property responsive values (as proposed), while in others it makes more sense to group responsive rules together.

**Comment by peduarte** [comment]
Closing this in favour of https://github.com/modulz/stitches/issues/382

**Comment by macarie** [comment]
> > Actually, how would you feel about this being a core feature?
> > I'm not sure. Are you proposing that over what we currently have, or have both?
> 
> What's your opinion about this API when a component requires different styles on different breakpoints?
> 
> **Proposal:**
> 
> ```js
> {
>   display: {
>     initial: 'flex',
>     bp5: 'grid'
>   },
>   flexDirection: {
>     initial: 'column',
>     bp3: 'row'
>   },
>   alignItems: {
>     initial: 'center',
>     bp5: 'start'
>   },
>   gap: {
>     initial: '$4',
>     bp3: '$5',
>     bp5: '$6'
>   },
>   maxWidth: {
>     bp3: '600px'
>   },
>   marginY: {
>     bp5: '$5'
>   }
> }
> ```

Has this ever been implemented? If not, is there an issue tracking this proposal?
