### ISSUE TITLE
Custom Properties Prefixed With Additional Hyphen

### ISSUE THREAD

**Issue by joe-bell** [modulz/stitches#267]
# Bug report

## Describe the bug

I've been working on getting an integration of [`raam`](https://github.com/joe-bell/raam/pull/89) working for Stitches when I hit a big hurdle with custom properties

Any `--custom-property` definition gets transformed to `---custom-property`. This additional prefixed hyphen isn't expected and in most cases causes invalid styles.

## To Reproduce

See https://codesandbox.io/s/stitches-custom-properties-repro-th73h?file=/pages/index.js

## Expected behavior

Custom properties should return in the same format they were defined

## System information

```json
  "dependencies": {
    "@stitches/react": "0.0.3-canary.3",
    "next": "latest",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
  "devDependencies": {
    "@stitches/core": "0.0.3-canary.2",
    "@types/node": "14.0.27",
    "@types/react": "16.9.46",
    "typescript": "3.9.7"
  },
```

**Comment by jonathantneal** [comment]
Hey @joe-bell, thanks for reporting this and including a sandbox.

First, while this doesn’t resolve the real issue, you can work around this issue right now by changing line 71 in your `magic.config.js` from `---magic` (3 dashes) to `-magic` (1 dash).

I would expect that if you declared the custom property with 2 dashes (i.e `--magic`) then you would also reference it with 2 dashes (i.e. `var(--magic)`). And I would expect that if you wanted to use 3 dashes it would work as well (i.e. `---magic` and `var(---magic)`).

**Comment by jonathantneal** [comment]
@joe-bell, would you let me know if this matches your expectations?

See https://codesandbox.io/s/stitches-custom-properties-repro-forked-uuzqc?file=/stitches.config.js:1367-1668

**Comment by joe-bell** [comment]
Yes exactly! Thanks for resolving this so quickly, really appreciate it
