### ISSUE TITLE
Parsing error of <bg-size> in background shorthand

### ISSUE THREAD

**Issue by apostolos** [modulz/stitches#276]
# Bug report

## Describe the bug

Using the following:

```json
{
  "background": "linear-gradient(white, black) bottom / 0 2px no-repeat"
}
```

produces a `background-size` of `0px`

## To Reproduce

https://codesandbox.io/s/stitches-background-size-parsing-bug-s3pe7

## Expected behavior

`background-size` should have a value of `0 2px`

https://developer.mozilla.org/en-US/docs/Web/CSS/background

## System information

- `@stitches/react`: `0.0.3-canary.3`

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.

**Comment by apostolos** [comment]
@peduarte confirmed fixed!

Thank you, closing.
