### ISSUE TITLE
Issues with comma separated selectors

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#278]
# Bug report

## Describe the bug

I found some issues with the selectors generation when comma separating them

## To Reproduce

https://codesandbox.io/s/exciting-currying-853rx?file=/src/App.tsx

Note how in this example, `hover` and `focus` are not generated correctly. `hover` is missing the hash, and `focus` is not applying the specificity fix.

In the descendant selector example, the `a` is missing the parent selector.

## Expected behavior

![image](https://user-images.githubusercontent.com/372831/95787153-36195b00-0cd9-11eb-9ca7-090955be5c71.png)
![CleanShot 2020-10-12 at 22 20 45@2x](https://user-images.githubusercontent.com/372831/95787156-37e31e80-0cd9-11eb-957d-f973b5f28373.jpg)

**Comment by hadihallak** [comment]
@peduarte your sandbox is not targeting the latest canary which contains the comma-separated rules fix

so you simply need to update the sandbox to use the latest canary and then update the hover,focus bit to 
```
  ":hover,:focus": {
    color: "black"
  }
```

I did however find another issue related to ampersand and the specificity fix which I'm looking into now

**Comment by peduarte** [comment]
@hadihallak oooft, my bad. perhaps it was a tad too late to be raising issues.

the issue I was meant to raise was this:

![image](https://user-images.githubusercontent.com/372831/95840618-a90beb80-0d44-11eb-988f-e3ca7195b0b0.png)

Note how the `focus` selector doesn't contain the right specificity. Looks like you spotted it as well 👍 

Same sandbox https://codesandbox.io/s/exciting-currying-853rx?file=/src/App.tsx

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.
