### ISSUE TITLE
Allow static properties to be added to Stitches Components

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#287]
I think we should allow users to add static properties to Stitches Components. This will be handle if we want to re-export Radix Components

Example: https://codesandbox.io/s/patient-cloud-80uh8?file=/src/App.tsx

**Comment by marceloadsj** [comment]
You can use it like this:

```typescript
const Image = styled("img", {});

export const Avatar = Object.assign(styled("div", {}), { Image });
```

**Comment by hadihallak** [comment]
@peduarte  The suggestion by @marceloadsj is the correct way of doing this while also retaining types

**Comment by peduarte** [comment]
Excellent!
