### ISSUE TITLE
Override element during composition.

### ISSUE THREAD

**Issue by colshacol** [modulz/stitches#288]
When composing `Text`, I would like to be able to override the element tag, `"p"`.

```js
const Text = styled("p", {
  color: "blue",
  fontWeight: 400
})

const Heading1 = styled(Text, {
  fontSize: 32,
  fontWeight: 700
})
```

Essentially, I am inquiring about a more elegant way of doing this:

```js
const _Heading1 = styled(Text, {
  fontSize: 32,
  fontWeight: 700
})

const Heading1 = (props) => {
  return <_Heading1 {...props} as='h1' />
}
```

Is there any API to support something like this?

```js
const _Heading1 = styled("h1", Text, { })
```

Or this?

```js
const _Heading1 = styled(Text, {
  as: "h1",
})
```

I've looked, even read through the source, but do not see one. Thought I might have missed something.

Appreciate you!

**Comment by peduarte** [comment]
Hey @colshacol 👋 

Current the way I'd do this is via the [as prop](https://stitches.dev/docs/overriding-styles#overriding-the-html-tag).

You can also  use React's `defaultProps`althought that is being deprecated at some point:
```jsx
const _Heading1 = styled(Text, { })
_Heading1.defaultProps = { as: 'h1' }
```

We have a discussion open that relates to your question, you can follow along or join in here https://github.com/modulz/stitches/discussions/242
