### ISSUE TITLE
How to access stitches component's props interface

### ISSUE THREAD

**Issue by djgrant** [modulz/stitches#289]
I would like to be able to get the interface of a stiches component's props. The particular usecase I have in mind is to allow me to pass a `css` prop from a parent component to a stitches component. I'm unsure how to type this.

This is what I'm hoping to achieve:

```ts
const Box = styled('div', {});

interface CustomProps {
	css: ? // should be equal to BoxProps["css"]
}

const Custom: React.FC<CustomProps> = ({ css, children }) => (
	<Box css={{ margin: "$1", ...css }}>{children}</Box>
);
```

I've tried alternative patterns such as:

```ts
const Box = styled('div', {});
const UnstyledCustom = (...props) => <div {...props}>{children}</div>
const Custom = styled(UnstyledCustom, { margin: "$1});
```

However, I'd still value the flexibility and readibility of the former approach.

**Comment by peduarte** [comment]
As of `0.0.3-canary.4` you can do that. More info in the [release logs](https://github.com/modulz/stitches/releases/tag/v0.0.3-canary.4)

But here's the gist of it:
```tsx
import {StitchesProps} from '@stithces/react'

const Box = styled('div', {});

type MyBoxProps = StitchesProps<typeof Box> & {
  myCustomProp?: any
}

function MyBox(props: MyBoxProps) {
  return <Box {...props} />
}
```

You can also import `StitchesVariants` to extract only variant types

**Comment by djgrant** [comment]
Thanks @peduarte, this is great!

I finally got a chance to upgrade to canary 4. It all works well, however, I did notice that you do not get full type data on the `css` prop. (See https://codesandbox.io/s/laughing-agnesi-bui98?file=/src/App.tsx).

I assume `StichesProps` is not aware of the user-defined config. Perhaps it could take a second type argument: `StichesProps<typeof Component, Config>`.

**Comment by djgrant** [comment]
Another issue I've noticed is that the `css` prop is typed as `string & { ... }`. This makes it awkward to merge anything with `css`:

```ts
import {StitchesProps} from '@stitches/react'

const Box = styled('div', {});

type MyBoxProps = StitchesProps<typeof Box> & {
  myCustomProp?: any
}

function MyBox({css, ...props}: MyBoxProps) {
  return <Box {...props} css={{ padding: 20, ...css }} />
}
```

See https://codesandbox.io/s/cranky-chatelet-lvpql for error

**Comment by peduarte** [comment]
@djgrant Ah, yes. @hadihallak is working on many Typescript improvements here https://github.com/modulz/stitches/pull/294

I think it should cover the issues you're having, but @hadihallak can you confirm, please?

**Comment by hadihallak** [comment]
@peduarte 
`StitchesProps` should include the correct typing of the CSS prop as this is something that we should be able to infer

regarding `string & { ... }` I'm not completely sure about this but do you know why it's typed as a string in addition to the CSS object? I'm guessing this is from the time where we allowed to do overrides outside the CSS prop which could result in a string but I'm not sure it's relevant now

**Comment by JoshRosenstein** [comment]
@hadihallak `(string & { })`  is a workaround to get IntelliSense on type unions of 'literals' | string.
This a long standing issue, see https://github.com/Microsoft/TypeScript/issues/29729

**Comment by peduarte** [comment]
Since `0.1.0-canary.0` we support `StitchesCss` type helper. More info https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta
