### ISSUE TITLE
css.global uses first defined styles, not last defined styles

### ISSUE THREAD

**Issue by rafgraph** [modulz/stitches#290]
# Bug report

## Describe the bug

`css.global` uses first defined styles, not last defined styles.

## To Reproduce

https://codesandbox.io/s/some-platform-vg40r-vg40r

## Expected behavior

For the last defined styles to take precedent. In the codesandbox the background color of the body should be green.

**Comment by peduarte** [comment]
@rafgraph great catch. Im adding this to our test suite to make sure we catch things like this in the future. 

We'll take a look. thanks!

**Comment by rafgraph** [comment]
This seems to be fixed in `0.0.3-canary.4`, see https://codesandbox.io/s/stitches-003-canary4-vg40r-forked-x5m7f
