### ISSUE TITLE
Unable to use predefined utils inside other utils

### ISSUE THREAD

**Issue by joe-bell** [modulz/stitches#291]
# Bug report

## Describe the bug

When trying to use another function from `utils` inside another `util`, the CSS output is as follows:

```css
function-name: value;
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to this [CodeSandbox example][CodeSandbox]
2. Scroll down to the `container` utility (where `maginX` is used)
3. Inspect element in the preview window to see the output

## Expected behavior

I would expect utils to work inside other utils **but** I appreciate this is probably quite a challenge to implement. A short term solution may be to add a disclaimer in the docs to make consumers aware of this limitation, something I'd be more than happy to pick up with

## Screenshots

See the provided [CodeSandbox][CodeSandbox] link

## System information

N/A

## Additional context

[CodeSandbox]: https://codesandbox.io/s/stitches-repro-291-utils-in-utils-srdqb?file=/stitches.config.ts:1744-1760

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.

**Comment by joe-bell** [comment]
It has indeed been resolved in beta, thank you 🙏 
https://codesandbox.io/s/stitches-ci-cra-utils-in-utils-73u7e
