### ISSUE TITLE
Vendor prefixes rendering with extra "-" prefix

### ISSUE THREAD

**Issue by josephkmh** [modulz/stitches#295]
# Bug report

## Describe the bug

I was trying to add a `-webkit-text-stroke` property and noticed that the CSS output has an extra `-` before the property name. To me it looks like stitches is treating this property like a CSS variable declaration?

## To Reproduce

Here is a codesandbox:
https://codesandbox.io/s/cool-platform-bh4q7?file=/src/App.js

1. Add a vendor prefixed property to a stitches `styled()` declaration (e.g. `-webkit-text-stroke`)
2. View the CSS output in the browser (e.g. `--webkit-text-stroke`)

## Expected behavior

For the correct vendor prefix property to be rendered in the browser.

## Screenshots

![image](https://user-images.githubusercontent.com/7550957/97104041-d8114e00-16b0-11eb-9eb3-d0a2cbaa63ac.png)

## System information

- OS: Ubuntu
- Browser: Chrome
- Version of Next.js: 9.5.5
- Version of Node.js: v12.16.1

**Comment by peduarte** [comment]
This is fixed in the latest `canary` releases. 

Demo: https://codesandbox.io/s/thirsty-surf-fbl83
