### ISSUE TITLE
css.global not working in latest Canary release 

### ISSUE THREAD

**Issue by Razinsky** [modulz/stitches#298]
# Bug report

## Describe the bug

I just installed `v0.0.3-canary.4` to take advantage of the latest `StitchesProps` typings but now `css.global` doesn't seem to work anymore. Not sure though if it's an issue with `gatsby-theme-stitches` and `@stitches/react` not being in sync.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a new `gatsby` app and install/configure `gatsby-theme-stitches` plugin
2. Install `@stitches/react`
3. Use `css.global` to set body's background color
4. The CSS rule is not applied

## Expected behavior

`css.global` should work properly.

## System information

- OS: macOS
- Version of Stitches: [e.g. 0.0.3-canary.4]
- Version of `gatsby-theme-stitches`: [e.g. 0.0.2]

**Comment by LexSwed** [comment]
Hello @Razinsky 
As far as I understand, the API was changed in canary, from this discussion: https://github.com/modulz/stitches/discussions/285#discussioncomment-104956

**Comment by Razinsky** [comment]
Alright thanks @LexSwed I confirm that this new API works well 👍 

Thanks for the swift response!
