### ISSUE TITLE
min(), max(), clamp() don't seem to accept token values

### ISSUE THREAD

**Issue by Razinsky** [modulz/stitches#302]
# Bug report

## Describe the bug

There is no output when using a token value inside a `min()`, `max()` or `clamp()` functions.

## Expected behavior

Would be very powerful to be able to use our defined tokens inside these function i.e. `min($4, $8)`

Using version `0.0.3-canary.4`.

**Comment by peduarte** [comment]
This is in the works

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.
