### ISSUE TITLE
Typing style object before passing to styled

### ISSUE THREAD

**Issue by djgrant** [modulz/stitches#304]
I'd like to be able to share styles between `styled` instances. 

```ts
const buttonStyles = {
  backgroundColor: "$gray2",
} as const;

export const Button = styled('button', buttonStyles);
export const ButtonLink = styled(CustomLinkComponent, buttonStyles);
```

This compiles ok but I lose type hints when writing `buttonStyles`. I would like to be able to type `buttonStyles`. 

I have looked into `TComponentStylesObject`:

```ts
import { TComponentStylesObject } from "@stitches/react";

const buttonStyles: TComponentStylesObject<> = {};
```

However, this requires a `Config` type argument and I'm not sure it's possible to extract that – or, if it is, I've missed how.

**Comment by peduarte** [comment]
We're working on this. @hadihallak can you give us an update? Is this something you're covering in #294 ?

**Comment by hadihallak** [comment]
yep. `StitchesCSS` should cover this in #294

**Comment by djgrant** [comment]
I had a quick play with #294. I couldn't quite see how to configure `StitchesCSS<Breakpoints, Utils, Tokens, Strict>` with my own config (i.e. I don't know how to infer those type arguments from my config), but assuming that's possible, looks great!

**Comment by hadihallak** [comment]
you could infer the values of the config using typeof.
There is currently an issue with #294 that's causing types to not work in a built version of stitches but once that is fixed, your case should be covered as well

**Comment by djgrant** [comment]
Ah, ok. Something like this https://codesandbox.io/s/stitches-ci-cra-forked-y8zsm?file=/src/stitches.config.ts?

Originally I was attempting to constrain my config – `const config: IConfig = {}` – which meant `typeof config` just gave me back `IConfig`.

If I remove the type annotation (and add types annotations for the functions that lose type inference) then I get something workable: 

```ts
const config = {  
  breakpoints: {
    bp1: (rule: string) => `@media (min-width: 520px) { ${rule} }`,
    bp2: (rule: string) => `@media (min-width: 900px) { ${rule} }`
  }
};
export const { css, styled } = createStyled(config);
export Config = typeof config;
```

I am wondering it that's ideal though. Could createdStyled return `config` back to you so that you both get contextual typing when defining the config, and can still do `typeof config`? Forgive me if I'm missing a more obvious TS solution to this!

**Comment by hadihallak** [comment]
@djgrant yep this is similar to how I do it [(see here)](https://github.com/modulz/stitches/blob/66db3993e6d2156b05c851fcaaec455be30f4bd5/packages/core/tests/types.test.ts#L78)

> I am wondering it that's ideal though. Could createdStyled return config back to you so that you both get contextual typing when defining the config, and can still do typeof config? Forgive me if I'm missing a more obvious TS solution to this!

I actually have a PR #273 that kinda has the functionality you're after (see usage below)
 
> **Example usage:**
> 
> ```ts
> // with the __TYPE_HELPERS
> const {styled} = createStyled({
>   tokens: {
>     colors: {
>       $red100: 'tomato'
>     }
>   }
> })
> 
> type StitchesTypeHelpers = typeof styled.__TYPE_HELPERS
> type StitchesStyles = StitchesTypeHelpers['css']
> 
> const styleObj: StitchesStyles = {
>   backgroundColor: '$red100'
> }
> 
> const Button = styled.button({
>   ...styleObj
> })
> ```
> 
> Trying to access `styled.__TYPE_HELPERS` in js (not as a typescript type) will throw an error informing the user that this is just a type helper



Why I'm hesitant about this approach is that type related things would leak to the js runtime for no reason other than typing which is something we're trying to avoid.

Maybe we could alter it more twards what you suggested and make `createStyled` return type helpers

```
 const {styled, css, __TYPE_HELPERS__} = createStyled({})
```

Still not sure  for the reason mentioned above but this is definitely a possibility 

@peduarte what do you think?

**Comment by peduarte** [comment]
I'll have a think. Meanwhile cc @jonathantneal

**Comment by djgrant** [comment]
That sounds promising! What about just doing this?

```ts
const {styled, css, config } = createStyled({})
type Config = typeof config;
```

That'd perhaps eliminiate the concern of leaking TS concerns into the runtime.

**Comment by peduarte** [comment]
You can do this with `StitchesProps` as of `0.1.0-canary.0` https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta
