### ISSUE TITLE
`css` not working with ionic components

### ISSUE THREAD

**Issue by binchik** [modulz/stitches#310]
# Bug report

## Describe the bug

We're using stitches extensively in our web app and now want to use it in our mobile ionic app. However the `css` function result when passed to ionic components `className` prop throws `TypeError: newClassProps.split is not a function` error.

## To Reproduce

1. Setup a standard Ionic with React project -> https://ionicframework.com/docs/intro/cli
2. Setup Stitches
3. Create a stitched ionic component with `css`:

```
<IonHeader
    className={css('ion-no-border', className)}
    {...restProps}>
      <IonToolbar>
        <IonTitle>{title}</IonTitle>
      </IonToolbar>
  </IonHeader>
```

## Expected behavior

Should not throw an error.

## System information

OS: macOS
Browser: Chrome
Version of Node.js: 12.8.x

## Additional context

These are related:
https://github.com/modulz/stitches/issues/191
https://github.com/modulz/stitches/issues/229
https://github.com/modulz/stitches/pull/235

**Comment by peduarte** [comment]
Which version of stitches are you using? This should be fixed in `0.0.3-canary-4`

**Comment by binchik** [comment]
I'm on `0.0.3-canary.4`. But it doesn't work :(

**Comment by peduarte** [comment]
@binchik are you using `@stitches/core` or `@stitches/react`?

**Comment by binchik** [comment]
@peduarte `@stitches/react`

Reproduction here:
https://codesandbox.io/s/stitches-ionic-css-bug-8mwz4
