### ISSUE TITLE
Before and after pseudo elements do not work

### ISSUE THREAD

**Issue by raunofreiberg** [modulz/stitches#313]
# Bug report

## Describe the bug

Pseudo-elements (`::after` and `::before`) don't seem to appear.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to the [CodeSandbox](https://codesandbox.io/s/sharp-kilby-o5luh?file=/src/App.tsx:314-337).
2. Inspect the rendered DOM.
3. `after` or `before` elements aren't visible.

## Expected behavior

Pseudo-elements (`::after` and `::before`) appear.

## System information

- OS: macOS Mojave 10.14.6
- Browser: Google Chrome Version 86.0.4240.198 (Official Build) (x86_64)
- Version of Stitches: 0.0.3-canary.4
- Version of Node.js: N/A

**Comment by peduarte** [comment]
Hmm interesting. Looks like some encoding issue. Thanks for raising. 

_For now,_ you can workaround it by wrapping the inner `content` in single quote, or back ticks. Any of these should do the trick:
```
content: "'After'"
content: "`After`"
content: `"After"`
```

Thanks!

**Comment by peduarte** [comment]
For the new version of Stitches, we'll see if we can do this automatically.

But just for reference, this type of issues also happen in styled components when using the object syntax
https://codesandbox.io/s/fancy-pond-bgebv?file=/src/App.js

**Comment by peduarte** [comment]
Turns out thats just how it should work. Wrapping in extra quotes. 😄
