### ISSUE TITLE
Ideas to expose tokens as props

### ISSUE THREAD

**Issue by kevinwolfdev** [modulz/stitches#314]
First of all, thanks to all the maintainers for this awesome library, I am starting a new project and decided to create my Design System with Stitches, mostly because of its developer experience and strong TypeScript support.

## Is your feature request related to a problem? Please describe.

Given the following theme:

```tsx
const theme = {
  fontSizes: {
    $3xl: "3rem",
    $2xl: "2.25rem",
    $xl: "1.5rem",
    $lg: "1.25rem",
    $md: "1rem",
    $sm: "0.875rem"
  },
  fontWeights: {
    $light: '300',
    $regular: '400',
    $medium: '500',
    $semibold: '600',
    $bold: '700',
  },
  letterSpacings: {
    $3xl: '-0.066875rem',
    $2xl: '-0.049375rem',
    $xl: '-0.029375rem',
    $lg: '-0.020625rem;',
    $md: '-0.01125rem',
    $sm: '-0.005625rem',
  },
  lineHeights: {
    $heading: '1.3',
    $body: '1.75',
  },
};
```

If I want to generate a `fontSize` variant that maps to each token in `theme.fontSizes`, I would need to do the following:

```tsx
const VerboseText = styled("p", {
  variants: {
    fontSize: {
      $3xl: { fontSize: "$3xl" },
      $2xl: { fontSize: "$xl" },
      $xl: { fontSize: "$xl" },
      $lg: { fontSize: "$lg" },
      $md: { fontSize: "$md" },
      $sm: { fontSize: "$sm" }
    }
  }
});
```

Now, let's say I want to also create variants for `fontWeight`, `letterSpacing` and `lineHeight`, I would need to make my variants bigger:

```tsx
const VerboseText = styled("p", {
  variants: {
    fontSize: {
      $3xl: { fontSize: "$3xl" },
      $2xl: { fontSize: "$xl" },
      $xl: { fontSize: "$xl" },
      $lg: { fontSize: "$lg" },
      $md: { fontSize: "$md" },
      $sm: { fontSize: "$sm" }
    },
    fontWeight: {
      $light: { fontWeight: "$light" },
      $regular: { fontWeight: "$regular" },
      $medium: { fontWeight: "$medium" },
      $semibold: { fontWeight: "$semibold" },
      $bold: { fontWeight: "$bold" }
    },
    letterSpacing: {
      $3xl: { letterSpacing: "$3xl" },
      $2xl: { letterSpacing: "$xl" },
      $xl: { letterSpacing: "$xl" },
      $lg: { letterSpacing: "$lg" },
      $md: { letterSpacing: "$md" },
      $sm: { letterSpacing: "$sm" }
    },
    lineHeight: {
      $heading: { lineHeight: "$heading" },
      $body: { lineHeight: "$body" }
    }
  }
});
```

### Proposal 1: Dynamic variants

Inspired by the utils API, I think variants could receive a function where the first parameter is a token value and returns a CSS object:

```tsx
const DynamicVariantText = styled("p", {
  fontSize: (value: keyof typeof theme["fontSizes"] | (string & {})) => ({
    fontSize: value
  }),
  fontWeight: (value: keyof typeof theme["fontWeights"] | (string & {})) => ({
    fontWeight: value
  }),
  letterSpacing: (
    value: keyof typeof theme["letterSpacings"] | (string & {})
  ) => ({
    letterSpacing: value
  }),
  lineHeight: (value: keyof typeof theme["lineHeights"] | (string & {})) => ({
    lineHeight: value
  })
});
```

### Proposal 2: Map utils to props

But, what if instead of rewriting a custom utility I added to the theme, I could just re-expose it? (Disclaimer, I don't know if other CSS rules are core utilities under the hood):

```tsx
const MappedUtilsText = styled("p", {
  mappedUtils: ["fontSize", "fontWeight", "letterSpacing", "lineHeight"]
});

const MappedUtilsBox = styled("div", {
  mappedUtils: ["margin", "marginTop", "marginLeft", "marginBottom", "marginRight", "marginX", "marginY"]
});
```

## Describe alternatives you've considered
Right now, the way I am achieving this is by reducing the tokens I want and creating a variant for each one. And I know, it looks hacky:

```tsx
const HackyText = styled("p", {
  variants: {
    fontSize: Object.entries(theme.fontSizes).reduce(
      (acc, [token, value]) => ({
        ...acc,
        [token]: { fontSize: value }
      }),
      {}
    ) as Record<keyof typeof theme["fontSizes"], any>,
    fontWeight: Object.entries(theme.fontWeights).reduce(
      (acc, [token, value]) => ({
        ...acc,
        [token]: { fontWeight: value }
      }),
      {}
    ) as Record<keyof typeof theme["fontWeights"], any>,
    letterSpacing: Object.entries(theme.letterSpacings).reduce(
      (acc, [token, value]) => ({
        ...acc,
        [token]: { letterSpacing: value }
      }),
      {}
    ) as Record<keyof typeof theme["letterSpacings"], any>,
    lineHeight: Object.entries(theme.lineHeights).reduce(
      (acc, [token, value]) => ({
        ...acc,
        [token]: { lineHeight: value }
      }),
      {}
    ) as Record<keyof typeof theme["lineHeights"], any>
  }
});
```

## Additional context
 I created a [CodeSandBox](https://codesandbox.io/s/flamboyant-swartz-p87m1?file=/src/App.tsx) for illustration purposes.

**Comment by peduarte** [comment]
@kevinwolfdev hey hey 👋 

Thanks for the kind words, we really appreciate it. 

What you're proposing is something we've spent a lot of time discussing whether we should support or not. We've come to the conclusion to keep the library as small, performant and simple as possible (in terms of API layer).

After chatting to a lot of design system maintainers (including our own team) we agreed that keeping the code as clear as possible is actually a _good thing_. What I mean by that is that repetition is actually a good thing! It means that developers of all levels are able to help make changes, etc. 

So we try to keep things verbose, just like your example here:
```jsx
const VerboseText = styled("p", {
  variants: {
    fontSize: {
      $3xl: { fontSize: "$3xl" },
      $2xl: { fontSize: "$xl" },
      $xl: { fontSize: "$xl" },
      $lg: { fontSize: "$lg" },
      $md: { fontSize: "$md" },
      $sm: { fontSize: "$sm" }
    }
  }
});
```

However, we also understand some developers prefer to abstract things, and that way we'd recommend doing it, is also exactly what you've showed with your `reduce`. haha

I think this type of abstractions should happen consumer-side. So it's up to you how you want to do it. 

One thing that we're improving a lot in the new version of stitches is the Typescript helpers. We'll be exposing a bunch of heplers to help you access tokens, etc. 

But yeah, for now, while the library is still quite young, we'll try to stick with our premise. 

This request is, however, noted, and as the library matures we'll assess the demand. Our goal is to listen to our consumers and provide what they need to build the best design systems they can 😄

**Comment by kevinwolfdev** [comment]
Thanks for your response, @peduarte. I agree with keeping the library small, concise, and performant. Thanks for the awesome work!

**Comment by Lukin** [comment]
Thanks for your hack, @elkevinwolf. I wrote a very simple strongly typed function for myself. Perhaps it will be useful to someone.

```ts
import type { Properties } from '@stitches/core/types/css-types';

// import type { StitchesCss } from '@stitches/react';
// const stitches = createCss(...);
// export type CSS = StitchesCss<typeof stitches>;
import type { CSS } from 'path-to/stitches.config';
import { theme } from 'path-to/stitches.config';

export const variant = <T extends keyof typeof theme>(
  property: keyof Properties,
  token: T
): Record<keyof typeof theme[T], CSS> =>
  Object.entries(theme[token]).reduce(
    (previousValue, [key, value]) => ({
      ...previousValue,

      [key]: {
        [property]: value,
      },
    }),
    {} as Record<keyof typeof theme[T], CSS>
  );
```

```ts
import { styled } from 'path-to/stitches.config';
import { variant } from 'path-to/variant';

const VerboseText = styled('p', {
  variants: {
    size: variant('fontSize', 'fontSizes'),
  }
});
```

**Comment by nayaabkhan** [comment]
Some APIs have changed since the super helpful snippet left by @lukin above. In case someone like me stumbles upon it.

```ts
/**
 * Export CSS type from stitches.config.ts
 */

import { createStitches } from '@stitches/react'
import type * as Stitches from '@stitches/react'

export const { styled, theme, config } = createStitches({...})

export type CSS = Stitches.CSS<typeof config>
```

```ts
/**
 * Create a function with a clear API
 */

import { theme } from '../stitches.config'

import type { CSS, config as stitchesConfig } from '@stitches'
import type * as Stitches from '@stitches/react'

export const tokenVariants = <T extends keyof typeof theme>(config: {
  token: T
  css: (value: Stitches.ScaleValue<T, typeof stitchesConfig>) => CSS
}): Record<keyof typeof theme[T], CSS> =>
  Object.entries(theme[config.token]).reduce(
    (previousValue, [key, value]) => ({
      ...previousValue,

      [key]: config.css(value),
    }),
    {} as Record<keyof typeof theme[T], CSS>
  )
```

Usage remains the same as before—only the implementation changes to account for changes to Stitches API.

**Comment by nayaabkhan** [comment]
Also, I'd volunteer to add this to the TypeScript docs considering this should be a user concern rather than a library concern.
I would be glad to submit a PR once given a go.
