### ISSUE TITLE
NPM 7 peer-deps

### ISSUE THREAD

**Issue by DaveLo** [modulz/stitches#325]
# Bug report

## Describe the bug

If you try and install stitches/react while using [NPM v7](https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/) it crashes because of bad peer deps.

```shell
ui git:(main) ✗ npm i @stitches/react@v0.0.3-canary.4
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @southtree/ui@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.13.1" from @stitches/react@0.0.3-canary.4
npm ERR! node_modules/@stitches/react
npm ERR!   @stitches/react@"v0.0.3-canary.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/**/.npm/eresolve-report.txt for a full report.
```

You can work around the error using a flag `--legacy-peer-deps` so it isn't a total blocker, but definitely an issue.

## To Reproduce

1. use npm 7 `npm i -g npm@7` (or use node 15)
2. install package
3. see error

## Expected behavior

package installs correctly 

## System information

- OS: macOS Catalina
- Browser: n/a
- Version of Stitches: 0.0.2,0.0.3-canary.4
- Version of Node.js: 14.15

**Comment by peduarte** [comment]
Fixed in beta canary!
