### ISSUE TITLE
Stitches Showcase

### ISSUE THREAD

**Issue by apostolos** [modulz/stitches#326]
I thought it would be cool to have a place to showcase websites/apps/libs that are using Stitches.

Please include a name, link to your website, a screenshot, and even link to the source code if applicable.

**Comment by apostolos** [comment]
# LWJGL

Website: https://www.lwjgl.org/
Source: https://github.com/LWJGL/lwjgl3-www

![lwjgl-screenshot](https://user-images.githubusercontent.com/41679/103104624-09ff4c00-4631-11eb-9724-b7821566aa19.png)

**Comment by peduarte** [comment]
That's a great initiative 😄

**Comment by peduarte** [comment]
I'll close this, but have a note to introduce it once we have more users :)
