### ISSUE TITLE
keyframes doesn't support a comma separated key

### ISSUE THREAD

**Issue by jeiea** [modulz/stitches#327]
# Bug report

## Describe the bug

It seems `css.keyframes` doesn't support comma separated keys like `50%, 100% {}`.

I don't know whether it is intentionally unsupported, so file this issue anyway.

## To Reproduce

[codesandbox](https://codesandbox.io/s/sweet-voice-410co?file=/src/App.js)

## Expected behavior

Two css spinners should be looked same.

## System information

- OS: Windows 10
- Browser: Chrome 87
- Version of Stitches: 0.0.3-canary.4

**Comment by peduarte** [comment]
That's right. This feature will be supported in the new 0.1 release. /cc @jonathantneal

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.

**Comment by jeiea** [comment]
I checked the codesandbox example has no problem with 0.1.0. Nice work!
