### ISSUE TITLE
Alias tokens

### ISSUE THREAD

**Issue by hennessyevan** [modulz/stitches#332]
**Describe the solution you'd like**
It's useful to be able to alias tokens.

i.e.
```ts
const {styled} = createStyled({
  tokens: {
    colors: {
      $blue: 'hsl(214, 18%, 43%)',
      $primary: '$blue'
    }
  }
})
```

**Describe alternatives you've considered**
I've considered pulling my token objects like `color` out of the styled declaration.

```ts
const colors = {
  $blue: 'hsl(214, 18%, 43%)'
}

const {styled} = createStyled({
  tokens: {
    colors: {
      ...colors,
      $primary: colors['$blue']
    }
  }
})
```

**Comment by peduarte** [comment]
We've spec'ed this for the new release of Stitches. Nice to see you suggesting the same API. 🎉

I'll keep this open and update once its released.

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.
