### ISSUE TITLE
Extend variants while composing components

### ISSUE THREAD

**Issue by schonert** [modulz/stitches#333]
**Is your feature request related to a problem? Please describe.**
Creating a base component library with the goal of being easily customisable and extendable. In this case i'd like the ability to extend the parent components variants rather then overwrite them.

**Describe the solution you'd like**
The component library exports a Button component handling size, type, disabled, icons etc. By importing and using this Button to compose your own button with custom styling - variants are not overwritten. 

In the example below the entire _primary_ and _link_ types are overwritten in **FancyButton**
```tsx
const StyledButton = styled("button", {
  variants: {
    type: {
      primary: {
        backgroundColor: "$accent",
        color: "#fff",
      },
      link: {
        backgroundColor: "transparent",
        color: "$accent",
      },
    },
  },
});

const FancyButton = styled(StyledButton, {
  variants: {
    type: {
      primary: {
        backgroundColor: "pink",
      },
    },
  },
});

export const Button = ({ type = "primary", ...rest }: ButtonProps) => (
  <FancyButton type={type} {...rest} />
);
```

**Comment by peduarte** [comment]
@schonert thanks for this 💯 Something we've talked about. Will see if we can fit that in the next beta release. 

/cc @jonathantneal

**Comment by peduarte** [comment]
@schonert This has been implemented in beta.

**Comment by LexSwed** [comment]
omg this next release is nuts 🤯

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.
