### ISSUE TITLE
boxShadow doesn't handle multiple shorthand values

### ISSUE THREAD

**Issue by deebov** [modulz/stitches#334]
First of all, thanks for the hard work guys! This library is what the Design System and React community have been needing for. I love it!

# Bug report

## Describe the bug

I would like to use shadow token in combination with others. Probably something like this:
```js
boxShadow: '$sm, $outilne'
```
or
```js
boxShadow: '$sm, inset 0 0 0 1px #000'
```

## To Reproduce

Just add boxShadow to a component like above👆

## Expected behavior

It should map multiple shadow values 

## System information

- Version of Stitches: 0.0.3-canary.4

**Comment by deebov** [comment]
I found a workaround using utils. Here's what I did:

```ts
  // RegExp from styled-system
  const SHADOWS_REG = /,(?![^\(]*\))/;

  multiShadow: (value: keyof typeof tokens["shadows"] | (string & {})) => {
    const boxShadow = value
      .split(SHADOWS_REG)
      .map((shadow) => {
        shadow = shadow.trim();

        return tokens.shadows[shadow]
          ? `var(--shadows-${shadow.replace("$", "")})`
          : shadow;
      })
      .join(", ");

    return { boxShadow };
  }
```

**Comment by deebov** [comment]
Also noticed that color tokens don't get mapped within shadow tokens:
![image](https://user-images.githubusercontent.com/28673719/107000494-cb20f200-67a9-11eb-8b36-06216c9cf87b.png)

**Comment by peduarte** [comment]
We've published a pre-release of Stitches beta 🚀

**Core**:
```bash
npm install @stitches/core@0.1.0-canary.0
```

**React**:
```bash
npm install @stitches/react@0.1.0-canary.0
```

This issue should have been resolved in the beta version. We'd appreciate it if you could verify it. 

⚠️ Please refer to this [migration guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta) as there are some breaking changes.

**Comment by deebov** [comment]
Trying to test it out. But as our codebase that uses stitches is not small. so I haven't got the beta working yet. Currently refactoring the old code.

**Comment by peduarte** [comment]
@deebov bare in mind that box shadow now maps the the `shadows` scale by default.

So, doing this:
```
boxShadow: '$primary'
```
will map to: `theme.shadows.primary`

If you want to have a hard coded shadow config (spread/offset/blur) but use a `color` from your theme, you need to be explicit:
```
boxShadow: '0 3px 10px $colors$red500'
```

**Comment by peduarte** [comment]
Let me know if you have any issues with the beta canary!
