### ISSUE TITLE
same class selector applied many times to pseudo selectors

### ISSUE THREAD

**Issue by deebov** [modulz/stitches#335]
# Bug report

## Describe the bug

Pseudo selectors like hover and focus work the way that they have many same class selectors applied to them which makes it hard to override. As you can see here `:focus` has 4 class selectors and `:hover` has 2 class selectors. Usually to override them within other selectors I'd do `&&[aria-invalid=true]` but it's not gonna work since they have more class selectors.

![image](https://user-images.githubusercontent.com/28673719/107025232-f0722800-67ca-11eb-94d6-13d45608ff7e.png)

## To Reproduce

Inspect the pseudo-selectors of the link here:

https://codesandbox.io/s/gallant-payne-hh7tw?file=/src/App.tsx

## Expected behavior

Pseudo selectors should have less class selectors OR what would be the alternative to override pseudo styles??

## System information

- Version of Stitches: 0.0.3-canary.4

**Comment by peduarte** [comment]
This is on purpose to avoid specificity issues. It's weird, I know. But this is gone in the beta version.
