### ISSUE TITLE
Group decorators

### ISSUE THREAD

**Issue by CodingDive** [modulz/stitches#35]
One of the things that I found really interesting about `classy-ui` was the ability to define [group decorators](https://classy-ui.io/api/group-decorators). Are there any plans to implement a similar API for stitches?

My use case is that I want to change the visibility of an element based upon if a parent element is hovered or not.

**Comment by peduarte** [comment]
hi @CodingDive thanks for this.

Currently, group decorators this is out of the scope of this project, but we're working on supporting the `&` like SC and others, which will allow you to do:

```
const Button = styled.button({})

const Icon = styled.span({
  opacity: 0.5,
  [`${Button}:hover &`]: {
    opacity: 1
  }
})
```

then

```
<Button><Icon>i</Icon> text</Button>
```

**Comment by peduarte** [comment]
Closing but feel free to raise any questions! Cheers
