### ISSUE TITLE
Integrating stitches in a lib, with the possibility of this lib being used in an app using stitches.

### ISSUE THREAD

**Issue by dbismut** [modulz/stitches#357]
Hi - First of all let me just say once again that I'm really fond of `stitches`, really feels like a no-compromise styling lib for React.

### The context
We're building a react GUI which main API will be a hook. People will use the hook and a GUI pane will be automatically spawn. The GUI should be fully theme-able. We've been switching from Styled Components to `stitches` because we faced a wall, namely Styled Components recommending to [add `styled-components` as a peer dependency](https://styled-components.com/docs/faqs#marking-styledcomponents-as-external-in-your-package-dependencies).

This resulted in poor DX, we want people to just add our lib and not bother with SC. So `stitched` felt like a great candidate for replacement and so far so good, we're super happy with our move!

### The problem
The lib isn't out and stitches is not widespread yet (I'm sure it will) so the problem didn't surface yet, but I've just tried integrating our lib into a minimal app consuming stitches `createCss` default export and it breaks the lib styling (doesn't trigger errors, but the theme that our lib should create doesn't inject any css vars).

Here is a sandbox. Try uncommenting line 6 and our gui pane lib will disappear.
https://codesandbox.io/s/leva-minimal-forked-4qkm4

So it looks like the `createCss` that we call in our lib doesn't have any effect.

Furthermore, there is a chance that even if that works, our variables would conflict with the ones that a user could create for its app.

### Possible solutions

I'm not sure how you can allow several `createCss` calls in the app. But we can't ask people to use our own `styled/css` export from our theme. The GUI is supposed to be a light, disposable element, and we want it to be dropped in or out easily without hassle.

- Ideally, we could scope the lib to a node. This may be a bit harder than it looks, since the node might not exist until it's actually rendered by React.
- Otherwise, namespacing the css vars would limit conflicting issues.

### Libs used
- @stitches/react 0.1.0-canary-1
- react + react-do 17.0.0 

Thanks!

**Comment by AndrewPrifer** [comment]
Hi, Andrew here, I'm also involved with the aforementioned React GUI.

I don't think we need to worry about namespacing anything, because ideally, we'll be using shadow dom. What we do need is a way to

1. scope the generated stitches variables / styles to the root of our shadow dom
2. create a localized stitches cache, if there is any (not quite sure about the stitches internals)

I f we can do these two things, I think we're good. This would also make Stitches pretty much the only CSS in JS solution that can be used for isolated drop-in web components without interfering with the host app, both in terms of the size of the library, and in terms of not breaking host dependencies.

**Comment by peduarte** [comment]
Thanks for this. I'll need a bit of time to think and chat with @jonathantneal, but I see the issue. 

At a glance there are two things going on:
- Stitches will always add the style to `<style id="stitches">` tag. So, when you call `createCss` a second time, it is overriding the first one
- The naming convention of the custom properties are `--scaleName-tokenName`, so even if we update stitches to have a dedicated `style` for each instance, there would still be a potential clash of custom properties. Stitches offers a `prefix` configuration, but that only applies to the generated classnames. Perhaps, we could consider applying it to the generated custom property name too. 

Will need more thinking, still.

**Comment by AndrewPrifer** [comment]
@peduarte to reiterate, the generated styles don't need name-spacing--for our purposes at least--because the appropriate solution here is to just use shadow-dom, which would stop outside styles, including custom properties from leaking in.

**Comment by peduarte** [comment]
Gotcha. In your specific case, since you'll be using shadow dom, the prefixed custom properties are irrelevant.

> The only thing we need then is to be able to place any generated styles inside our shadow dom

Do you have anything in mind?

**Comment by AndrewPrifer** [comment]
To remain React-agnostic, I imagine createCss could allow a custom html element to be passed. I'm saying html element and not selector for a reason, selectors require extra logic for shadow dom to be supported.

**Comment by peduarte** [comment]
@AndrewPrifer I was hoping your answer would be something along those lines 🙂 

At the time of creating the stitches instance, via `createCss` would you be able to do query from the DOM?

```
const target = document.querySelectorAll('')

createCss({
  styleNode: target
})
```

Is this what you were imagining? If not, can you provide some snippets, so its clear for me?

**Comment by AndrewPrifer** [comment]
@peduarte yes, very much literally what I was imagining! :D

**Comment by dbismut** [comment]
@peduarte We've had an internal discussion with @AndrewPrifer and as much as shadow-root would feel like an exciting possibility, in our specific use case, namespacing css vars would be a drop-in fix for us.

So I guess something like the below would work for us.

```js
const { styled, css } = createCss(tokens, 'myNameSpace')
```

In that case case I imagine `styled` and `css` could transpile the namespace on top of the space so that `margin: $1` becomes `margin: var(--myNameSpace-colors-$1)`. 

Worst case scenario, we would handle the namespace ourselves, but our issue is that at the moment calling `createCss` twice makes the second call squash all variables...

**Comment by peduarte** [comment]
@dbismut Ok. I'll have a chat with @jonathantneal and see what we can do.

**Comment by peduarte** [comment]
Related: https://github.com/modulz/stitches/issues/130

**Comment by dylanklohr** [comment]
> Thanks for this. I'll need a bit of time to think and chat with @jonathantneal, but I see the issue.
> 
> At a glance there are two things going on:
> 
>     * Stitches will always add the style to `<style id="stitches">` tag. So, when you call `createCss` a second time, it is overriding the first one
> 
>     * The naming convention of the custom properties are `--scaleName-tokenName`, so even if we update stitches to have a dedicated `style` for each instance, there would still be a potential clash of custom properties. Stitches offers a `prefix` configuration, but that only applies to the generated classnames. Perhaps, we could consider applying it to the generated custom property name too.
> 
> 
> Will need more thinking, still.

+1 for being able to provide either a unique-hash for css custom properties generated with `createCss`, or for allowing the `prefix` key already accepted by `createCss` to also prefix created custom properties.

When introducing stitches to projects that may have any number of other styling solutions in place (at least until they're replaced with stitches 😉) being able to reduce friction in naming collisions is **hugely** valuable. _Fantastic_ job so far 😄 🙏

**Comment by dylanklohr** [comment]
With this issue being closed, is there any intent to provide name-spacing of tokens to avoid conflicts in existing apps that may have existing css tokens?

**Comment by peduarte** [comment]
@dylanklohr not at the moment, this was about specifying an injection target

Do you think it's useful to namespace variables? Mind creating an issue with your vision?

Thanks!

**Comment by dbismut** [comment]
We're in the same position of needing namespacing @peduarte even if canary 15 does help a big deal and solves a major issue as now our lib can coexist with an app, both using stitches.

We need to inject at head level as our panel can spawn either portalled (in that case the inject method + shadowDOM would work perfectly I guess) but also in the user app tree, considering there could be several panels in the user app.

With that in mind, there might be a way to use the `styled` function returned by our global `createCss` function to generate the css classes and inject a new one when the panel mounts inside a ref but it feels a bit hacky?

But again, thanks for the help and follow up this is fantastic.

**Comment by peduarte** [comment]
Makes sense. Let's create a proposal for name spacing or hashing variables. /cc @jonathantneal

**Comment by dylanklohr** [comment]
@peduarte or @jonathantneal, what is the likelihood of being able to enable multiple `createCss` invocations to be compatible without leaning on the shadow DOM for encapsulation?

In monorepo react component libraries, having every `createCss` invocation overwrite any existing `style` elements with a `stitches` id make reliably extracting a single stitches Config into a library package to be referenced throughout the aforementioned react component packages **incredibly** cumbersome, despite the stitches api theoretically lending itself really well to this  😕.

**Comment by peduarte** [comment]
@dylanklohr let's talk about this and I'm sure we can find a solution. I think the best way to go about it is:
- Open up a discussion (since this is not an issue, more of an enhancement/feature that needs some spec'ing)
- Provide an example use case, if we can create a demo repo for this highlighting the current difficulties it would be great

Let' get it! Thanks 🙏

**Comment by dylanklohr** [comment]
@peduarte , ✅ https://github.com/modulz/stitches/discussions/534
