### ISSUE TITLE
CSS does not work in Next.js production build.

### ISSUE THREAD

**Issue by olaven** [modulz/stitches#365]
# Bug report

Hi 👋 Thank you for making this. 
I'm overall very happy to use stitches. 

## Describe the bug
When building a Next.js site for production.

## To Reproduce
Reproduction available [here](https://github.com/olaven/error-reproductions/tree/master/stitches-not-working-with-nextjs)

1. Build the application with `yarn && yarn build`
2. Start the application wiht `yarn start`
3. Notice how the orange background color does not get applied to the "Hello"-message

## Expected behavior
The "Hello"-text should get an orange background color. 
This does happen if the application is running in development mode, with `yarn dev`. 

## System information

- OS: macOS
- Browser: Reproduced in Firefox, Chrome and Safari.
- Version of Stitches: 0.0.2
- Version of Node.js: e.g. 15.5.1

**Comment by peduarte** [comment]
@olaven hey, thanks for raising this. 

Nextjs server-side renders your page, so you need to load the initial styles via SSR as well.
Here's a guide https://stitches.dev/blog/using-nextjs-with-stitches

PS: you're using Stitches alpha `0.0.2` and we've just released a beta canary, it's still in testing but overall its much more stable than the alpha version. You can see the migration [guide here](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta)

**Comment by olaven** [comment]
Thank you for the swift response! 
Following the guide, implementing `_document.tsx` worked like a charm 😄 

In my case, ui components are in a separate monorepo-package. To implement `_document.tsx` I had to export `css` from the ui-package and import it in my next-project. This works, but feels kind of hacky. 

Are there any known solutions avoiding exposing `css`?

**Comment by peduarte** [comment]
>This works, but feels kind of hacky.

That's not hacky at all. Thats how we do it in our Design System as well. It's a great, because the source of truth of everything CSS related is the DS, in your case, `ui-package` so by re-exporting `css` and `styled`, etc, from there, it means that all consumers will be using the right instance of Stitches. This means they will have access to tokens, themes, etc.

**Comment by olaven** [comment]
@peduarte That makes sense 😄 
Thank you for letting me learn something new today 😄
