### ISSUE TITLE
type-safe way of using utils

### ISSUE THREAD

**Issue by deebov** [modulz/stitches#367]
**Is your feature request related to a problem? Please describe.**

We have quite a few utils that are in a separate file. But since the beta syntax change using the util's value like this  `value: keyof typeof theme["space"] | (string & {})` wouldn't be safe anymore. Let me explain.

We define token without `$` prefix. But we must use them with `$` prefix. So in the theme object we defined, the tokens are not prefixed. And we're saying that the value is `keyof typeof theme["space"]`. So when using that utility we cannot see/use the prefixed tokens. 

**Describe the solution you'd like**

Would be nice to have a `Utils` type so we can define utilities outside `createCss` and be able to prefixed tokens. 

```ts
const utils: Utils = {
   marginY: (config /* Config is aware of the tokens */) => (value: keyof typeof config.theme['space'] | string) => ({})
}
```

**Describe alternatives you've considered**

Tried to extract the "prefixed" theme object using `StitchesCss` but `StitchesCss` itself does not use prefixed tokens.

**Comment by peduarte** [comment]
@deebov yeah. There's a bit of work still to be done around utils to improve abstraction + types. 

I think eventually we'll add a type helper generic that will ensure tokens are prefixed.

For now, though, you can do this:
```
(value: number | `$${keyof typeof config.theme.space}`)
```

Thanks!

**Comment by peduarte** [comment]
Closing in favour of https://github.com/modulz/stitches/issues/383
