### ISSUE TITLE
[react/0.1.0-canary.3] Inconsistent behavior of defaultVariants when composing styled components 

### ISSUE THREAD

**Issue by nderscore** [modulz/stitches#380]
# Bug report

## Describe the bug

When composing a styled component with defaultVariants:

```javascript

const Foo = styled('div', {
  variants: {
    example: {
      a: { color: 'red' },
      b: { color: 'blue' }
    }
  },
  defaultVariants: {
    example: 'a'
  }
});

const ComposedFoo = styled(Foo, {
  backgroundColor: 'green'
});
```

Behavior of the inherited variant props is not always respected:

```jsx
// this should always render with variant `example=b` styles, but sometimes gets `example=a` styles
<ComposedFoo example="b" /> 
```

When the error occurs, the resulting `className`s includes both variants, but the default variant is applied with higher specificity.

## To Reproduce

See demo here: https://codesandbox.io/s/stitches-composed-variants-83fu8-83fu8?file=/src/App.js:965-1130

## Expected behavior

Variant from a prop should always over-ride default variant.

**Comment by peduarte** [comment]
Fixed in `react/0.1.0-canary.4`
