### ISSUE TITLE
[0.1.0-canary.x] TypeScript doesn't recognise "locally scoped tokens" inside conditions

### ISSUE THREAD

**Issue by joe-bell** [modulz/stitches#390]
# Bug report

## Describe the bug

I'm currently leveraging locally scoped tokens in my custom component; changing the value on specific conditions...

- **Good news**: CSS is outputting perfectly 🎉 
- **Bad news**: TypeScript doesn't seem to recognise the tokens and throws:
    ```tsx
    const Container = styled("div", {
      $$maxWidth: "300px",
      marginX: "auto",
      paddingX: "$3",
      maxWidth: "$$maxWidth",
      when: {
        bp1: {
          $$maxWidth: "585px",
          // Error: Object literal may only specify known properties, but '$$maxWidth' does not exist
          // in type 'InternalCSS<… . Did you mean to write 'maxWidth'?
        },
        bp2: {
          $$maxWidth: "865px",
        },
      },
    });
    ```

## To Reproduce

Visit https://codesandbox.io/s/stitches-ci-cra-locally-scoped-tokens-issue-n2t33?file=/src/App.tsx:488-508

## Expected behavior

TypeScript should recognise the locally scoped tokens inside `conditions`

## Screenshots

<img width="607" alt="Screenshot 2021-02-16 at 13 06 58" src="https://user-images.githubusercontent.com/7349341/108054842-dbfa1f00-7057-11eb-8f75-b9bce64c5293.png">

## System information

N/A

## Additional context

N/A

**Comment by jonathantneal** [comment]
resolved in #418
