### ISSUE TITLE
[Beta] internal stylesheet is shared across network requests in SSR

### ISSUE THREAD

**Issue by eddyw** [modulz/stitches#395]
# Bug report

## Describe the bug

Stitches beta provides a single method to get all rendered styles for SSR `getCssString`. The suggested way to use Stitches beta is to create a shared config file as follows:
```javascript
import createCss from '@stitches/react'

export const { css, styled, global, theme, keyframes, getCssString } = createCss({})
```
This works well in the browser. However, in a server environment (aka SSR), this config is shared across all network requests. Meaning that:
```
(Client 1) GET /
(Client 2) GET /profile
(Client 3) GET /private-gallery
(Client 4) GET /guest
```
All these requests will share the same internal stylesheet which means `getCssString` for the last request in this example (Client 4) will get all styles used in previous requests (including used in `/private-gallery`)

In frameworks such as Next.js where each page is its own server (if target is `serverless`), you don't get styles from all pages but if you have styles that depend on query strings or SSR page for logged in user, you're still sending styles that do not belong to the current request.

This is not desirable because you may, for instance, set a `backgroundImage` for a private gallery for a logged in user and you wouldn't want to send those styles to other users.

### Case 1

1. Go to https://codesandbox.io/s/frosty-raman-yyyi9
2. Use the browser view to navigate to https://yyyi9.sse.codesandbox.io/ (root/home)
3. Check the terminal or page source. Output includes not used styles because they belong to previous requests
4. Repeat from 1 to 3 a couple of times (Check terminal or page source again, each request adds more styles)

### Case 2

1. Go to https://codesandbox.io/s/frosty-raman-yyyi9
2. Use the browser view to navigate to https://yyyi9.sse.codesandbox.io/api/styles?color=red
3. Use the browser view to navigate to https://yyyi9.sse.codesandbox.io/api/styles?color=hotpink
4. Use the browser view to navigate to https://yyyi9.sse.codesandbox.io/api/styles?color=black
5. Use the browser view to navigate to https://yyyi9.sse.codesandbox.io/api/styles?color=yellow
6. Observe the output

Relevant files:
```
/pages/api/styles.ts (API request handler for `/api/styles`)
/pages/index.js (SSR example page)
/pages/_document.js (Styles injected in the document using `getCssString`)
/src/library/stitches.js (Stitches config file)
```

## Expected behavior

There should be a way to create an isolated config for each network request. In the API case, this could be solved with:
```javascript
import { default as createCss } from "@stitches/react";

export default function (req: NextApiRequest, res: NextApiResponse) {
  // Create for each request instead of sharing config with all
  const { css, getCssString } = createCss({ /* the config here */ })
  css({ color: req.query.color }).toString();

  res.send(getCssString());
}
```
However, this isn't possible using JSX since `styled` needs to be used from config.

## Proposal

An idea to solve the issue is to expose the internal `sheet` and provide the sheet using a context provider (pseudo-solution):
```javascript
function MySSRApp() {
    const sheet = useStitchesSheet() // Scoped and isolated
    
    return (
       <StitchesProvider value={sheet}>
            <Head>
                <style>{sheet.getCssString()}</style>
            </Head>
            <TheApp />
       </StitchesProvider>
    )
}
```
This way the internal `sheet` is generated and scoped to the `App` function (component) and not shared with other renders from other network requests while doing SSR.

I understand that beta aims to be simpler, so there could be a default `sheet` to be used if no provider is used to override the `sheet` which could be cleaner and useful for React Apps that do not do SSR.

```javascript
// Somewhere internal in `styled`
const sheet = useContext(StitchesProvider) ?? defaultSheet // Pseudo-solution
```

## System information

- OS: MacOS, Linux
- Version of Stitches: 0.1.0-canary.4

**Comment by jonathantneal** [comment]
We have a `reset` function that will clear styles, ideal for scoping when stitches should do one thing or another. This may not handle your use-case, because it would not be the same as running stitches concurrently in multiple places.

```js
const { reset } = createCss()
```

However, I am interested to know if concurrency is less the issue here, and if `reset` fully resolves the issue?

**Comment by eddyw** [comment]
@jonathantneal testing `reset` in Next.js with:
```javascript
const styles = getCssString().toString()
reset() // after getting styles
```
Only the first render has `styles`, next network requests have empty string 🤔

**Comment by jonathantneal** [comment]
Pardon an overly late response, but we can now re-use an inline or external sheet (_without needing to rewrite or modify it_) in the current version of Stitches.
