### ISSUE TITLE
TypeError in Variants with undefined values

### ISSUE THREAD

**Issue by jorenrui** [modulz/stitches#398]
# Bug report

A TypeError is shown when you give a styled component's variant an 'undefined' value.

### 1. Pass `undefined` to a styled component's variant that has no default variants.

Considering the sample styled component:

```jsx
const Chip = styled("span", {
  display: "inline-block",
  padding: "8px",
  borderWidth: "1px",
  borderStyle: "solid",

  variants: {
    color: {
      blue: {
        color: "blue",
        borderColor: "blue"
      }
    }
  }
});
```

This returns a TypeError of "Cannot read property 'color' of undefined".

```jsx
<Chip color={undefined}>Chip 3</Chip>
```

This is due to having no `defaultVariants` if you add one, the error goes away.

![image](https://user-images.githubusercontent.com/23741509/108090407-8a807d00-70b5-11eb-8d68-34644e8d358e.png)

### 2. TypeError in `css()`

Also I discovered another type error when using `css`:

![image](https://user-images.githubusercontent.com/23741509/108089312-6bcdb680-70b4-11eb-8b4a-403dd4c992d4.png)

I'm not sure about this cause I don't use `css()` that much, I'm basing this on [Core variant support part of the docs](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta#core-variant-support).

## To Reproduce

CodeSandbox: https://codesandbox.io/s/relaxed-dawn-wntq0?file=/src/App.tsx

## System information

- OS: macOs Catalina
- Version of Stitches: 0.1.0-canary.5
- Version of Node.js: v14.15.4

## Additional context

This bug suddenly came up when I updated from `0.1.0-canary.3` to `0.1.0-canary.5`.

In the alpha version, I added the default styles directly to the component then let the style overrides be done when a variant was chosen. Now that I've updated to beta, I can now use defaultVariants for that.

Although I'm not quite sure if this is a feature like when you add a variant, there should be a default value? Anyway, amma just wanna let you know about it. Also thank you for the great work! I like Stitches 😁

**Comment by peduarte** [comment]
Will be released in `0.1.0-canary.6`
