### ISSUE TITLE
TypeError when passing a style object with default variants or of type CSS

### ISSUE THREAD

**Issue by jorenrui** [modulz/stitches#405]
# Bug report

TypeError when passing a style object with default variants or of type CSS

### 1. When a style object has a `defaultVariants`, it shows a type error.

```diff
const smallChipStyles = {
  display: "inline-block",
  padding: "8px",
  borderWidth: "1px",
  borderStyle: "solid",

  variants: {
    color: {
      blue: {
        color: "blue",
        borderColor: "blue"
      }
    }
  },
  // Adding default variants to a style object
  // shows a type error.
  // Remove this then the error goes away.
+  defaultVariants: {
+    color: 'blue',
+  },
};
```

![image](https://user-images.githubusercontent.com/23741509/108181730-3c19bf80-7143-11eb-8317-dc30955abf6a.png)

### 2. Variants is lost when you use `CSS` for the style object's type

```diff
+ const bigChipStyles: CSS = {
  display: "inline-block",
  padding: "8px",
  borderWidth: "1px",
  borderStyle: "solid",

  variants: {
    color: {
      blue: {
        color: "blue",
        borderColor: "blue"
      }
    }
  },
  defaultVariants: {
    color: 'blue',
  },
};
```

![image](https://user-images.githubusercontent.com/23741509/108181958-7c793d80-7143-11eb-8306-b312022496c3.png)

![image](https://user-images.githubusercontent.com/23741509/108182019-88fd9600-7143-11eb-87c8-7dbdc24ebc13.png)

## To Reproduce

CodeSandbox: https://codesandbox.io/s/festive-bell-jn5de?file=/src/App.tsx

## System information

- OS: macOs
- Version of Stitches: 0.1.0-canary.6
- Version of Node.js: v14.15.4

## Additional context

My use-case for this was using Radix then using the styles of an existing component.

Example:

```js
export const StyledButton = styled('button', BUTTON_STYLES);

// Dialog.Trigger from Radix
export const StyledTrigger = styled(Dialog.Trigger, BUTTON_STYLES);
```

In this example, the Dialog's Trigger and the styled Button have the same styles.

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
