### ISSUE TITLE
TS: error spreading abstracted style onto `css` prop

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#407]
This happens on both `stitches/core` and `stitches/react`

Repro: https://codesandbox.io/s/stitches-ts-error-passing-abstracted-css-to-css-prop-4v34v?file=/src/App.tsx

**Comment by andyhqtran** [comment]
@peduarte this is also happening when spreading `...css` with existing css properties
https://codesandbox.io/s/autumn-monad-2fgqm?file=/src/App.tsx

**Comment by pepibumur** [comment]
I managed to workaround it by adding the following declaration file to the project:

```ts
import * as React from "react";

declare module "react" {
  // The css prop
  interface HTMLAttributes<T> extends DOMAttributes<T> {
    css?: any;
  }
  // The inline svg css prop
  interface SVGProps<T> extends SVGProps<SVGSVGElement> {
    css?: any;
  }
}
```
Note that this is a workaround. The `css?` attribute that we are declaring for `HTMLAttributes` should be the type of the CSS attribute. Does anyone know if I can import that from the stitches package?

**Comment by dsbrianwebster** [comment]
Another workaround that seems to work for us is to use a small function typed o create the local css before spreading the css from the props. For example...

```tsx
...

type SkeletonProps = StitchesVariants<typeof StyledSkeleton> & {
  ar?: AspectRatio;
  css?: CSS;
};

const arCss = (ar: AspectRatio): CSS => ({
  height: '0px',
  paddingBottom: parseAspectRatio(ar) * 100 + '%',
});

export const Skeleton: React.FC<SkeletonProps> = ({ variant, ar, css }) => {
  return (
    <StyledSkeleton
      variant={variant}
      css={{
        ...(ar && arCss(ar)),
        ...css,
      }}
    />
  );
};

```

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
