### ISSUE TITLE
[0.1.0-canary.x] defaultVariants creates selector that includes all default variant classes

### ISSUE THREAD

**Issue by nderscore** [modulz/stitches#413]
# Bug report

## Describe the bug

Last seen on: `@stitches/react@0.1.0-canary.7`

When using the `defaultVariants` feature, the generated `selector` always includes the default variant classnames. 

(example: `.baseClass.baseClass--variant1-value1.baseClass--variant2-value2`)

This selector is also used as the return value for `toString()`/`toPrimitive()`, which is used to support referencing the component when doing nested styles. Because the generated selector only targets the element when it has default variants, it breaks previous usages

## To Reproduce

```jsx
const Foo = styled('div', {
  defaultVariants: {
    x: 'a',
  },
  variants: {
    x: {
      a: { color: 'red' },
      b: { color: 'blue' }
    }
  }
});

const FooWrapper = styled('div', {
  [`& ${Foo}`]: { // <-- generates a selector that includes default variant classes instead of just base class
    color: 'green'
  }
});

// rendering Foo with variant "b" causes the selector to not work in this scenario:
const renderSomething = () => (
  <FooWrapper>
    <Foo x="b" />
  </FooWrapper>
);
```

## Expected behavior

The generated selector should not include the default variant classes, because it breaks referential nesting.

**Comment by peduarte** [comment]
Thank you for raising this <3

**Comment by nderscore** [comment]
This seems to be fixed in canary 12

**Comment by peduarte** [comment]
Was fixed here https://github.com/modulz/stitches/pull/428
