### ISSUE TITLE
TS: Error using `undefined` as a CSS value

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#422]
Repro: https://codesandbox.io/s/stitches-beta-css-error-when-using-undefined-9shxm?file=/src/App.tsx

```jsx
<Button css={{
  color: undefined // ❌ Error
}}/>
```

**Comment by jonathantneal** [comment]
Great catch. The `undefined` value no longer throws in canary 11. Fixed in https://github.com/modulz/stitches/commit/01780d33c8b8fab841e14b2474c75f9c5df66ccc#diff-ebddff3e820fd3c2c42105d178b6b48a6ff5326fc1089e60a489e9aa8d5d869eR229
