### ISSUE TITLE
[0.1.0-canary.7+] TS error when passing react-router's Link to "as" prop

### ISSUE THREAD

**Issue by apostolos** [modulz/stitches#427]
# Bug report

Getting `No overload matches this call.` typescript error when passing `react-router-dom@6.0.0`'s `Link` component to "as" prop.

This started happening since `0.1.0-canary.7` and still reproduces on `0.1.0-canary.11`

## To Reproduce

https://codesandbox.io/s/stitches-react-router-link-5hdol?file=/src/App.tsx

## Expected behavior

Link should be accepted as a valid "as" prop value

## Screenshots

![image](https://user-images.githubusercontent.com/41679/108567794-92d4f400-7311-11eb-9ad0-948554556a77.png)

**Comment by PhilGarb** [comment]
I am still facing this issue on 0.1.0-canary.21. Has someone found a fix for this yet?

**Comment by peduarte** [comment]
Not yet, but we'll be focusing on all typescript related issues soon

**Comment by Razinsky** [comment]
I get this same error for any components really. I'm on beta version `0.1.4`.

For example, this basic example will trigger the same issue:
```
const Heading = styled('span', {...});

const Page = () => (
  <Heading as="h1" />
)
```

Really annoying, it is completely stopping development for me. Please fix this 🙏

**Comment by peduarte** [comment]
Upgraded to P1

**Comment by sandgraham** [comment]
Is there another (type-safe) way to use stitches with react-router `Link`/`NavLink`? I suppose you could use `css` to apply styles directly to `Link` and wrap it in a new component to expose css and any variants. For the end-user the types should check out but you do need to manually sync the variants if there are any.

**Comment by philldev** [comment]
@apostolos  this solve the issue for me

```jsx 
import { Link as RLink } from "react-router-dom";
import { styled } from "../../stitches.config";

const Link = styled(RLink, {});

const Example = () => {
  return (
        <Button as={Link} to="/signup">
          Signup
        </Button>
  );
};
```

**Comment by jonathantneal** [comment]
This should be working in #659

```tsx
import * as Stitches from '@stitches/react'
import { createCss } from '@stitches/react'
import { Link } from 'react-router-dom'

const { styled } = createCss()

const StyledLink = styled('a', {
	lineHeight: '2rem',
	color: 'red',
})

export const expectation = () => {
	return (
		<StyledLink as={Link} to="/">
			Home
		</StyledLink>
	)
}
```

<img width="1440" alt="screenshot of the above code upon suggestions" src="https://user-images.githubusercontent.com/188426/126379818-3fa15ecc-58de-4890-99b8-be3f064ae2bb.png">
<img width="1300" alt="screenshot of the above code after suggestions" src="https://user-images.githubusercontent.com/188426/126379870-4060a835-6f62-4164-8af7-7c94a4f8e906.png">

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
