### ISSUE TITLE
events on styled components are typed as `any`

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#43]
In this example, `Button` is the return of `styled.button`

<img width="960" alt="CleanShot 2020-07-08 at 11 47 55@2x" src="https://user-images.githubusercontent.com/372831/86904349-e3943580-c110-11ea-8f89-7c139ecda751.png">

**Comment by kripod** [comment]
Yeah, it’s definitely an issue with react-polymorphic-box and I vaguely remember that TypeScript 4 had something on its roadmap to resolve the situation…

**Comment by kripod** [comment]
This should be fixed on the language level of TypeScript, as far as I know: https://github.com/microsoft/TypeScript/pull/31023

**Comment by peduarte** [comment]
@kripod ah nice, thanks for chiming in. I wasn't sure if this was directly related to react-polymorphic-box or not.
I also created this, which could be related: https://github.com/christianalfoni/stitches/issues/44
