### ISSUE TITLE
[0.1.0-canary.x] TS error when nesting local variable inside selector nested inside variant

### ISSUE THREAD

**Issue by nderscore** [modulz/stitches#430]
# Bug report

Last seen on: `@stitches/react@0.1.0-canary.12`

Trying to assign a local variable inside a nested selector inside variant styles causes a type error on the variant.

## To Reproduce

https://codesandbox.io/s/serverless-darkness-swi06?file=/src/App.tsx

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
