### ISSUE TITLE
TS: Error using `styled.element` syntax when importing `styled`

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#433]
Repro https://codesandbox.io/s/small-sun-mrqxb?file=/src/App.tsx

**Comment by Aslemammad** [comment]
@peduarte  Can I check this, and if I solved it, then send a PR?

**Comment by peduarte** [comment]
Hey! Actually, this is irrelevant now, since we dropped `proxy` support

Thanks for the reminder 😄
