### ISSUE TITLE
[0.1.0-canary.12] No more StitchesProps

### ISSUE THREAD

**Issue by Razinsky** [modulz/stitches#434]
I'm in the middle of migrating to latest canary version following the migration guide. However, I cannot find anything related to the removal of `StitchesProps` type which is very handy. Is there a new alternative?

**Comment by jorenrui** [comment]
You could use `React.ComponentProps` to get all the props of a component like:

```jsx
type IProps = React.ComponentProps<typeof StyledButton> & {
  loading?: boolean;
  children: React.ReactNode;
}
```

or use `StitchesVariants` to get only the variants of the styled component.

```jsx
export type IBoxVariants = StitchesVariants<typeof StyledBox>;
```

**Comment by Razinsky** [comment]
Yes `React.ComponentProps<typeof StyledButton>` works except for the `as` prop which may be important as well. What would be the best solution to keep the `as` prop?

**Comment by jorenrui** [comment]
@Razinsky how bout this?

```diff
type IProps = React.ComponentProps<typeof StyledButton> & {
+ as?: keyof JSX.IntrinsicElements;
  loading?: boolean;
  children: React.ReactNode;
}

+ export function Button({ as = 'button', children, ...props }: IProps) {
  return (
    <StyledButton
+      as={as}
      {...props}
    >
      {children}
    </StyledButton>
  );
}
```
<img width="512" alt="image" src="https://user-images.githubusercontent.com/23741509/108965150-6d503d80-76b7-11eb-969b-c41bf81deb93.png">

Found `JSX.IntrinsicElements` when I was digging to stitches/react/types xD

<img width="544" alt="image" src="https://user-images.githubusercontent.com/23741509/108965312-aa1c3480-76b7-11eb-8752-390e9fbb7a13.png">

**Comment by peduarte** [comment]
I dont think the previous `StitchesProps` contained `as` anyway. Maybe it did, dont remember. 

But its not that simple. You may type the `as` prop but that doesnt mean your wrapped component is truly polymorphic with types and ref.

Thats something thats outside the scope of Stitches. If you want to wrap Stitches components as your own, and still offer polymorphism youd have to use something like `@radix-ui/react-polymorphic` (to be documneted, but here's a [usage demo](https://github.com/radix-ui/design-system/blob/master/components/Button.tsx)) or `react-polymorphic-box`

**Comment by Razinsky** [comment]
Thank @peduarte ! I confirm the `as` prop was there before, thus my question. The typings weren't great and that's something I was really hoping to be fixed. Indeed something like  `react-polymorphic-box` is exactly what we need. I'll try `@radix-ui/react-polymorphic` just because I like `modulz` ecosystem! 

I'm going to close this one now.
