### ISSUE TITLE
type events based on `as` prop

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#44]
the `onKeyDown` event when using an `input`
<img width="836" alt="CleanShot 2020-07-08 at 11 54 05@2x" src="https://user-images.githubusercontent.com/372831/86905109-e5122d80-c111-11ea-8da5-25f735fba875.png">

the `onKeyDown` event when using `as="input"`
<img width="962" alt="CleanShot 2020-07-08 at 11 54 13@2x" src="https://user-images.githubusercontent.com/372831/86905147-f2c7b300-c111-11ea-9807-9f0d30e8819f.png">

Could be an issue with [react-polymorphic-box ](https://github.com/kripod/react-polymorphic-box)
/cc @kripod

Probably related to #43

**Comment by kripod** [comment]
As noted on #43, this can be improved on the language level by TypeScript, with better function parameter inference.

**Comment by peduarte** [comment]
Awesome. What does it take to get it into here? 

I suppose its a change that needs to be done in react-polymorphic-box, then released. Then update the deps here?

**Comment by kripod** [comment]
I’m not quite sure whether react-polymorphic-box will need an update. We should follow the updates of TypeScript and see whenever a fix gets released.
