### ISSUE TITLE
Feature request: add source maps

### ISSUE THREAD

**Issue by elektronik2k5** [modulz/stitches#442]
Hello and thank you for pushing the CSS-in-JS ecosystem further! :)

**Is your feature request related to a problem? Please describe.**
Source maps help trace and debug where a given style comes from. This is especially needed in an atomic CSS based solution like Stitches, cause practically every property lives in its own generated rule. 

**Describe the solution you'd like**
Source maps which will point to the source file and line where the style came from - in development and production modes. A developer should be able to see the filename next to the rule, be able to click it and the taken to the exact source file and line where it is defined. 

**Describe alternatives you've considered**
Don't think there are any.

**Additional context**
For me, not having source maps is a deal breaker. That's why I've been using Emotion (as opposed to styled-components, which lacks source maps) over the last few years. I recently discovered that Linaria has source maps too, but haven't tried it yet.
Debugging should be **easy** and guesswork free. I'd love to try Stitches once it has source maps.

Again, thanks for the fresh take on CSS-in-JS and all your efforts! :heart:

**Comment by jonathantneal** [comment]
I bear the unpopular news that we will not be adding this. Source maps are available when SSR is used, but for now we won’t be adding this to the JS-generated styles. It would require using an inconsistent API with the browser (_cleverly using `new Error().stack`)) and a bit of heft to convert that into the object that is stringified and converted into base64 to ultimately become the usable map. Add to this some folks might not want the SSR versions to point back to static/server compiled source that is not available. Add to this, we now, for performance reasons use the CSSOM which does not support the addition of comment nodes.
