### ISSUE TITLE
Pass down disabled

### ISSUE THREAD

**Issue by ankri** [modulz/stitches#447]
# Bug report

Hi. First of all, amazing library. Thank you very much for developing it as Open Source (and also thank you for radix-ui ❤️ )

## Describe the bug

When we have a `styled('button')` that uses a boolean variant called `disabled`, `disabled` is then not passed down to the HTML Button. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Have a look at this [codesandox](https://codesandbox.io/s/stitches-disabled-button-y84ql?file=/src/App.tsx)

Create a theme:
```tsx
const { styled } = createCss({
  theme: {
    colors: {
      primary900: "#0000d6",
      primary500: "blueviolet",
      primary100: "#d4bff9",
      white: "white"
    }
  }
});
```

And a button:

```tsx
const Button = styled("button", {
  borderColor: "$primary900",
  backgroundColor: "$primary500",
  color: "$white",
  padding: "0.5rem",
  minWidth: 175,
  variants: {
    disabled: {
      true: {
        backgroundColor: "$primary100"
      }
    }
  }
});
```

And render the button
```tsx
      <Button
        disabled
        onClick={() => {
          alert("Hello World");
        }}
      >
        Disabled
      </Button>
```

![image](https://user-images.githubusercontent.com/2842920/109484182-6c852600-7a80-11eb-8360-6374f4f99232.png)

## Expected behavior

The rendered HTML button should have the `disabled` prop. 

## System information

- Version of Stitches: 0.1.0-canary.12

**Comment by peduarte** [comment]
Variants are not passed down to DOM elements on purpose.

A few people have mentioned this exact example, but after chatting for a bit, we always reach the same conclusion: why not use the `:disabled` selector, instead of a variant? When you have first-class selectors for "states", there is no need to use a variant. 

```diff
const Button = styled("button", {
  borderColor: "$primary900",
  backgroundColor: "$primary500",
  color: "$white",
  padding: "0.5rem",
  minWidth: 175,

+  '&:disabled': {
+      backgroundColor: "$primary100"
+  }
})
```

If absolutely necessary, we may introduce a function that allows users to determine whether to pass down or not. Similar to Emotion's `shouldForwardProp` function.

**Comment by ankri** [comment]
Thank you for the detailed explanation and sorry for not finding a related issue before opening.

May I suggest adding your example to the documentation. Maybe in a category called "best practices" or "guides"? I think more people will stumble upon this and wonder why disabled is not passed down to the DOM element. 

---

I have thought about and discussed it with a colleague and found another another case for supporting `:disabled` like you described and why it should NOT be passed down to the DOM element. There would be a pitfall when we would pass down the prop and also want to utilize polymorphism: Imagine we have a `Button` that has a `disabled` variant and the prop would be passed down to `button`. Easy. No problem there. 
But if we then wanted to render the `Button` as an `a` there could be confusion, because `disabled` cannot be passed down to the DOM anchor element, because anchors do not support `:disabled`. So the rendered "AnchorButton" would look like it's disabled but in reality it would not and still fire on `onClick`. 

So I think there is no way around a Wrapper Component to truly support polymorphic Buttons:

```tsx
const StyledButton = styled("button", {
  borderColor: "$primary900",
  backgroundColor: "$primary500",
  color: "$white",
  padding: "0.5rem",
  minWidth: 175,
  variants: {
    isDisabled: {
      true: {
        backgroundColor: "$primary100"
      }
    }
  }
});

// someone smarter than me has to figure out how to type the props
const Button = (props: any) => {
  // Please use `useButton` from "reakit" or "rect-spectrum" for accessibility 
  const { as, disabled, type, children, ...otherProps } = props;

  if (
    disabled &&
    (as === undefined ||
      as === "button" ||
      (as === "input" && type === "submit"))
  ) {
    return (
      <StyledButton as={as} type={type} disabled isDisabled {...otherProps}>
        {children}
      </StyledButton>
    );
  } else if (disabled) {
    return (
      <StyledButton
        as={as}
        isDisabled
        {...otherProps}
        onClick={(event) => {
          event.preventDefault();
        }}
      >
        {children}
      </StyledButton>
    );
  } else {
    return (
      <StyledButton as={as} type={type} {...otherProps}>
        {children}
      </StyledButton>
    );
  }
};

 
Like you said in your demo. Buttons are complicated. Thanks again for your answer and feel free to close the issue 👍

**Comment by peduarte** [comment]
Thanks for the feedback. I'm working on the docs atm so I've made a note of this.
