### ISSUE TITLE
Consider replacing `when` with "something better"

### ISSUE THREAD

**Issue by jonathantneal** [modulz/stitches#449]
**Is your feature request related to a problem? Please describe.**

We would like the ability to intersperse aliased media queries between properties. This isn’t possible without inline media queries, which are not aliased. We would like something like [Custom Media Queries](https://www.w3.org/TR/mediaqueries-5/#custom-mq).

```pcss
@custom-media --smallViewport (width <= 30em);

.component {
  /* styles for a component */

  @media (--smallViewport) {
    /* styles for a component in a small viewport */
  }

  /* more styles for a component */
}
```

Currently, conditional aliases are only accessible within the `when` property. The `when` property serves as a hook into accessing the `conditions` authored in a Stitches configuration. The `when` property in Stitches is not "_just CSS™_". JavaScript prohibits us from putting multiple `when` properties in a rule, so interspersing then with `when` is a non-starter.

**Describe the solution you'd like**

```pcss
@custom-media --smallViewport (width <= 30em);

.component {
  /* styles for a component */

  @media (--smallViewport) {
    /* styles for a component in a small viewport */
  }

  /* more styles for a component */
}
```

Or something else reflective of real CSS.

**Describe alternatives you've considered**

The following syntaxes have been kicked around:

```ts
{
  "@when (--smallViewport)": {
    ...styles
  }
}
```

```ts
{
  [config.conditions.smallViewport]: {
    ...styles
  }
}
```

```ts
{
  $conditions$smallViewport: {
    ...styles
  }
}
```

**Additional context**

I think the more our API resembles something that could ship natively, the more likely it is so serve people better and longer.

**Comment by peduarte** [comment]
Any API that requires the user `import`'ing something is out of the question IMO.

My favourite is `@when` but typing here will be tricky, if we can nail it, I think thats the winner. It's close to CSS and I think thats a great thing. 

`$` should be reserved for tokens I think

Some other ideas:
```jsx
{
  'when@smallViewport': {
    ...styles
  }
}
```

```jsx
{
  '@smallViewport': {
    ...styles
  }
}
```

**Comment by jonathantneal** [comment]
Here’s what we’ve come up with so far:

---

A **custom when query** is defined with the `@condition` rule:

```
@condition <extension-name> <boolean-condition-list> ;
```

The `<extension-name>` can then be used to represent a `<boolean-condition-list>`.

```
<boolean-condition-list> = <boolean-condition>*
```

```
<boolean-condition> = media() | supports()
```

A `<boolean-condition>` represents boolean algebra, which are `media()` or `supports()` functions representing [Media Queries](https://www.w3.org/TR/mediaqueries-4/#mq-syntax) or [Supports Rules](https://drafts.csswg.org/css-conditional-4/#at-supports-ext).

```
media() = media( [ <mf-plain> | <mf-boolean> | <mf-range> ] )

supports() = supports( <declaration> )
```

---

> For example, if a responsive site uses a particular breakpoint in several places, it can alias that with a reasonable name:
>
> ```pcss
> @condition --narrow-window media(max-width: 520px);
> 
> @when --narrow-window {
>   /* narrow window styles */
> }
> 
> @when --narrow-window and media(script) {
>   /* special styles for when script is allowed */
> }
> 
> /* etc */
> ```

Within Stitches, this translates to the following:

```tsx
const { css } = createCss({
  condition: {
    narrowWindow: 'media(max-width: 520px)
  }
})

const component = css({
  "@when $narrowWindow": {
     /* narrow window styles */
  },
  "@when $narrowWindow and media(script)": {
    /* special styles for when script is allowed */
  },
  /* etc */
})
```

**Comment by peduarte** [comment]
```jsx
createCss({
  media: {
    smallUp: ‘(min-width: 450px)‘,
    smallViewport: ‘(max-width: 30em)’
  }
});
```
```jsx
const Button = styled({
  ‘@smallUp’: {}, // => @media (min-width: 450px) :ballot_box_with_check:
  ‘@smallViewport’: {} // => @media (max-width: 30em) :ballot_box_with_check:
  ‘@media (max-width: 450px)‘: {} // => @media (max-width: 450px) :ballot_box_with_check:
  variants: {
    size: {
      small: ‘’,
      medium: ‘’,
      large: ‘’
    }
  }
})
```
```jsx
<Button size={{
  ‘@initial’: ‘small’,
  ‘@smallUp’: {} // => @media (min-width: 450px) :ballot_box_with_check:
  ‘@smallViewport’: {} // => @media (max-width: 30em) :ballot_box_with_check:
  ‘@media (max-width: 450px)’: {} // => @media (max-width: 450px) :ballot_box_with_check:
}}/>
```

**Comment by peduarte** [comment]
Done
