### ISSUE TITLE
Types disappear when I destructure `config` from `createCss`

### ISSUE THREAD

**Issue by horacioh** [modulz/stitches#453]
# Bug report

## Describe the bug

for some reason when I destructure the `config` from the return of `createCss` i loose all the types from all values (styled, css..) you can see the behaviour I describe in the video below.

## Expected behavior

I expect that destructuring another value does not break the types as you can see on this codesandbox: https://codesandbox.io/s/frosty-hill-8xxij?file=/src/stitches.config.js

## Screenshots

https://user-images.githubusercontent.com/725120/109946669-caac4600-7cd8-11eb-98ca-44b32baf39f2.mov

## System information

- OS: macOS
- Version of Stitches: @stitches/react@0.1.0-canary.12
- Version of Node.js: 12.20.1
- Typescript Version: 4.2.2 (both in devDependencies and in VSCode)

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
