### ISSUE TITLE
[0.1.0-canary.14] Numeric line height is converted to px

### ISSUE THREAD

**Issue by arempe93** [modulz/stitches#457]
# Bug report

## Describe the bug

I had initially reported this in a comment here https://github.com/modulz/stitches/commit/26e2ab13558270dbdd763520d9b47ac1b1e8eabc#r47572049, but since a release was made I'll add it as a tracked issue.

Since canary.14, any unitless `lineHeight` property

```js
lineHeight: 1.5      // either as a number
lineHeight: "1.5"    // or as a numeric string
```

get converted to px

```css
line-height: 1.5px;
```

## To Reproduce

https://codesandbox.io/s/line-height-bug-cslrw

## Expected behavior

Line height accepts numeric values to match CSS spec.

## System information

- Version of Stitches: 0.1.0-canary.14

**Comment by apostolos** [comment]
> `<number>` (unitless)
> The used value is this unitless <number> multiplied by the element's own font size.

So basically, `lineHeight` should produce unitless values or suffixed with an `em` instead of `px`.
