### ISSUE TITLE
[0.1.0-canary.14] Composed forwardRef components do not render correctly

### ISSUE THREAD

**Issue by arempe93** [modulz/stitches#462]
# Bug report

## Describe the bug

If you compose a `forwardRef` component

```ts
const Button = forwardRef((props, ref) => { ... })

const StyledButton = styled(Button, { ... })
```

the React component will not render, and a default `span` will be rendered instead.

## To Reproduce

https://codesandbox.io/s/stitches-composition-bug-mdk50

> Change to stitches canary.12 to see working behavior

## Expected behavior

Composed components that forward ref should render.

## System information

- Version of Stitches: 0.1.0-canary.14

**Comment by arempe93** [comment]
I discovered that in this code

https://github.com/modulz/stitches/blob/4b717fbd4bed9df4c4eb17110d887dac2ba4288e/packages/core/src/index.js#L338-L351

if I add an additional check to the L345 condition it works

```ts
init.$$typeof !== Symbol.for('react.forward_ref')
```

however, considering this is core code, that doesn't seem adequate. something should be done on the react side instead.

there may be a clever solution given that: while you inherit _styles_ from **ALL** composers, you will only ever _render_ the **LAST** composer.

**Comment by peduarte** [comment]
Hey, yep I just noticed that today too. Here's my repro with a Radix UI Component https://codesandbox.io/s/quizzical-faraday-d9wjk?file=/src/App.js
