### ISSUE TITLE
Typing/usage issue with variants that are keyed by indexed 

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#47]
Demo: https://codesandbox.io/s/stitches-passing-variant-as-number-doesnt-work-f1bnm

A variant with this shape:
```
variantName: {
  0: {},
  1: {},
  2: {}
}
```

gets types as `red?: 0 | 1 | 2`. But passing them down as numbers doesn't seem to work. Passing them as string does, but TS complains.

**Comment by hadihallak** [comment]
More info provided in the closed issue above 👆

**Comment by peduarte** [comment]
As a workaround, we can document that keys must be string.

**Comment by peduarte** [comment]
Update: https://codesandbox.io/s/stitches-passing-variant-as-number-doesnt-work-f1bnm?file=/src/App.js

- No more typescript errors.
- padding value as a number still doesn't work

**Comment by hadihallak** [comment]
Fixed in #134
