### ISSUE TITLE
[0.1.0-canary.x] Specificity issue with inherited variants + variants leaking as DOM attributes

### ISSUE THREAD

**Issue by apostolos** [modulz/stitches#473]
# Bug report

## Describe the bug

When a _Descendant_ styled component inherits variants from an _Ancestor_ styled component two problems are observed:

### 1. Specificity of ancestor variant styles is lower than descendant default styles:

![image](https://user-images.githubusercontent.com/41679/110689622-94e0f300-81eb-11eb-99ed-62055a5a987c.png)

### 2. Variant prop on descendant component leaks as a DOM attribute:

![image](https://user-images.githubusercontent.com/41679/110689739-b641df00-81eb-11eb-8f9b-beb8523d4462.png)

## To Reproduce

https://codesandbox.io/s/stitches-inherited-variant-attr-qf2l7?file=/src/App.tsx

## Expected behavior

- Inherited variant styles should have higher specificity than default component styles
- Inherited variant props should NOT be inserted as DOM attributes.

**Comment by peduarte** [comment]
Fixed, will be in next release
![image](https://user-images.githubusercontent.com/372831/119511531-cee57e00-bd72-11eb-944a-5b9ebe3362b7.png)

**Comment by apostolos** [comment]
Fixed since `0.2.0-canary.0`

**Comment by peduarte** [comment]
@apostolos YESS! sorry it took so long. The future is bright. @jonathantneal has re-written the whole variant composition logic. A couple of little bugs to iron out, related to this issue, so I'll keep it open till then. 

Thanks! :)

**Comment by peduarte** [comment]
This fix has now been released 🚀 

Release post: https://stitches.dev/blog/stitches-0.2.0

Thank you
