### ISSUE TITLE
Utils types not being applied when used inside of a variant.

### ISSUE THREAD

**Issue by DanishShah** [modulz/stitches#481]
# Bug report

## Describe the bug
Utils function types are not being inferred inside a variant

```javascript
const { styled } = createCss({
  theme: {
    colors: {
      primary900: "#0000d6",
      primary500: "blueviolet",
      primary100: "#d4bff9",
      white: "white"
    }
  },
  utils: {
    size: () => (values: (number | string)[]) => ({
      width: values[0],
      height: values[1] || values[0]
    })
  }
});
```

```javascript
const Button = styled("button", {
  borderColor: "$primary900",
  backgroundColor: "$primary500",
  color: "$white",
  padding: "0.5rem",
  minWidth: 175,
  size: ["50px", "10px"], // this works
  variants: {
    variant: {
      primary: {
        size: ["50px", "10px"] // this doesn't work
      }
    }
  }
});

```

## To Reproduce
https://codesandbox.io/s/stitches-disabled-button-forked-xv49k?file=/src/App.tsx

## Expected behavior
The types should work the same when utils functions are used inside variants

## System information

- OS: Linux
- Browser (if applies) safari
- Version of Stitches: 0.1.0-canary-18
- Version of Node.js: v15.2.1

**Comment by peduarte** [comment]
Fixed in `0.1.0`

**Comment by DanishShah** [comment]
Still not fixed, please check code sandbox.

**Comment by peduarte** [comment]
Ah, yes, we still have the typescript issue. My bad.

**Comment by peduarte** [comment]
Closing in favour of https://github.com/modulz/stitches/issues/602
