### ISSUE TITLE
Responsive variants aren't respecting usage order

### ISSUE THREAD

**Issue by ruijdacd** [modulz/stitches#483]
# Bug report

## Describe the bug

When using responsive variants, it seems that the order, in which the variant values are declared, matter when the styles are effectively injected on the page.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to this [sandbox](https://codesandbox.io/s/bold-sound-wdhdy?file=/src/App.tsx)
2. Inspect size of the column
3. See error

## Expected behavior

For this example the grid item should take up 2 columns for `bp1` and 3 columns for the `initial` breakpoints.

## System information

- OS: macOS
- Browser: All
- Version of Stitches: I believe this issue surfaced on the beta releases, since I don't recall having this problem when using the alpha releases
- Version of Node.js: Any

**Comment by jonathantneal** [comment]
> ### Expected behavior
> For this example the grid item should take up 2 columns for bp1 and 3 columns for the initial breakpoints.

That appears to be exactly what’s going on. `3` comes after `2`, and `initial` applies to all breakpoints.

<img width="260" alt="image" src="https://user-images.githubusercontent.com/188426/111148922-96e7e080-8562-11eb-953c-3f0b6f27413d.png">

Now, you may also be experiencing something else. If you’ve tried re-sorting your original variants, you _will_ notice that it won’t appear to work. This is a limitation in JavaScript itself, that numeric keys are always sorted.

```js
Object.keys({
  1: 'a',
  2: 'b',
  4: 'd',
  5: 'e',
  6: 'f',
  3: 'c',
}) // [ "1", "2", "3", "4", "5", "6" ]
```

```js
Object.values({
  1: 'a',
  2: 'b',
  4: 'd',
  5: 'e',
  6: 'f',
  3: 'c',
}) // [ "a", "b", "c", "d", "e", "f" ]
```

I believe the only way to work around this issue is to _not_ use numeric keys.

**Comment by ruijdacd** [comment]
> That appears to be exactly what’s going on. 3 comes after 2, and initial applies to all breakpoints.

Shouldn't the `initial` value be set before the other breakpoints? I believe in an earlier (alpha) release of Stitches, the values for the initial were being inserted before every other breakpoint and not the other way around.

> I believe the only way to work around this issue is to not use numeric keys.

I have updated the sandbox to use string keys and the issue remains the same, as the variant defined for `bp1` is never applied, due to the `initial` value being inserted after, causing a CSS order issue.

Correct me if I'm wrong, but I would expect the `initial` value to always be inserted before every other breakpoint, otherwise responsive variants would never truly work.

**Comment by ruijdacd** [comment]
It seems like this was working on `0.1.0-canary.12`, so that might help track the source of the issue

**Comment by peduarte** [comment]
Another repo raised by @colmtuite 

> Green never gets applied
> https://github.com/modulz/stitches/issues/483

**Comment by ruijdacd** [comment]
A possible solution for this, would be to organise the rules generated by stitches on several `<style>` tags, with a `media` attribute that would match the respective media query, from the stitches config.

[Fela](https://fela.js.org/) has this approach and it leads to smaller style tags, and fix CSS order issues when it comes to responsive styles. Not only that but it seems certain browsers tend to have issues when debugging large style tags (recall seeing this on Chrome and Firefox, though this could've been fixed by now).

<img width="718" alt="Screenshot 2021-03-29 at 12 23 58" src="https://user-images.githubusercontent.com/9107610/112829878-ac442b00-9089-11eb-8ccc-426f9ebf94d7.png">

**Comment by ruijdacd** [comment]
@peduarte is it possible to get an ETA on this fix? We've been betting heavily on Stitches for our design system, and we've been facing with this issue on many occasions.

I can have a look at the codebase and possibly look into fixing this, if no one is available to look into it.

**Comment by peduarte** [comment]
Fixed. Will be in the next release.

Validated here:
- https://codesandbox.io/s/sweet-lamport-bnsrs?file=/src/App.js
- https://codesandbox.io/s/stitches-ci-cra-forked-edl22?file=/src/App.tsx

**Comment by stefanobrambilla** [comment]
hi @peduarte , can you release this bug fix, is very blocked.
thanks

**Comment by peduarte** [comment]
@stefanobrambilla this bug fix is part of a larger piece of work, which is still undergoing thorough testing before being published.

This issue will close when it's releases - in a few days. Hold tight!

**Comment by peduarte** [comment]
This fix has now been released 🚀 

Release post: https://stitches.dev/blog/stitches-0.2.0

Thank you
