### ISSUE TITLE
Allow utils in themeMap for ease of typing for a more generic typing

### ISSUE THREAD

**Issue by elkevinwolf** [modulz/stitches#484]
**Is your feature request related to a problem? Please describe.**
Currently, trying to type a utility function implies repeating this pattern on almost every utility: 

```ts
margin: (config) => (value: keyof typeof config['theme']['space'] | (string & {})) => ({ })
marginHorizontal: (config) => (value: keyof typeof config['theme']['space'] | (string & {})) => ({ })
marginVertical: (config) => (value: keyof typeof config['theme']['space'] | (string & {})) => ({ })
```

**Describe the solution you'd like**
What if `themeMap` could also include the utilities rather than only the existing CSS props? On that way, we could do something like this:

```ts
import createCss, { defaultThemeMap } from "@stitches/react";

createCss({
  ...,
  utils: {
    marginHorizontal: (config) => (value) => ({
      marginLeft: value,
      marginRight: value,
    }),
  },
  themeMap: {
    ...defaultThemeMap,
    marginHorizontal: "space",
  },
});
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by peduarte** [comment]
Thanks for raising this. I have a note with the exact same idea and I'm really glad someone else mentioned it!

**Comment by peduarte** [comment]
We've been working on types and are introducing some new types to deal with his. Will post an update when its out.

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
