### ISSUE TITLE
Support gridTemplateRows and gridTemplateColumns with 'space' theme tokens

### ISSUE THREAD

**Issue by aliak00** [modulz/stitches#488]
# Bug report

## Describe the bug

Tried to set a space related theme token and use it in `gridTemplateRows` and `gridTemplateColumns` but it has no effect.

## To Reproduce
```typescript
import { createCss } from "@stitches/react";

export const { styled, css, global } = createCss({
  theme: {
    space: {
      $1: "40px"
    }
  }
});
```

```typescript
import * as React from "react";
import { styled } from "./stitches.config";

const Box = styled("div", {
  display: "grid",
  height: "100vh",
  gridTemplateAreas: `
    'one'
    'two'
  `,
  // set $1 to 40px for e.g and it'll have an effect
  gridTemplateRows: "$1 1fr",
  gridTemplateColumns: "1fr"
});
const One = styled("div", {
  backgroundColor: "yellow"
});
const Two = styled("div", {
  backgroundColor: "green"
});

export default function App() {
  return (
    <Box>
      <One>one</One>
      <Two>two</Two>
    </Box>
  );
}
```

## Expected behavior

The `$1` theme token should work?

## System information

Here: https://codesandbox.io/s/focused-sinoussi-zr907

**Comment by aliak00** [comment]
I guess it should be within the `sizes` type and not `spaces`?

**Comment by arempe93** [comment]
`sizes` is probably a good default if those properties are unmapped

fyi some work arounds:

**You can edit the theme map yourself in the beta version**

```js
import { defaultThemeMap } from '@stitches/core'

createCss({
  themeMap: {
    ...defaultThemeMap,
    gridTemplateRows: 'sizes',
    gridTemplateColumns: 'sizes'
  }
})
```

**You can reference any token on any scale by using `$scaleName$token`**

```js
styled({
  gridTemplateRows: '$sizes$2 1fr'
})
```

> More info: [Stitches Beta Migration Guide](https://stitches-site-git-beta.modulz-deploys.com/blog/migrating-from-alpha-to-beta)

**Comment by aliak00** [comment]
@arempe93 ah cool! That `themeMap` is going to be handy. Thanks!
