### ISSUE TITLE
Default variants are being ignored when "responsively applying variants"

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#492]
Say I have a `Button` with two color variants:
- `blue`
- `red`

I use `defaultVariants` and make the `blue` variant the default `color`.

Then, I render my `Button`, and set it to use violet on `bp1`:
```jsx
<Button color={{ bp1: 'blue' }} />
```

I would expect that by default the `Button` uses the `blue` color variant (initially)

Outcome: Default variant is not applied

Repro: https://codesandbox.io/s/tender-bhaskara-x41n0?file=/src/App.js

**Comment by ruijdacd** [comment]
I believe this might also be related to #483, which is causing responsive variants to not work as expected.

**Comment by peduarte** [comment]
Fixed. Will be out in the next release.

https://codesandbox.io/s/distracted-franklin-ydx5w?file=/package.json

**Comment by peduarte** [comment]
This fix has now been released 🚀 

Release post: https://stitches.dev/blog/stitches-0.2.0

Thank you
