### ISSUE TITLE
Multiple TypeScript errors in most basic example

### ISSUE THREAD

**Issue by RafalFilipek** [modulz/stitches#494]
# Bug report

Hi!

Here you can find super simple example https://github.com/RafalFilipek/stitches-ts

```
error TS2344: Type '{}' does not satisfy the constraint 'TConditions'.
  Property 'initial' is missing in type '{}' but required in type 'TConditions'.

...

 Types of property 'backgroundColor' are incompatible.
    Type 'string' is not assignable to type 'never'.

...

DeepStitchesComponentType' does not satisfy the constraint 'string'.
```

Also full TypeScript error log is embeded in README.

this example was tested with `typescript@4.2.3/4.2.2/4.1.5` and `@sittches/react@canary12/20`.

II hope it's something silly because I had no problem with `canary.12` some time ago.

## To Reproduce

```
git clone git@github.com:RafalFilipek/stitches-ts.git
cd stitches-ts
yarn
./node_mododules/.bin/tsc src/index.tsx
```

## Expected behavior

No error

## System information

- OS: MacOs / Windows
- Version of Stitches: 0.1.0-canary.20
- Version of Node.js: 14.16.0

**Comment by vovacodes** [comment]
I suppose, the only way of making stitches work in the meantime is to add `"skipLibCheck": true` to the tsconfig's `"compilerOptions"`?

**Comment by RafalFilipek** [comment]
https://github.com/RafalFilipek/stitches-ts/blob/main/tsconfig.json#L71 nope

**Comment by vovacodes** [comment]
@RafalFilipek `"skipLibCheck": true` It appears to be fixing it in my case: 
```
$ yarn list @stitches/react  typescript
yarn list v1.22.4
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ @stitches/react@0.1.4
└─ typescript@4.2.3
```

**Comment by peduarte** [comment]
Did you ever figure out what this is? I cloned your repo but cannot reproduce.

**Comment by peduarte** [comment]
Feel free to re-open with more information
