### ISSUE TITLE
[0.1.0-canary.x] Variants named with a $ prefix don't work

### ISSUE THREAD

**Issue by afzalsayed96** [modulz/stitches#495]
# Bug report

## Describe the bug

When we create variants with `$` prefix in it's name, the variant styles are not generated and attached to stylesheet

For instance, this does not work:

```js
const Button = styled("button", {
  variants: {
    color: {
      $primary: {},
      $white: {}
    }
  }
});
```

Though, this works

```js
const Button = styled("button", {
  variants: {
    color: {
      primary: {},
      white: {}
    }
  }
});
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://codesandbox.io/s/stitches-disabled-button-forked-06rxp?file=/src/App.tsx

## Expected behavior

I don't know if this is a bug or a feature request. But would it be too much to expect variants named similarly as tokens to work OOTB?

## Screenshots

N.A.

## System information

Environment: CodeSandbox

## Additional context

We generate variants for our primitive components like `Box`, `Text` from our theme tokens. So, in `Text`, a variant named `color` takes values defined in theme.colors
```js
const colorVariants = generateThemeVariants(theme.colors, (token) => ({ color: `$${token}` }))

const Text = styled(Box, {
  variants: {
    color: colorVariants
  }
}
```

Now we can do
```js
<Text color="primary" /> // without the $
```

But it get's confusing when used along with `css`
```js
<Text color="primary" css={{ borderColor: "$primary" }} />
```

We kinda have to mentally keep track of where to use $ and where not to. For consistency, I'd prefer to make the variants follow the same convention as that of token (where they use name from theme tokens)

**Comment by jonathantneal** [comment]
We’ve moved away from using `$` anywhere outside of tokens, and thus we no longer recommend using `$` for non-tokens.

**Comment by afzalsayed96** [comment]
@jonathantneal what about when we want to have a non `$` special  character in token. Like `%` as mentioned in https://github.com/modulz/stitches/issues/525
