### ISSUE TITLE
Tokens in outline shorthand not working

### ISSUE THREAD

**Issue by rafgraph** [modulz/stitches#496]
# Bug report

## Describe the bug

Color tokens in outline shorthand do not work (I haven't tried other token types).

## To Reproduce

See this codesandbox: https://codesandbox.io/s/goofy-brook-7iyxi?file=/src/App.js

```js
export const { styled } = createCss({
  theme: {
    colors: {
      green: "rgb(0,168,0)"
    }
  }
});

// this works
const OutlineShorthandNoTokens = styled("div", {
  margin: "10px",
  outline: "2px solid rgb(0,168,0)"
});

// this does not work
const OutlineShorthandColorToken = styled("div", {
  margin: "10px",
  outline: "2px solid $green"
});

// this works
const OutlineColorTokenNotShorthand = styled("div", {
  margin: "10px",
  outlineColor: "$green",
  outlineWidth: "2px",
  outlineStyle: "solid"
});
```

## Expected behavior

For tokens in `outline` shorthand to work, e.g. `outline: "2px solid $green"`.

## System information

- Version of Stitches: `0.1.0-canary.20`

**Comment by RafalFilipek** [comment]
Hi,

This works just fine according to [this mapping](https://stitches-site-git-beta.modulz-deploys.com/docs/tokens#property-mapping).

What you can do is 

```
outline: "2px solid $colors$green"
```

You can find more info [href](https://stitches-site-git-beta.modulz-deploys.com/docs/tokens#scale-prefixed-tokens).

**Comment by rafgraph** [comment]
@RafalFilipek, yes `outline: "2px solid $colors$green"` works, thanks for the tip.

However, I think using `$colors$green` should only be necessary when referencing a token from inside another token or when used outside of the Property Mapping.

The Property Mapping says that `colors` tokens are mapped to `outlineColor` (which works fine),  so I believe the intended behavior is for it to work in the `outline` shorthand as well.

For example, the `border` shorthand works fine `border: "2px solid $green"`.

**Comment by peduarte** [comment]
Thanks! I think in this case it's probably fine to map outline to colors. 

Doesn't look like we map outline at all currently.

**Comment by rafgraph** [comment]
I see, you're not mapping the shorthand first to the individual properties and then to the token types for each property. This seems to cause another counter-intuitive issue with `border` shorthand. As a user, my expectation for css shorthand is to simply be a way to combine the properties (syntactic sugar).

These are small issues, but something to maybe consider as you approach v1.

From sandbox: https://codesandbox.io/s/busy-ganguly-wifpd?file=/src/App.js:115-643
```js
export const { styled } = createCss({
  theme: {
    colors: {
      green: "rgb(0,168,0)"
    },
    borderWidths: {
      defaultWidth: "2px"
    },
    borderStyles: {
      defaultStyle: "dashed"
    }
  }
});

// this does not work, but to me is the logical way to write shorthand
const BorderShorthandTokenNotWorking = styled("div", {
  margin: "10px",
  border: "$defaultWidth $defaultStyle $green"
});

//  this works
const BorderShorthandTypeTokensWorking = styled("div", {
  margin: "10px",
  border: "$borderWidths$defaultWidth $borderStyles$defaultStyle $green"
});

// this works
const BorderTokenNotShorthand = styled("div", {
  margin: "10px",
  borderColor: "$green",
  borderWidth: "$defaultWidth",
  borderStyle: "$defaultStyle"
});
```

**Comment by peduarte** [comment]
@rafgraph each property can only be mapped to one scale. So for shorthands that accept multiple values - from multiple scales - we need to pick one. For the others, you need to use the [scale-prefixed token syntax](https://stitches.dev/docs/tokens#scale-prefixed-tokens). 

I understand it's a bit confusing, but scaled can share the same token name. For example, a `primary` token could exist in `colors`, `borderWidths` and `borderStyles`. 

The parsing algorithm would get insanely complex, and we'd eventually be forced into forcing users into defining their values in a specific order. For example, `border: [width] [style] [color]`

**Comment by rafgraph** [comment]
That makes sense. FWIW, given the tradeoff my personal preference would be for enforcing a specific order for shorthand tokens, `border: [width] [style] [color]` (this order is kind of already the convention I think), instead of only mapping the shorthand to one scale.

**Comment by peduarte** [comment]
@rafgraph that's valid feedback, appreciate that! Another issue to keep in mind is that you can omit certain values from certain properties. So even if we enforce the order above, `border: solid red` is still valid. 

Anyway, you get the idea 😄  But your feedback is noted!

**Comment by peduarte** [comment]
https://github.com/modulz/stitches/releases/tag/v0.1.1

**Comment by rafgraph** [comment]
@peduarte  Yeah I think you're right, that would be going down a rabbit hole of complexity and edge cases.. api design is hard.

Though only mapping one scale to shorthand still feels a bit arbitrary and inconsistent (`border: "$borderWidths$defaultWidth $borderStyles$defaultStyle $green"` doesn't feel right). I think I'd be in favor of always requiring scale-prefixes in shorthand and adding an invariant error explaining to the user why prefixes are always required in shorthand (I'm a fan of consistency).

Just a thought, but it might be possible to take this a step further and infer what the user/dev means by allowing globally unique tokens to be un-prefixed in shorthand, and then throwing an invariant error if a non-unique token is used without a prefix. This would add a bit of complexity overall but could ramp well where apps with few tokens (and tokens with `$longAndSpecificNames`) generally wouldn't need to worry about prefixes, and an invariant error can explain why a prefix needs to be added once it's required.

**Comment by peduarte** [comment]
@rafgraph really appreciate your feedback, it means a lot to us. this has been noted and we'll definitely consider it.

**Comment by peduarte** [comment]
@rafgraph for the sake of history and tracking, would you be willing to raise a discussion about this?

**Comment by rafgraph** [comment]
Discussion created, see #529
