### ISSUE TITLE
Yarn build should maybe run the typescript compiler to ensure types are sound

### ISSUE THREAD

**Issue by aliak00** [modulz/stitches#498]
**Is your feature request related to a problem? Please describe.**

Recently ran in to an issue where production builds were not building with the typescript compiler because of unsound types in stitches.

**Describe the solution you'd like**
I'm not familiar with the build scripts in `.bin` but maybe they should run the typescript compiler to make sure types are good.

**Additional context**
Would avoid issues like #497

**Comment by peduarte** [comment]
Closing in favour of the related issues.
