### ISSUE TITLE
Typescript Error when passing css prop to styled component 

### ISSUE THREAD

**Issue by mikemcavoy** [modulz/stitches#506]
# Bug report

## Describe the bug
When wrapping a styled component I'm not able to pass anything into the css prop without typescript giving the following error...

`The expected type comes from property 'css' which is declared here on type 'IntrinsicAttributes & Omit<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<...>> & { ...; }, "css" | "as"> & { ...; } & VariantsCall<...>'`

It seems like the type of the css prop is 
`((string | number | boolean | ComponentSelector | Keyframes | SerializedStyles | ArrayInterpolation<undefined> | ObjectInterpolation<...> | ((theme: any) => Interpolation<...>) | null)`
rather than type
`InternalCSS`

## To Reproduce
![image](https://user-images.githubusercontent.com/67292835/112232737-fdd75a80-8c30-11eb-9bfb-7e362dd012d1.png)
![image](https://user-images.githubusercontent.com/67292835/112232490-928d8880-8c30-11eb-8265-80eca6eff0b7.png)

## System information

- Version of Stitches: v0.1.0
- Version of Node.js: v15.5.1

## Additional context

Using Typescript 4.2.3

**Comment by peduarte** [comment]
Related: https://github.com/modulz/stitches/issues/407

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
