### ISSUE TITLE
Theme token not being parsed when used with `css()`

### ISSUE THREAD

**Issue by DanishShah** [modulz/stitches#522]
# Bug report
Theme token when used inside `css()` doesn't parse the actual token value

## Describe the bug
![image](https://user-images.githubusercontent.com/10388290/112619511-6f8bf000-8e4d-11eb-9112-0a8929fba9cf.png)

## To Reproduce
https://codesandbox.io/s/stitches-disabled-button-forked-xv49k?file=/src/App.tsx

## Expected behavior
The token value should properly parse when used inside `css()`

**Comment by peduarte** [comment]
this has been fixed in `0.1.4`, demo here https://codesandbox.io/s/stitches-disabled-button-forked-h2oru

Thanks!
