### ISSUE TITLE
[0.1.3] FOUC after upgrading from alpha to beta

### ISSUE THREAD

**Issue by afzalsayed96** [modulz/stitches#523]
# Bug report

## Describe the bug

I'm noticing a prominent Flash Of Unstyled Content after migrating to `v0.1.x`

## Screenshots

Before in alpha:

![alpha](https://user-images.githubusercontent.com/14029371/112621193-77e52a80-8e4f-11eb-9967-014a851e5873.gif)

After in beta:

![beta](https://user-images.githubusercontent.com/14029371/112621204-7ae01b00-8e4f-11eb-9f3c-35aab93979a0.gif)

## Additional Context

We are using CRA and not relying on SSR

**Comment by peduarte** [comment]
Thanks, we're aware of this and working on it 🔥

**Comment by DanTsk** [comment]
@peduarte sorry for bothering you, but any progress on this issue? 🤔

**Comment by peduarte** [comment]
@DanTsk yeah, loads. We've improved perf 20x. 

It should be released by end of the week or early next week

**Comment by jemmyphan** [comment]
hi @peduarte , sorry for asking.
has this issue been resolved?

I still face this issue on the latest release.

**Comment by peduarte** [comment]
@jemmyphan yeah, but not released. we have a few more things to implement/fix before releasing

But soon! 🙏

**Comment by peduarte** [comment]
This fix has now been released 🚀 

Release post: https://stitches.dev/blog/stitches-0.2.0

Thank you
