### ISSUE TITLE
var name are wrong since 0.1.4

### ISSUE THREAD

**Issue by yovanoc** [modulz/stitches#524]
# Bug report

## Describe the bug

It seems to get rid of prefixes when generating css classes, here --LIGHT_BLUE instead of --colors-LIGHT_BLUE (same for fonts, and probably others)

## Screenshots

![image](https://user-images.githubusercontent.com/7302317/112627808-59bd0180-8e32-11eb-8ea6-be6ac9ddb308.png)

## System information

- OS: macOs
- Browser (if applies) tested on chrome and safari
- Version of Stitches: 0.1.4
- Version of Node.js: 15.12

**Comment by peduarte** [comment]
@yovanoc can you share a codesandbox? or share the relevant code? (theme config, usage, etc)

thanks

**Comment by yovanoc** [comment]
the stitches config: https://gist.github.com/yovanoc/7e02e06c910d6538155bbbdcd3bc61ec
my _app.tsx where there is my globalStyles: https://gist.github.com/yovanoc/3dcb31928a3880758c1b1b2185f24494
the index.tsx page: https://gist.github.com/yovanoc/b3be7cfd1a12fbc3f023e5e2fdf69076

**Comment by peduarte** [comment]
Oh, right, this happens because you're passing in an empty `themeMap` object to `createCss`, so it's essentially stopping the mapping from working. 

Heres a working demo, with that commented out https://codesandbox.io/s/jolly-voice-6drck?file=/src/App.tsx

https://stitches.dev/docs/api#thememap

**Comment by yovanoc** [comment]
Oh I see, maybe not enough clear at first sight but thanks

**Comment by peduarte** [comment]
No problem. I will improve the docs!
