### ISSUE TITLE
Special character when used in variants key are not being applied

### ISSUE THREAD

**Issue by DanishShah** [modulz/stitches#525]
# Bug report

## Describe the bug
When we use `"100%"` as a variant key, its css properties are not applied

## To Reproduce
https://codesandbox.io/s/lingering-moon-42j9k?file=/src/App.tsx

## Expected behavior
Special character used as variant key should behave exactly like any other key value

**Comment by DanishShah** [comment]
Related to #495

**Comment by rafgraph** [comment]
Also spaces and colons too. See #564 and https://codesandbox.io/s/stitches-variant-key-bug-5z92g?file=/src/App.tsx

**Comment by peduarte** [comment]
Closing in favour of https://github.com/modulz/stitches/issues/495
