### ISSUE TITLE
Tooltip is not showing when using custom components as Slot

### ISSUE THREAD

**Issue by horacioh** [modulz/stitches#526]
# Bug report

## Describe the bug

When using the `as` prop and passing a custom component inside a tooltip, the tooltip is not visible when hover the component

## To Reproduce

1. Go to https://codesandbox.io/s/heuristic-pine-nulv0?file=/src/App.tsx
2. hover on the link with the content "custom link"

## Expected behavior

the custom tooltip should be visible after the proper delay
You can see the expected behaviour in the button on the right side

## Screenshots

<img width="711" alt="Screenshot 2021-03-26 at 15 01 34" src="https://user-images.githubusercontent.com/725120/112643004-2be0b880-8e44-11eb-8346-7df1ae733ed1.png">

![Screenshot 2021-03-26 at 15 03 09](https://user-images.githubusercontent.com/725120/112643342-909c1300-8e44-11eb-9e09-7d0a3398f036.png)

![Screenshot 2021-03-26 at 15 03 50](https://user-images.githubusercontent.com/725120/112643343-9134a980-8e44-11eb-979c-a9a784b3e052.png)

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) Brave
- Version of Stitches: 0.1.4
- Version of Node.js: ?

## Additional context

maybe the Link component needs to be wrapped with `forwardRef`? or the box should be implemented differently?

thanks in advance!

**Comment by peduarte** [comment]
Hey Horacio 👋 

You are right! You need to wrap `Link` in `React.forwardRef` 🎉

It's something that has to be done consumer-side.

**Comment by benoitgrelard** [comment]
Yep that's correct. This is an annoying one because we can't really guide you through DX.
However, React already will throw an error for you to let you know that you have a functional component and something is trying to attach a ref to it.
See the log in your case:

![image](https://user-images.githubusercontent.com/1539897/112649350-444fd380-8e42-11eb-9c14-44328bac8d6b.png)

**Comment by horacioh** [comment]
indeed wrapping the component with `forwardRef` does the trick!

```ts
import { forwardRef } from "react";
import { Link as RouterLink } from "react-router-dom";

const Link = forwardRef(({ to, children, ...props }, ref) => {
  return (
    <RouterLink to={to} {...props} ref={ref}>
      {children}
    </RouterLink>
  );
});
```

🎉💪🏼
