### ISSUE TITLE
TS: Spread Object styles 

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#53]
Thinking of how we can eventually support people abstracting styles without getting type errors, eg:

```jsx
const sharedCss = {
  outline: 0,
}

const Component = styled.div({
  ...sharedCss,
})
```

Currently, TS complains because in `sharedCss` the `outline` property value is `0` as a Number. And Stitches expects `outline` to be `"0"` as a String.

Technically, they're both valid, and right now it's unknown why the error appears. 

Im curious about whats the best DX we can apply here?

Should we relax the CSS Types to essentially allow string or numbers when it makes sense?

---

Update: 
This also happens with certain properties like appearance: 'none',. If its added in the shared css object, when you spread it complains. But if you add it directly to the CSS definition, it's fine.. haha wut

Sandbox demo https://codesandbox.io/s/gh-stitches-spread-shared-css-oject-3ss8p?file=/src/App.tsx

**Comment by peduarte** [comment]
This also happens with certain properties like `appearance: 'none',`. If its added in the shared css object, when you spread it complains. But if you add it directly to the CSS definition, it's fine.. haha wut

**Comment by hadihallak** [comment]
I think TS is complaining because the sharedCss obj wasn't cast as `const` so it infers that the outline property is of type number instead of 0. 

simply changing:
```
const sharedCss = {
  outline: 0,
}
```

to:
```
const sharedCss = {
  outline: 0,
} as const
```

should fix this issue.
I do agree tho that the types could use some relaxing tho as casting things to const was a bit unexpected to me

**Comment by peduarte** [comment]
Nice one 👍
