### ISSUE TITLE
Variant props being passed down to DOM elements

### ISSUE THREAD

**Issue by DanishShah** [modulz/stitches#532]
# Bug report

## Describe the bug
Styled components when reused with variants pass the variant prop down to the DOM element

![image](https://user-images.githubusercontent.com/10388290/112854114-221cb680-90cb-11eb-9a48-fcdd667ed34a.png)

## To Reproduce
Comparison of alpha version with beta
Alpha Version:
https://codesandbox.io/s/variant-props-alpha-b0cwp?file=/src/App.tsx
Beta Version:
https://codesandbox.io/s/variant-props-beta-nc78b?file=/src/App.tsx

## Expected behavior
Should work as it was in alpha

**Comment by peduarte** [comment]
Thanks for raising that. By default, variants should not be passed down to the DOM.

It seems to only happen when a Stitches Component composes another component which creates the variant.

**Comment by DanishShah** [comment]
Yes, that's the case

**Comment by peduarte** [comment]
Fixed, will be in next release

![image](https://user-images.githubusercontent.com/372831/119517850-44078200-bd78-11eb-8ed2-d459c087b0a9.png)

**Comment by peduarte** [comment]
This fix has now been released 🚀 

Release post: https://stitches.dev/blog/stitches-0.2.0

Thank you
