### ISSUE TITLE
[0.1.x] Perf degradation after migrating from alpha to beta

### ISSUE THREAD

**Issue by afzalsayed96** [modulz/stitches#535]
# Bug report

## Describe the bug

In alpha version of stitches we followed the [below pattern](https://discord.com/channels/752614004387610674/752795957674115092/757995397603000380) for dynamic prop based styling due to the lack of `variants` support in `css` API
```js
const fooStyles = props => css({
  backgroundColor: props.danger ? 'red' : 'blue'
})

const App = props => <div className={fooStyles(props)} />
```

After migrating to beta, we have started noticing a slowdown on client side navigation because of compounding effect from this pattern.

I am aware that `css` API now supports `variants` but I see no reason why doing this should be slower in beta.

## To Reproduce

Alpha Example: https://codesandbox.io/s/beautiful-dawn-2vdjt
Beta Example: https://codesandbox.io/s/misty-water-l5fy6

## Expected behavior

Beta version should have similar or better performance as compared to alpha version.

## Screenshots

Alpha: https://csb-2vdjt-2bigbzelq-afzal4.vercel.app/

![Screenshot 2021-04-01 at 3 16 05 PM](https://user-images.githubusercontent.com/14029371/113282008-fb959000-9303-11eb-980f-c508720873a3.png)

Beta: https://csb-l5fy6-5du6dtx8u-afzal4.vercel.app/

![Screenshot 2021-04-01 at 3 15 56 PM](https://user-images.githubusercontent.com/14029371/113281994-f89a9f80-9303-11eb-8c92-0b8d6b938a06.png)

**Comment by afzalsayed96** [comment]
Even `variants` with `css` currently perform worse than the alpha example:

Demo: https://codesandbox.io/s/elastic-silence-870md (https://csb-870md-bz5d2217h-afzal4.vercel.app)

**Comment by peduarte** [comment]
@afzalsayed96 thanks for raising this <3

We're aware of this issue and we're currently working on it. We've made good progress over the last few days and hope to have this wrapped up early next week

![image](https://user-images.githubusercontent.com/372831/113563194-8d084900-9607-11eb-8f26-d525309e328b.png)

**Comment by afzalsayed96** [comment]
Nice!

**Comment by jonathantneal** [comment]
Hey @afzalsayed96, would you retest this in 0.1.7? I’m seeing similar results, but my tests produce very different results, like `App (3.5ms of 7.8ms)` for Alpha and `App (5ms of 6.8ms)` for Beta.

**Comment by peduarte** [comment]
Sneak peek: 
![image](https://user-images.githubusercontent.com/372831/119892208-313cab00-bf3a-11eb-82e3-44dadf33ed51.png)

**Comment by StephenHaney** [comment]
Thank you for providing the CodeSandbox repros — this issue directly helped us track it down.

**Comment by afzalsayed96** [comment]
![RuCiax1](https://user-images.githubusercontent.com/14029371/119936536-f6249100-bfa6-11eb-99d3-753c20529f82.gif)

**Comment by afzalsayed96** [comment]
Tested out the latest canary release. And theme creation seems to be still 30-40x slower :(

alpha: https://codesandbox.io/s/agitated-boyd-sxmql?file=/src/stitches.config.ts
![Screenshot 2021-06-07 at 10 03 09 PM](https://user-images.githubusercontent.com/14029371/121056813-39b7a000-c7dc-11eb-9a30-2c3ba0061894.png)

beta (canary): https://codesandbox.io/s/vigorous-rubin-08xmr?file=/src/stitches.config.ts
![Screenshot 2021-06-07 at 10 03 33 PM](https://user-images.githubusercontent.com/14029371/121056868-489e5280-c7dc-11eb-872c-1a8a8977a614.png)

**Comment by peduarte** [comment]
This fix has now been released 🚀 

Release post: https://stitches.dev/blog/stitches-0.2.0

Thank you

---

@afzalsayed96 theme creation is slower than alpha but is significantly faster than `0.1.9`

For our priorities, it's fast enough now. But if this is causing you issues, please raise a separate issue and we'll most certainly look into it.
