### ISSUE TITLE
`className={undefined}` adds an `"undefined"` class to the DOM element

### ISSUE THREAD

**Issue by rafgraph** [modulz/stitches#537]
# Bug report

## Describe the bug

Adding `className={undefined}` to a Stitches styled component adds an `"undefined"` class to the DOM element.

## To Reproduce

Live reproduction: https://codesandbox.io/s/stitches-classname-undefined-qopjx?file=/src/App.js

## Expected behavior

`className={undefined}` should not add an `"undefined"` class to the DOM element.

## System information

`@stitches/react v0.1.4`

**Comment by peduarte** [comment]
Thanks!
