### ISSUE TITLE
`media` property on `createCss` result is undefined

### ISSUE THREAD

**Issue by kylegach** [modulz/stitches#543]
# Bug report

## Describe the bug

In this snippet (from this [sandbox](https://codesandbox.io/s/undefined-stitches-media-export-r4mk5?file=/src/App.js)), `media` is undefined:

```js
import { createCss } from "@stitches/react";

const stitches = createCss({
  media: {
    sm: "(min-width: 640px)",
    md: "(min-width: 768px)",
    lg: "(min-width: 1024px)",
    xl: "(min-width: 1280px)"
  }
});

const { media } = stitches;
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run the code in this sandbox: https://codesandbox.io/s/undefined-stitches-media-export-r4mk5?file=/src/App.js

## Expected behavior

`media` contains defined media properties and their values.

## System information

- Version of Stitches: 0.1.4

**Comment by peduarte** [comment]
That's technically "by design" 😄 

If you want to access the raw config, you can do it like this:

```jsx
import { createCss } from "@stitches/react";

const stitches = createCss({
  media: {
    sm: "(min-width: 640px)",
    md: "(min-width: 768px)",
    lg: "(min-width: 1024px)",
    xl: "(min-width: 1280px)"
  }
});

const { config } = stitches;

console.log(config.media)
```


Demo: https://codesandbox.io/s/undefined-stitches-media-export-forked-ud5p5

**Comment by kylegach** [comment]
Ahh, thanks for the clarification. That works for my needs. 👍 

However, I think the real issue may be types. If I'm understanding correctly, then `media` is a required property of the `TStyledSheet` interface, which is the return value of `ReactFactory`, which is the type assigned to `createCss`.

```ts
// /packages/core/types/index.d.ts
export interface TStyledSheet<
  // ... omitted
> {
  // ... omitted
  /** Named CSS media queries. */
  media: A
  // ... omitted
}

// /packages/react/types/index.d.ts
type ReactFactory = <Medias extends TMedias = TMedias, Theme extends TTheme = {}, Utils = {}, Prefix = '', ThemeMap extends TThemeMap = CSSPropertiesToTokenScale>(
  _config?: IConfig<Medias, Theme, Utils, Prefix, ThemeMap>,
) => TStyledSheet<Medias, Theme, Utils, Prefix, ThemeMap> & {
  // ... omitted
}

export declare const createCss: ReactFactory
```

Full source of `TStyledSheet`: https://github.com/modulz/stitches/blob/canary/packages/core/types/index.d.ts#L460

**Comment by peduarte** [comment]
@kylegach we'll be focusing on TS issues soon! 🎉
