### ISSUE TITLE
Argument types not being inferred in event handler props when composing components

### ISSUE THREAD

**Issue by jakelazaroff** [modulz/stitches#560]
# Bug report

## Describe the bug

When using composing a component that uses any of the `*HTMLAttributes` interfaces from React, TypeScript no longer infers the types of arguments to event handlers.

Weirdly, it infers correctly if you use the plain `HTMLAttributes` interface… but only if some other prop is causing an error 🥴

## To Reproduce

Reduced test case:

```typescript
import { InputHTMLAttributes } from "react";
import { createCss } from "@stitches/react";

const { styled } = createCss({});

type InputProps = InputHTMLAttributes<HTMLInputElement>;

function Input(props: InputProps) {
  return <input {...props} />;
}

const StyledInput = styled(Input, {});

export default function App() {
  // Parameter 'e' implicitly has an 'any' type. ts(7006)
  return <StyledInput onChange={(e) => console.log(e)} />;
}
```

Here's a sandbox with a more comprehensive example: https://codesandbox.io/s/dreamy-oskar-chq4z?file=/src/App.tsx

## Expected behavior

TypeScript should infer the correct type for the event handler arguments.

**Comment by jonathantneal** [comment]
This is now working in #659 —

```tsx
import { InputHTMLAttributes } from 'react'
import { createCss } from '@stitches/react'

const { styled } = createCss({})

function Input(props: InputHTMLAttributes<HTMLInputElement>) {
  return <input {...props} />
}

const StyledInput = styled(Input)

export default function App() {
  return (
    <>
      <Input onChange={(e) => console.log(e)} />
      <StyledInput onChange={(e) => console.log(e)} />
    </>
  )
}
```

<img width="740" alt="image" src="https://user-images.githubusercontent.com/188426/126393878-e10f7669-1788-4f42-8f11-835e570f42e9.png">

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
