### ISSUE TITLE
Issue composing down `as` prop

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#561]
- Stitches Alpha demo - it works: https://codesandbox.io/s/stitches-radix-as-alpha-l6jv1
- Stitches Beta demo - it fails: https://codesandbox.io/s/stitches-radix-as-beta-lyvl0

To repro: Click on the Trigger button. You should see the dropdown menu

/cc @jonathantneal @benoitgrelard @jjenzz

**Comment by jjenzz** [comment]
I believe this is a duplicate of https://github.com/modulz/stitches/issues/448

**Comment by peduarte** [comment]
Yeah! We found that later 👀
