### ISSUE TITLE
Resulting CSS from custom theme / globals does not append to head if parameters are the same

### ISSUE THREAD

**Issue by cpakken** [modulz/stitches#563]
One of the best things about stitches compared to other css-in-js solutions is that changing the theme doesn't trigger prop changes in the entire react tree.
So while developing, I experiment with different theme colors using `react-fast-refresh` and watch the app instantly update without reloading / re-mounting every single styled component. Amazing!
```jsx
const mainTheme = theme({
  colors: {
    themeBg: '$coolGray200',
    //some more theme paramemters
  }
})
const Main = () => <div className={mainTheme} ><App /></div>

```
If `themeBg` is a new value that hasn't been updated before since a reload, it works fine. The resulting css string is appended to `<head />` as expected. However if the value is changed back to something it has already apended before, then no css is appended.

For example: 
```jsx
themeBg: '$goolGray300' //works
themeBg: '$goolGray400' //works
themeBg: '$goolGray500' //works

//doesn't work, since the css string is the same as something it appended before it doesn't get appended again
themeBg: '$goolGray300' 

themeBg: '$goolGray800' //works

themeBg: '$goolGray500' //doesn't work

```
My guess is that the result from `theme({})` is being memorized every time it appends CSS to <head> and any changes that produce the same css will be ignored. After some investigation, it seems that `global({})` share the same behavior, maybe they use the same internal logic in applying the css to head

Solution: 
Memoize only the last result, so that the result from new changes gets applied.

This an issue with developer experience and probably not an issue when built. If this is not a good pattern, then is there a better way to experiment with theme styles using react-fast-refresh?

Tested in @stitches/react v0.1.7 and v0.1.6

**Comment by peduarte** [comment]
Very interesting! Thanks for raising this. Let's see what we can do to improve the DX here.

**Comment by cpakken** [comment]
I solved it! This only occurs if a classname is specified when creating the theme
```jsx
//Works fine!
const mainTheme = theme({
  colors: {
    themeBg: '$coolGray200',
    //some more theme paramemters
  }
})

//Changing themeBg back to something it has already been set to doesn't work
const mainTheme = theme('primary', {
  colors: {
    themeBg: '$coolGray200',
    //some more theme paramemters
  }
})

```
The css is probably memoized with a specific class name. If this is not set, the css string appends correctly to a different class name. 

Still, is preventing css from appending when a class name is set the desired behavior??

**Comment by cpakken** [comment]
Here is the starter repo to test the react-fast-refresh behavior
https://github.com/cpakken/stitches-custom-theme-refresh

**Comment by peduarte** [comment]
This fix has now been released 🚀 

Release post: https://stitches.dev/blog/stitches-0.2.0

Thank you
