### ISSUE TITLE
global() should take a custom theme as a parameter to apply theme tokens

### ISSUE THREAD

**Issue by cpakken** [modulz/stitches#565]
```jsx
//Currently if we use a token in global
const styles = global({ body: { backgroundColor: '$themeBg' } })

//and apply a new theme
const darkTheme = theme({ colors: { themeBg: '$darkColor' } })

const Main = () => {
  //$themeBg does not get applied here
  styles()
  return (
    // dark theme only applies in <App />
    <div className={darkTheme}>
      <App />
    </div>
  )
}
```
```jsx

//Solution
const Main = () => {
  //global styles takes in theme as parameter and applies $themeBg in styles
  styles(darkTheme)
  return (
    <div className={darkTheme}>
      <App />
    </div>
  )
}

```

**Comment by peduarte** [comment]
Themes are available in the global css function the same way they're available every else - by providing the theme to the `createCss` creator. https://stitches.dev/docs/installation#configure-stitches

**Comment by cpakken** [comment]
Thanks for responding.

Sorry, I don't think I was clear in describing my use case. In my example, `themeBg` is initialized using `createCss`.

```jsx
export const { theme, global } = createCss({
  theme: {
    colors: {
      //color palette
      dark: '#33333',
      light: '#99999',

     //theme colors
      themeBg: '$light',
    },
  },
})

const globalStyles = global({ body: { backgroundColor: '$themeBg' } })

const dark = theme({ colors: { themeBg: '$dark' } })
```
As you can see, using the default theme, the `body: { backgroundColor: '$themeBg' }` which is `$light`.
When I apply `dark` theme to change `themeBg: '$dark'`, all components using the `$themeBg` color will change accordingly **_except_** for global styles.

Is there a pattern I can use to apply the modified theme tokens in global styles? Or is this even a good way to approach this? 

And to clarify theme tokens like in `const dark = theme({ colors: { themeBg: '$dark' } })` not `createCss({theme: {...}})`

**Comment by peduarte** [comment]
@cpakken oh, I see. Do you have a codesandbox for this?

The only reason I can think of is that the `dark` theme class isn't being added high up enough in the DOM. 

For example, if you're changing the `body` you need to ensure the theme class is either on the `body` element or any of its parent - in this case the `html`

**Comment by cpakken** [comment]
@peduarte Thanks for your feedback. Adding the theme to `html` works like a charm.

**Comment by peduarte** [comment]
Lovely.
