### ISSUE TITLE
`styled(React.memo(MyComp), {})` removes the memoization

### ISSUE THREAD

**Issue by rafgraph** [modulz/stitches#568]
# Bug report

## Describe the bug

`styled(React.memo(MyComp), {})` removes the memoization. `MyComp` is rendered as though it is not memoized.

On a semi-related note, `key="undefined"` is showing up in React dev tools on every component that is wrapped in `styled`. I don't think this is material for performance, but it's an easy fix, ~~just add `key: null` to the React element object [here](https://github.com/modulz/stitches/blob/canary/packages/react/src/index.js#L36)~~ PR [here](https://github.com/modulz/stitches/pull/569).

## To Reproduce

https://codesandbox.io/s/stitches-react-memo-bug-s044r?file=/src/App.js

## Expected behavior

A memoized component to be rendered.

## Screenshots

<img width="869" alt="Screen Shot 2021-04-18 at 11 07 00 PM" src="https://user-images.githubusercontent.com/11911299/115177870-19058080-a09e-11eb-9dc9-42818b066a50.png">

## System information

- Version of Stitches: `0.1.7`

**Comment by jonathantneal** [comment]
This is working, tested in 0.2.2.

https://codesandbox.io/s/stitches-react-memo-bug-forked-p2it8?file=/src/stitches.config.js
