### ISSUE TITLE
typescript build issue

### ISSUE THREAD

**Issue by stefanobrambilla** [modulz/stitches#575]
hi all,
thanks very much for all contributors.

i have a issue:
i Use Nextjs in typescript and when i build i have this error:

./node_modules/@stitches/core/types/index.d.ts:279:6
Type error: Type expected.

 `$${Extract<keyof Theme[ThemeMap[k]], string | number>}`

is this a bug ?

**Comment by peduarte** [comment]
Which version of typescript do you have?

**Comment by stefanobrambilla** [comment]
hi @peduarte.

i use typescript 4.3.0

**Comment by peduarte** [comment]
That's odd. Should with with typescript 4.1+

Out curiosity would you mind deleting node_modules and installing again, then building?

**Comment by stefanobrambilla** [comment]
hi @peduarte 

with typescript 4.1+ solve this issue. 👏👏👏 🙌

thanks.

Stefano
