### ISSUE TITLE
`key="undefined"` added to elements created by Stitches, and "rendered by" list missing in dev tools

### ISSUE THREAD

**Issue by rafgraph** [modulz/stitches#579]
# Bug report

## Describe the bug

`key="undefined"` is added to elements created by Stitches, and the "rendered by" list is missing in React dev tools.

## To Reproduce

Inspect React dev tools on a site using Stitches. The "rendered by" list will only show up when using a development build of React.

## Expected behavior

There should be no `key` value set on elements created by Stitches (key should be `null` on the element object), and the "rendered by" list should show the component render stack.

## Screenshots

<img width="1285" alt="Stitches" src="https://user-images.githubusercontent.com/11911299/115828130-470afd80-a3db-11eb-97a9-f4aea60b3418.png">

## System information

Stitches `0.1.7`

**Comment by jonathantneal** [comment]
This is likely fixed in 0.2.x, but feel free to comment if you can share the repo, and the key is still undefined.
