### ISSUE TITLE
Props is not being passed forward when using composition

### ISSUE THREAD

**Issue by franklinjavier** [modulz/stitches#583]
# Bug report
## Describe the bug
I'm trying to pass a prop from one component to another using composition, but apparently the prop is not being passed.

## To Reproduce
Heading 1 should render with $brand-1 color. The same with Heading 2 with $brand-2 color
https://codesandbox.io/s/flora-forked-c2l50?file=/src/App.tsx

In the Text component, I added a console.log to line 20. This log is not being triggered, btw.

## System information

- macOS
- Browser Chrome
- Version of Stitches: 0.1.9

## More details
If I remove the comments of these lines, it works, but it would be better to use the power of composition instead https://codesandbox.io/s/flora-forked-c2l50?file=/src/components/Heading.tsx:471-564

**Comment by rafgraph** [comment]
I think this is because the `as` prop in `<Heading>` is replacing the `<Text>` component, so `<Text>` is never rendered. Similar to #448

**Comment by franklinjavier** [comment]
I've tried another way to reproduce the issue -> https://codesandbox.io/s/blue-platform-66snm?file=/src/App.js

**Comment by peduarte** [comment]
Thanks for this. It certainly is an issue. We'll address this once we're done with performance work and typescript. Probably ~4 weeks from now.

**Comment by smhutch** [comment]
I believe this is an example of the issue outlined in #488, my team also encountered this issue. We had to create internal documentation highlighting this "gotcha", and typically avoid passing a component to `styled`.

In case it clarifies the issue, our internal documentation is:

> # Issues with using `styled(Component)`

> There are a couple of issues with styling elements this way.

> 1. Passing a React component to `styled` will only work if the component passed down accepts a `className` prop. If it doesn't, the styles will not be applied. [Sandbox](https://codesandbox.io/s/styledcomponent-dgmyb).
> 2. The `as` prop can cause unexpected behaviour when using `styled(Component)`. This prop overrides the rendered DOM node, but as a side-effect, it also loses reference to the original `Component` which was `styled`. This [sandbox](https://codesandbox.io/s/the-as-prop-f7um6?file=/src/App.tsx) illustrates the issue. There is also an [open issue](https://github.com/modulz/stitches/issues/448) about it, which the Modulz team have acknowledged.

**Comment by peduarte** [comment]
Fixed. Will be out in next release 
![Uploading image.png…]()

**Comment by franklinjavier** [comment]
AH MULEKE!

**Comment by franklinjavier** [comment]
@peduarte 0.2.0?

**Comment by peduarte** [comment]
@franklinjavier yeahm, it'll be `0.2.0` - release prob next week.

**Comment by franklinjavier** [comment]
Hey @peduarte
I created another sandbox pointing to 0.2.0, but didn't work. Yeah i know, i'm a little anxious 🥺

Maybe, it will help you to test https://codesandbox.io/s/stitches-ci-cra-forked-g1jp3?file=/package.json:188-282

Would you mind sharing your demo?

**Comment by franklinjavier** [comment]
Another point, it seems that it is swallowing the props 
![image](https://user-images.githubusercontent.com/440220/119745809-47c50280-be65-11eb-88a9-0e382c9b00d0.png)

**Comment by peduarte** [comment]
@franklinjavier that would be because there is no `0.2.0`, it hasn't been [released](https://www.npmjs.com/package/@stitches/react) yet :)

**Comment by franklinjavier** [comment]
I know, I'm referring about this

```json
  "dependencies": {
    "@stitches/react": "https://pkg.csb.dev/modulz/stitches/commit/b11739b0/@stitches/react",

```

**Comment by peduarte** [comment]
@franklinjavier Hmm. I used the sandbox you [created here](https://github.com/modulz/stitches/issues/583#issuecomment-825929969)

Here's the forked sandbox with it working: https://codesandbox.io/s/hungry-brook-qk9uc?file=/package.json

**Comment by peduarte** [comment]
@franklinjavier looking at your latest sandbox though, I can see the issue still remains. Thanks for that, it was a bit of a mix up of sandboxes 😅

**Comment by peduarte** [comment]
@franklinjavier Ok, after some more digging, it turns out that even your last sandbox is working as expected

- This is the sandbox you provided https://codesandbox.io/s/stitches-ci-cra-forked-g1jp3?file=/package.json:188-282
- This is the forked sandbox working as expected https://codesandbox.io/s/stitches-ci-cra-forked-4v695?file=/src/App.jsx

In your sandbox, you're not mapping the `color` prop to the CSS `color` property. So it'll never get applied. 

![image](https://user-images.githubusercontent.com/372831/119825928-c8344380-bef7-11eb-859d-551990580f61.png)


Am I missing something?

**Comment by kylemh** [comment]
He's spreading props on L27, no?

**Comment by franklinjavier** [comment]
Pedro, I'm extending Text component and this component is the responsible for getting the color props and put inside css prop. Makes sense?

**Comment by peduarte** [comment]
@franklinjavier Hmm, I'm not following. Can you provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) please?

I know there're a few examples, but they have too many abstractions and files and that can be distracting. 

Without it, all I can tell is that the sandbox and screenshot from my [previous comment](https://github.com/modulz/stitches/issues/583#issuecomment-849590762) seem to make sense and behave as expected.

**Comment by peduarte** [comment]
Im not convinced it's a bug, though. There are multiple layers of composition. Some happening in Stitches via the styled function, some happening via `as` prop, and some via React Component wrappers. 

It feels to me that it's more of an architectural issue. The moment you wrap `StyledHeading` in `Heading`, you're out of Stitches composition logic. So you need to manually map the `color` prop to the CSS. 

Im not sure what we can do about this, but once our top priority issues are out of the way we can dedicate some time to explore this further

**Comment by jonathantneal** [comment]
@peduarte is correct. We wouldn't be able to "fix" this, and if we decided to revisit how it is architected, we would need to think thru how we would want to change the way things work.
