### ISSUE TITLE
`backdropFilter` doesn't transform locally-scoped tokens in css()

### ISSUE THREAD

**Issue by joe-bell** [modulz/stitches#588]
# Bug report

## Describe the bug

I recently hit a little snag upgrading [joebell.co.uk](https://joebell.co.uk) to `@stitches/react@0.1.9`, where my use of locally-scoped tokens with `backdropFilter` suddenly broke. I was a few versions behind, so I'm unable to pinpoint the exact moment this may have happened

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://codesandbox.io/s/stitches-ci-issue-repro-backdrop-filter-q1uyq?file=/src/App.tsx
2. Click on `App.tsx` and see the `header()` style
3. Open the preview pane and scroll
4. Open dev tools to see that `$$blur` is not transformed to `var(---blur)`

## Expected behavior

`$$blur` should be transformed to `var(---blur)`

## Screenshots

<img width="562" alt="Screenshot 2021-04-30 at 10 12 32" src="https://user-images.githubusercontent.com/7349341/116661109-9c777980-a99c-11eb-93d5-c17bbd4fa081.png">

## System information

N/A

## Additional context

Weirdly, this issue **doesn't** occur with `styled()`, only `css()`

**Comment by jonathantneal** [comment]
Hi @joe-bell! I’m still working through this issue, but I’m going to share some notes to confirm what’s going on.

This is a bug in our CSS stringifier. Specifically, the issue in the **replacer** function of the stringifier. The replacer function intercepts object properties & values from CSS-in-JS and lets us change them before they are turned into CSS strings. We use it to power `utils` and polyfills.

We can recreate the bug like this:

```js
css({ backdropFilter: '$$blur' })
```

That generates the following CSS:

```css
.sx104uf {
  -webkit-backdrop-filter: var(---blur);
  backdrop-filter: $$blur;
}
```

↑ Note the untransformed `$$blur`.

Inspecting the replacer function, I can see that it intercepts the CSS object like this:

> Stringifying!
> I found a thing, .sx104uf. — (_this is the generated class name_).
> I found a thing, backdrop-filter. — (_this is when the auto-prefix-ing will step in_)
> I found a thing, -webkit-backdrop-filter. — (_this is our generated property_)
> I found a thing, -webkit-backdrop-filter. — (_this is our generated property, again_)
> Done. — (_it never re-encounters the backdrop-filter property_)

**Comment by joe-bell** [comment]
Thanks @jonathantneal, really appreciate you taking the time to explain what's going on behind the scenes here!

**Comment by peduarte** [comment]
This fix has now been released 🚀 

Release post: https://stitches.dev/blog/stitches-0.2.0

Thank you
