### ISSUE TITLE
`themeMap` in config is confusing

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#598]
I've received various reports of people saying that their tokens are not working, only to find out they're passing an empty `themeMap` to the config. 

This happens because the docs is unclear. 

But I also think that passing an empty object shouldn't just clear the mapping. 

Raising this so we can track it.

**Comment by jonathantneal** [comment]
FWIW, you’ve added a section here for this with some content — https://stitches.dev/docs/api#defaultthememap

**Comment by csantos1113** [comment]
Wondering if themeMap should be merged with defaultThemeMap automatically behind the scenes, so we don't have to deal/remember to import and merge the defaultThemeMap object?

**Comment by peduarte** [comment]
Yeah, I think it's better with the updated docs 👍 

@csantos1113 We considered that, but we also want to offer users the ability to remove the mapping completely, in which case, doing `{}` works. 

Thanks for the suggestion though!
