### ISSUE TITLE
Attaching additional props

### ISSUE THREAD

**Issue by MatejBransky** [modulz/stitches#599]
**Is your feature request related to a problem? Please describe.**

It's a little bit uncomfortable to create wrapper for my styled component which just sets `as` prop.

```tsx
import React from "react";
import { styled } from "@stitches/react";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import type * as Polymorphic from "@radix-ui/react-polymorphic";
import { Button } from "./Button";

const StyledSplitButtonArrow = styled(DropdownMenu.Trigger, {
  /** extending button styles */
});

export const SplitButtonArrow = React.forwardRef((props, forwardedRef) => {
  return <StyledSplitButtonArrow as={Button} {...props} ref={forwardedRef} />;
}) as Polymorphic.ForwardRefComponent<
  DropdownMenu.DropdownMenuTriggerPrimitive,
  {}
>;
```

**Describe the solution you'd like**

It would be great to attach additional props like with `styled-components` (https://styled-components.com/docs/basics#attaching-additional-props):

```tsx
import { styled } from "@stitches/react";
import * as DropdownMenu from "@radix-ui/react-dropdown-menu";
import { Button } from "./Button";

const SplitButtonArrow = styled(DropdownMenu.Trigger, {
  /** extending button styles */
}, { as: Button });
```

**Describe alternatives you've considered**

Wrapper around styled component.

**Additional context**

I work on SplitButton (https://www.nngroup.com/articles/split-buttons/).

**Comment by jonathantneal** [comment]
Hey... I’ll be the bearer of some unpopular news here. We’ve decided not to allow attaching any props to components. See https://github.com/modulz/stitches/issues/688
