### ISSUE TITLE
Issue with NextJS Link and components modified with `as`

### ISSUE THREAD

**Issue by aequasi** [modulz/stitches#600]
I am having an issue with next/link and stitches, in this example:

```ts
const Button = styled('button', {});

export default function IndexPage() {
    return <Link href="/browse"><Button as="a">Browse</Button></Link>;
};
```

In this case, the dom has the `a` element, as expected, but it doesn't have the `/browse` href on it, as expected.

**Comment by VaibhavAcharya** [comment]
The `Link` component sees the child as `button` and not `a` that's why it does not pass href to its child.
You will have to specify `passHref` as true.

Like this :
```
<Link href="/url" passHref={true}>
  ...
</Link>
```

**Comment by aequasi** [comment]
Derp. Thanks!
