### ISSUE TITLE
TypeScript: Typing of `util` errors inside variants

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#602]
Repro: https://codesandbox.io/s/busy-shape-big4n?file=/src/App.tsx

Notice how `small` is throwing an error when using a util.

![image](https://user-images.githubusercontent.com/372831/119519706-f0963380-bd79-11eb-9b37-024a6e8d3634.png)

**Comment by peduarte** [comment]
@jonathantneal Still not working

```tsx
utils: {
    size: (value: Array<Stitches.PropertyValue<'width'>>) => ({
      width: value[0],
      height: value[1] || value[0],
    }),
}
```

then:

```Box
const Bar = styled('div', {
  backgroundColor: 'red',
  size: [10, '40px'],
  variants: {
    size: {
      small: {
        size: [10, '100px'],
      },
    },
  },
});
```

![CleanShot 2021-07-15 at 19 00 41@2x](https://user-images.githubusercontent.com/372831/125827825-b850bd00-4521-4861-a069-ab54a9a1c415.jpg)

**Comment by jonathantneal** [comment]
This should be working in #659 —

```tsx
import * as Stitches from '@stitches/react'
import { createCss } from '@stitches/react'


const { styled } = createCss({
  utils: {
    size: (value: Stitches.PropertyValue<'width'>[]) => ({
      width: value[0],
      height: value[1] || value[0],
    }),
  }
})

const Bar = styled('div', {
  backgroundColor: 'red',
  size: [''],
  variants: {
    size: {
      small: {
        size: [10, '100px'],
      },
    },
  },
})
```


<img width="1340" alt="screenshot of the above code before offering suggestions" src="https://user-images.githubusercontent.com/188426/126378916-318eee11-ef83-418d-b7fd-2a63d5e91766.png">


<img width="1340" alt="screenshot of the above code upon offering suggestions" src="https://user-images.githubusercontent.com/188426/126378834-d58c36e7-a2a7-4e91-829a-bf7cb5bc6375.png">

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
