### ISSUE TITLE
Add custom string to className

### ISSUE THREAD

**Issue by liajoy** [modulz/stitches#605]
**Is your feature request related to a problem? Please describe.**
It will be helpful when debug if developer can add custom information to className. For example, developer can add some semantic words `.xxx-footer`, so that `footer` can easily refer in code.

**Describe the solution you'd like**
Maybe add a new property to `css` API. `label` is the name [emotion](https://emotion.sh/docs/labels) used. Like this:
```
const clsFooter = css({
  // ...some styles
 label: 'footer'
})()

clsFooter // outputs .xxx-footer
```

**Comment by peduarte** [comment]
Hi! :) 

We have a discussion for this https://github.com/modulz/stitches/discussions/482

Still under consideration. Thanks! 👍

**Comment by liajoy** [comment]
> Hi! :)
> 
> We have a discussion for this #482
> 
> Still under consideration. Thanks! 👍

Hi! I have read that discussion. That discussion is talking about adding extra classNames to the component. But I think this issue is not the same thing. The feature I request is make the className readable, it just add some suffix to the className.
