### ISSUE TITLE
Intermittent TypeScript Error for HTML Children

### ISSUE THREAD

**Issue by joe-bell** [modulz/stitches#607]
# Bug report

## Describe the bug

I've recently hit an intermittent bug with some Stitches components (only some, and I really can't figure out why) throw a TypeScript error when the children contains HTML

```tsx
const StatusGroupTitle = styled("p", { color: "$blue400" });

export const StatusGroup = (props) => (
  <React.Fragment>
    <StatusGroupTitle>
      <span>TypeScript doesn't like me</span>
      {/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        No overload matches this call.
          Overload 1 of 3, '(props: VariantsCall<any, TMedias & { initial: ""; }> & { as: "p"; } & Omit<DetailedHTMLProps<HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, string | ... 1 more ... | symbol> & { ...; }): Element', gave the following error.
            Type 'Element' is not assignable to type 'string | number | symbol | `${number}` | { [x: string]: string | number | symbol | `${number}`; initial?: string | number | symbol | `${number}`; }'.
              Type 'Element' is not assignable to type '{ [x: string]: string | number | symbol | `${number}`; initial?: string | number | symbol | `${number}`; }'.
                Index signature is missing in type 'Element'.
          Overload 2 of 3, '(props: VariantsCall<any, TMedias & { initial: ""; }> & { as?: never; } & Omit<never, string | number | symbol> & { css?: InternalCSS<TMedias & { initial: ""; }, { ...; }, { ...; }, CSSPropertiesToTokenScale>; }): Element', gave the following error.
            Type 'Element' is not assignable to type 'string | number | symbol | `${number}` | { [x: string]: string | number | symbol | `${number}`; initial?: string | number | symbol | `${number}`; }'.
          Overload 3 of 3, '(props: Omit<Pick<DetailedHTMLProps<HTMLAttributes<HTMLParagraphElement>, HTMLParagraphElement>, "key" | keyof HTMLAttributes<...>> & { ...; }, string | ... 1 more ... | symbol> & { ...; } & VariantsCall<...>): ReactElement<...>', gave the following error.
            Type 'Element' is not assignable to type 'string | number | symbol | `${number}` | { [x: string]: string | number | symbol | `${number}`; initial?: string | number | symbol | `${number}`; }'.ts(2769)
       */}
    </StatusGroupTitle>
  </React.Fragment>
);
```

## To Reproduce

I've spent a few hours trying to reproduce this with no luck as it seems to be behaving inconsistently, I've tried. I discussed briefly with @peduarte who mentioned he'd also seen the same intermittent behaviour.

At first I wondered if it was only when `styled` was consumed as an export of another `package` (e.g. modulz design-system), but I've been unable to recreate in a minimal reproduction.

## Expected behavior

Stitches components should allow HTML within the without throwing a TypeScript error

## Screenshots

N/A

## System information

- OS: [e.g. macOS, Windows] macOS
- Browser (if applies) [e.g. chrome, safari] N/A
- Version of Stitches: [e.g. 0.0.2] 0.1.9
- Version of Node.js: [e.g. 10.10.0] 14.16.0

**Comment by peduarte** [comment]
I do remember seeing this at least once in the past, but still not been able to create a stable, reproducible example :(

**Comment by joe-bell** [comment]
It's not really a "minimal" reproduction but I have managed to recreate it!
(in our project: https://github.com/orchest/orchest/pull/275)

1. Clone `orchest`
    ```sh
    git clone git@github.com:orchest/orchest.git
    ```
2. Run `pnpm i` (you may need to run `npm i pnpm -g` first)
3. Build the design system package in `lib/design-system/package`
    ```sh
    pnpm run build --filter '@orchest/design-system...'
    ```
4. Visit `services/orchest-webserver/client/src/components/Example.jsx`.   
_an example component inside a Vite project (that consumes the design-system package)_
5. See the error on line 8 (inside VSCode)

---

You won't be able to run the project locally without additional steps, but it should allow you to recreate the TypeScript issue

**Comment by joe-bell** [comment]
After some further investigation, it seems that the culprit was `declaration: true` in my consumer's `tsconfig.json` (which didn't need to output types anyway)

This issue might be a little problematic for consumers creating libraries that require `declaration: true`, but it's not a concern for us anymore!

Happy to leave it up to you whether or not to keep the issue open

**Comment by peduarte** [comment]
Thanks Joe. Doesn't seem to be an issue to many people, so I'll close and see how it goes. Thanks!
