### ISSUE TITLE
defaultThemeMap not exported anymore

### ISSUE THREAD

**Issue by mntnoe** [modulz/stitches#615]
When trying out 0.2.0-canary.2, it seems `defaultThemeMap` is not exported from @stitches/core and @stitches/react.

It is still used as a falback when `themeMap` is not given in the config in `createCss`, however.

**Comment by peduarte** [comment]
Thanks@

**Comment by jonathantneal** [comment]
Thanks for bringing this to our attention, @mntnoe. The export was reintroduced in v0.2.0-canary.6 (and, at the time of this writing the current canary is v0.2.0-canary.7).
