### ISSUE TITLE
Support or document CSS fallback property usage

### ISSUE THREAD

**Issue by mntnoe** [modulz/stitches#616]
**Is your feature request related to a problem? Please describe.**

We still need to use CSS fallback properties from time to time, even on modern browsers, for instance:

    min-height: 100vh;
    min-height: -webkit-fill-available;

It doesn't look like this is currently supported in Stitches, at least I couldn't find any documentation on it.

**Describe the solution you'd like**

Emotion and free-style use arrays to express this:

    minHeight: [
      '100vh',
      '-webkit-fill-available'
    ]

**Comment by peduarte** [comment]
You can rely on `utils` for this. Example: https://codesandbox.io/s/gifted-brown-9wfqb?file=/src/stitches.config.ts:94-295

![image](https://user-images.githubusercontent.com/372831/121024289-5f28b780-c7a4-11eb-8d5b-2a1a248917f3.png)

**Comment by mntnoe** [comment]
Thanks for the workaround! I will use this for now, and understand that adding support may complicate typings even more. I hope to see support for this added at some point, though.
