### ISSUE TITLE
Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules

### ISSUE THREAD

**Issue by jeiea** [modulz/stitches#617]
# Bug report

## Describe the bug

I have a userscript using stitches. On some site `createCss` throws the above error at [this](https://github.com/modulz/stitches/blob/b053352f6647588e7a145b1077eb69dee0f0fd92/packages/core/src/createSheet.js#L37).

## To Reproduce

If it is necessary I should spend more time for reproducible example. If the error is unreachable situation please request to me.

## Expected behavior

`createCss` is initilization function. It should not fail.

## System information

- OS: windows 10
- Browser: Google Chrome 91.0.4472.77 (Official Build) (64-bit)
- Version of Stitches: 0.2.0-canary.2

## Additional context

0.0.3-canary.4 does not have this problem.

**Comment by peduarte** [comment]
Hi! Can you provide some more information? Either a reproducible example or code snippets. Thanks

**Comment by jeiea** [comment]
[codesandbox](https://codesandbox.io/s/stitchesreport-ulokn)
I thought it would be hard to reproduce at first but it wasn't.

**Comment by peduarte** [comment]
@jeiea brilliant! 

I suppose this is happening because there's no config being passed in. If this is blocking you currently, you can import `styled` and other functions directly https://stitches.dev/docs/installation#import-it

cc @jonathantneal

**Comment by jemmyphan** [comment]
In my case, the issue occurred even when there is a config.
[example](https://codesandbox.io/s/stitchesreport-forked-zmfj7)

**Comment by peduarte** [comment]
@jemmyphan thanks!

Seems to only happen when importing from `@stitches/core`. It works from with `@stitches/react`

/cc @jonathantneal

**Comment by peduarte** [comment]
Fixed in `0.2.0-canary.4` 
https://codesandbox.io/s/stitchesreport-forked-mt2bh?file=/package.json
