### ISSUE TITLE
TS: Array syntax scales producing type errors inside createStyled 

### ISSUE THREAD

**Issue by hadihallak** [modulz/stitches#62]
Not sure if this is intended but if we're following the [theme UI spec](https://theme-ui.com/theme-spec/#font-sizes-typographic-scale) then we should probably support them too as they work correctly aside from the typing errors

**Full error:** 
```js
/Users/hadihallak/cra-ts/src/App.tsx
TypeScript error in /Users/hadihallak/cra-ts/src/App.tsx(7,3):
Type '{ fontSizes: string[]; }' is not assignable to type 'ITokensDefinition'.
  Types of property 'fontSizes' are incompatible.
    Type 'string[]' is not assignable to type 'ITokenDefinition'.
      Index signature is missing in type 'string[]'.  TS2322

     5 | 
     6 | export const { styled, css } = createStyled({
  >  7 |   tokens: {
       |   ^
     8 |     fontSizes: ['1px', '2px', '3px']
     9 |   },
    10 | })
```

**Relevant packages:**
```
    "@stitches/styled": "^8.0.2",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "typescript": "~3.7.2"
```

**Can be reproduced with the following code ina  CRA TS app:**

```tsx
import React from 'react'

import { createStyled } from '@stitches/styled'


export const { styled, css } = createStyled({
  tokens: {
    fontSizes: ['1px', '2px', '3px']
  },
})

const Box = styled.div({})

function App() {
  return (
    <div className="App">
      <Box> Hello world </Box>
    </div>
  )
}

export default App

```

**Comment by peduarte** [comment]
@hadihallak are you referring to supporting array values?

**Comment by hadihallak** [comment]
it's just typescript errors. the syntax itself is supported in normal js

**Comment by peduarte** [comment]
Yeah I get that it's typescript, but should we support array values at all?

How would we type the array? Would we use the index?

Eg:
```js
// scale
space: [0, '5px', '10px']

css({
  margin: 2, // here I expect TS to give me the options 0 | 1 | 2
})
```

**Comment by peduarte** [comment]
@hadihallak you think we still need this? Im happy to close and document that we only support objects

**Comment by peduarte** [comment]
@hadihallak whats the deal with this one?

**Comment by hadihallak** [comment]
> happy to close and document that we only support objects

Yeah, in this case, we can close it 👍
