### ISSUE TITLE
Can't set new default variants when composing components

### ISSUE THREAD

**Issue by effectiveduck** [modulz/stitches#622]
# Bug report

## Describe the bug

When trying to set new default variants for a composed component it uses the original default variants instead of the new ones.

## To Reproduce

```jsx
const BaseButton = styled("button", {
  variants: {
    variant: {
      x: {},
      y: {},
      z: {},
    }
  },
  defaultVariants: {
    variant: "x"
  }
)

const CustomZButton = styled(BaseButton, {
  ...,
  defaultVariants: {
    variant: "z",
  }
})
```

## Expected behavior

CustomZButton would have variant="z" by default, instead it has variant="x"

## System information

- OS: macOS
- Browser: chrome 91
- Version of Stitches: 0.1.9
- Version of Node.js: 16.2.0

**Comment by peduarte** [comment]
Thanks for raising this. We're aware of it, and will work on a fix! Thanks again

**Comment by peduarte** [comment]
This will be fixed when we release `0.2.0` - currently in canary. 

Demo https://codesandbox.io/s/nostalgic-montalcini-5ewk3?file=/src/App.tsx

**Comment by peduarte** [comment]
This fix has now been released 🚀 

Release post: https://stitches.dev/blog/stitches-0.2.0

Thank you

**Comment by weslleyaraujo** [comment]
Hi @peduarte!

I was trying out something like this: https://codesandbox.io/s/heuristic-wu-8uhte?file=/src/App.tsx
it looks like we lost the type definitions for `defaultVariants` when composing components with variants

Tried on version `0.2.2`, not sure if this is expected? 🤔

**Comment by peduarte** [comment]
@weslleyaraujo not expected, but not surprising either 😄 We're re-doing the whole typescript layer at the moment, so all ts-related issues will be fixed soon. Thanks
