### ISSUE TITLE
Theming issue in v0.2.0

### ISSUE THREAD

**Issue by sandgraham** [modulz/stitches#627]
# Bug report

## Describe the bug

After updating to v0.2.0 my dark theme stopped working. It looks like applying the class returned from calling `theme()` (as returned by `createCss`) does not set CSS variables properly.

## To Reproduce

https://codesandbox.io/s/spring-paper-zhwgb?file=/src/App.js

## Expected behavior

Expect applying the class name for an alternate theme to set CSS variables.

## System information

- OS: macOS
- Browser: Chrome
- Version of Stitches: v0.2.0

## Additional context

Theming works in 0.1.9 ([codesandbox](https://codesandbox.io/s/async-sun-7gvy2))

**Comment by peduarte** [comment]
This is how you apply the theme https://stitches.dev/docs/theming#apply-the-theme

You don't need `.className` - that was an old internal (undocumented) API 😄 

Demo: https://codesandbox.io/s/serene-nobel-368nd?file=/src/App.js

**Comment by sandgraham** [comment]
Oh whoops - can [confirm](https://codesandbox.io/s/twilight-mountain-e9pvd?file=/src/App.js) this works (as documented 😅). I must have seen `className` come up in type autocompletion and assumed that was "the way".
