### ISSUE TITLE
Should base rules override inherited base variants?

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#629]
Initially raised by @vladmoroz, I'd like to open up an issue to discuss how specificity war should work between default variants, and base rules, when composing a stitches component. 

The most minimal example I could come up with is:
```jsx
const BlueBox = styled("div", {
  variants: {
    color: {
      blue: {
        color: "blue"
      }
    }
  },
  defaultVariants: {
    color: "blue"
  }
});

// This composes `BlueBox` and adds a base rule 
const RedBox = styled(BlueBox, {
  color: "red"
});
```

Currently, the `RedBox` gets rendered as `blue`. Because its still using the `defaultVariant` inherited from `BlueBox`.

Although I can understand why this happens, I think its confusing. One way to get around this, is by extending the `color` variant in `RedBox` and overriding the `defaultVariant` there. But seems like a confusing workflow.

Could base rules override inherited default variants?

Repro: https://codesandbox.io/s/mutable-silence-9kip8?file=/src/App.tsx:43-345

**Comment by vladmoroz** [comment]
On the second thought, I think it's just as confusing with non-default variants too:
https://codesandbox.io/s/elated-waterfall-1we9b?file=/src/App.tsx

My expectation was that when composing a new component, the composed component would override any style supplied by the base component, be it a default variant or not.

**Comment by peduarte** [comment]
After a while of thinking about this, and chatting over it with Jonathan, we've come to the conclusion that this works as expected. 

Base rules, regardless of where they are in the composition tree, shouldn't override variants.

I appreciate this may seem unintuitive at first, but I believe that it will help prevent lots of errors and force users to think more carefully about where styles go. The Stitches API was designed to help with these type of "states".

Given all of the above, @vladmoroz this is how I'd approach your sandbox https://codesandbox.io/s/priceless-fog-2hn77?file=/src/App.tsx

One way to think about this is, once you start relying on variants to set styles, you must continue using variants to override them. 

Anyway, I'll close this issue as this isn't a bug, it's by design, and after chatting to Jonathan there isn't much we can do about this from an architectural point of view. 

Thanks!

**Comment by colmtuite** [comment]
Adding this to the discussion here
https://github.com/radix-ui/generator/blob/4659aa19a20addd538c64d40b1a63adb368c3ad5/packages/app/generatables/styles/shared/Label.tsx#L11

I've been caught out a few times by this API design, it seems unintuitive to me.

> My expectation was that when composing a new component, the composed component would override any style supplied by the base component, be it a default variant or not.

This suggestion seems to make the most sense.

Any rules I declare on a composed component should win.

**Comment by peduarte** [comment]
@colmtuite I've been thinking about this for a while, and I'm not convinced it's a bug, hence why the issue was closed.

Let's think about the problem in a different way. Take the following code:

```jsx
// 1. Create a Text component
//    - with a `color: red` variant
const Text = styled('p', {
  variants: {
    color: {
      red: { color: 'red' }
    }
  }
})

// 2. Create a Label component
//   - set a base color
const Text = styled('label', {
  color: 'blue'
});

// 3. Render time
() => <>
  <Text>Text with no variants - system color</Text>
  <Text color="red">Text with color red variant - it's red!</Text>
  <Text as={Label}>Text as Label - it's blue!</Text>
  <Text as={Label} color="red">Text as Label with color red variant - what color should this be?</Text>
</>
```

What color would you expect the last example to be?

/cc @vladmoroz

**Comment by colmtuite** [comment]
Is this identical to doing

```
const Label = styled(Text, {
  color: 'blue'
});
```

?

**Comment by vladmoroz** [comment]
@peduarte thanks for picking it up again. What do you figure about this example?

```jsx
const Text = styled("span", {
  variants: {
    size: {
      1: {
        fontSize: "12px",
        lineHeight: "16px",
      },
      2: {
        fontSize: "14px",
        lineHeight: "18px",
      },
      3: {
        fontSize: "18px",
        lineHeight: "24px",
      },
    }
  }
});

const SingleLineText = styled(Text, {
  lineHeight: "1",
  whiteSpace: "nowrap"
});

function App () {
  // What line height shall we get?
  return <SingleLineText size="3">Hello world</SingleLineText>
}
```

Same issue as I created with the TransparentButton composition https://codesandbox.io/s/elated-waterfall-1we9b?file=/src/App.tsx

Are you still thinking that the style precedence would be, from lowest to highest:
- Base component base styles
- Composed component base styles
- Base component variants
- Composed component variants

Or would it be:
- Base component base styles
- Base component variants
- Composed component base styles
- Composed component variants

/cc @colmtuite
