### ISSUE TITLE
Missing @initial breakpoint

### ISSUE THREAD

**Issue by yosafatkesuma** [modulz/stitches#634]
# Bug report

## Describe the bug

When i try to use '@initial' breakpoints, i got this error
 
Chrome: Failed to execute 'insertRule' on 'CSSGroupingRule': the rule '@initial{.c-KkSIT{color:red}}' is invalid and cannot be parsed.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Define a theme
```
import { createCss, StitchesCss } from "@stitches/react";
export type { StitchesVariants } from "@stitches/react";

const stitches = createCss({});

export type CSS = StitchesCss<typeof stitches>;

export const { styled, global, css, getCssString, theme } = stitches;
```

2. Create a styled component and use '@initial' breakpoint on it

```
import * as React from "react";
import { styled } from "./styles";

const StyledText = styled("span", {
  "@initial": {
    color: "red",
    fontSize: 50
  }
});

export default StyledText;
```

3. there is no change on the layout and there is a error on console log

## Expected behavior

There is a change css styles on layout.

## Screenshots
![image](https://user-images.githubusercontent.com/44065042/122150973-ea7f0880-ce88-11eb-879d-2cc4968c13fa.png)

## System information

- OS: [Windows]
- Browser [Chrome v91]
- Version of Stitches: [0.2.1]

## Reproduce Demo
[https://codesandbox.io/s/bug-stitches-021-bw9jr?file=/src/Text.tsx:0-191](https://codesandbox.io/s/bug-stitches-021-bw9jr?file=/src/Text.tsx:0-191)

**Comment by norman-ags** [comment]
Same on `css` prop: Repro: https://codesandbox.io/s/kind-flower-mg04z?file=/src/App.tsx

**Comment by peduarte** [comment]
Hey hey. I chatted to Norm on Discord briefly, but will paste it here for transparency. 

`@initial` shouldn't have ever worked in `css` or in `styled` functions. It's only needed for **responsive variants**.

I know this sounds like the removal of a feature, but it was a bug fix.  Also, this was totally undocumented, so how did you find out about it anyway? 😄 

I'm curious, why are you using `@initial` in style objects? It really makes no difference, as you'll have the exact same result by putting your styles in the root level .

```diff
const StyledText = styled("span", {
+  color: "red",
+  fontSize: 50
- "@initial": {
-   color: "red",
-   fontSize: 50
- }
});
```

Whereas for responsive variants, `@initial` is the only way to tell which variant is the initial one:
```jsx
<Button size={{
  '@initial': 'small',
  '@bp1': 'large'
}} />
```

**Comment by norman-ags** [comment]
Thanks for responding @peduarte. I currently have this `Grid` component that can have dynamic and responsive columns. Internally, it passes the prop to the `css`, and with `@initial` gone, the responsive column won't work anymore.

Here's a sample usage of the component: 
```
<Grid
  col={{
    '@initial': 2,
    '@md': 3,
  }}
/>
```

Implementation:
```
const Grid =React.forwardRef(({  col, css, ...rest }, ref) => {
 const getColumn = () => {
    if (!col) {
      return {};
    }

    if (typeof col === 'number') {
      return {
        gridTemplateColumns: `repeat(${col}, 1fr)`,
      };
    } else {
      const mediaCols = Object.keys(col).reduce(
        (acc, cv) => ({
          ...acc,
          [cv]: {
            gridTemplateColumns: `repeat(${col[cv]}, 1fr)`,
          },
        }),
        {}
      );

      return mediaCols;
    }
  };
  
  return <StyledGrid {...rest} ref={ref} css={{...css, ...getColumn()}}/>
})
 
 ```

**Comment by peduarte** [comment]
Oooooh, I see 👀 

Yeah, that breaks your implementation. But the good news is that you're in charge of your implementation!

As of `0.2.0`, you can't use `@initial` in Style Objects, so you need to update your implementation to reflect that.

For example:

```jsx
const Grid = React.forwardRef(({ col, css, ...rest }, ref) => {
  const getColumn = () => {
    if (!col) {
      return {};
    }

    if (typeof col === "number") {
      return {
        gridTemplateColumns: `repeat(${col}, 1fr)`
      };
    } else {
      const mediaCols = Object.keys(col).reduce((acc, cv) => {
        const colStyle = { gridTemplateColumns: `repeat(${col[cv]}, 1fr)` };
        return {
          ...acc,
          ...(cv === "@initial" ? colStyle : { [cv]: colStyle })
        };
      }, {});

      return mediaCols;
    }
  };

  return <StyledGrid {...rest} ref={ref} css={{ ...css, ...getColumn() }} />;
});
```

I hope that helps!

**Comment by trekinbami** [comment]
Funny enough, I was using the same implementation (and the same use case) as @norman-ags. Will also have to refactor. Thanks for your answer @peduarte.

**Comment by norman-ags** [comment]
> Oooooh, I see 👀
> 
> Yeah, that breaks your implementation. But the good news is that you're in charge of your implementation!
> 
> As of `0.2.0`, you can't use `@initial` in Style Objects, so you need to update your implementation to reflect that.
> 
> For example:
> 
> ```js
> const Grid = React.forwardRef(({ col, css, ...rest }, ref) => {
>   const getColumn = () => {
>     if (!col) {
>       return {};
>     }
> 
>     if (typeof col === "number") {
>       return {
>         gridTemplateColumns: `repeat(${col}, 1fr)`
>       };
>     } else {
>       const mediaCols = Object.keys(col).reduce((acc, cv) => {
>         const colStyle = { gridTemplateColumns: `repeat(${col[cv]}, 1fr)` };
>         return {
>           ...acc,
>           ...(cv === "@initial" ? colStyle : { [cv]: colStyle })
>         };
>       }, {});
> 
>       return mediaCols;
>     }
>   };
> 
>   return <StyledGrid {...rest} ref={ref} css={{ ...css, ...getColumn() }} />;
> });
> ```
> 
> Here's a sandbox: https://codesandbox.io/s/goofy-shtern-8u5bc?file=/src/App.js:209-847
> 
> I hope that helps!

This helps a lot! Thank you so much @peduarte

**Comment by peduarte** [comment]
Thanks!

**Comment by yosafatkesuma** [comment]
Thank you very much @peduarte for your explanation

**Comment by junagao** [comment]
I was also using initial in the styled object in version 0.0.2. Now I'm upgrading it to the latest version 0.2.2 and will refactor accordingly.

Just to point out that in the migration guide: https://stitches.dev/blog/migrating-from-alpha-to-beta it mentions:

**Responsive variants**

- You need to prefix the initial key with an @ sign.
- You need to prefix media queries with an @ sign.

```
const Button = styled('button', {
 initial: {}
 '@initial': {}
 bp1: {}
 '@bp1': {}
})
```

I was a bit confused why my initial styles wasn't working after refactoring initial:{} to '@initial':{}. So that's why I ended up here in this issue.

Thanks a lot for the explanation and for the awesome work, @peduarte !
