### ISSUE TITLE
Base Theme Overrides Additional Themes

### ISSUE THREAD

**Issue by joe-bell** [modulz/stitches#635]
# Bug report

## Describe the bug

In `@stitches/react@0.2.1`, the base theme will override any additional themes

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://codesandbox.io/s/stitches-issue-reproduction-theming-s6hrl?file=/pages/index.tsx
2. Click on "Toggle Theme"
3. Open developer tools
4. See that the body class has changed and styles have been added, but the ordering is incorrect.

## Expected behavior

Custom themes should override the default base theme

## Screenshots

<img width="491" alt="Screenshot 2021-06-16 at 09 14 13" src="https://user-images.githubusercontent.com/7349341/122167163-3a5ad100-ce83-11eb-9950-5770af235265.png">

## System information

N/A

## Additional context

This seems to **only** occur in 0.2.1, 0.2.0 works fine 🙂

**Comment by peduarte** [comment]
Thanks Joe 🙌

I can confirm this is an issue. I've narrowed it down to SSR. When disabling SSR from `_document`, it works as expected. 

I've updated the sandbox to a more minimal example: https://codesandbox.io/s/stitches-issue-reproduction-theming-forked-wke7e

We'll look into this. 

Thanks!
