### ISSUE TITLE
Using `someStyles.className` no longer works without calling `someStyles()`

### ISSUE THREAD

**Issue by smhutch** [modulz/stitches#636]
# Bug report

## Describe the bug

Composing styles created with the `stitches.css()` function no longer works (compared to `0.1.9`)

## To Reproduce

1. Go to this [Sandbox](https://codesandbox.io/s/hopeful-grass-265b7?file=/src/App.js)
2. No styles are applied
3. Update the `@stitches/react` dependency to `0.1.9`
4. Styles are applied

## Expected behavior

Either:
- Styles are applied.
- Docs are updated to list this change 😄 

### `0.2.1`
![CleanShot 2021-06-16 at 07 46 09](https://user-images.githubusercontent.com/7217244/122170832-efd35780-ce76-11eb-9f79-53a11511980e.png)

### `0.1.9`

<img width="572" alt="CleanShot 2021-06-16 at 07 37 50@2x" src="https://user-images.githubusercontent.com/7217244/122169836-c7972900-ce75-11eb-934a-1a1d2714e133.png">

## System information

- OS: mac
- Browser (if applies) FF
- Version of Stitches: 0.2.1
- Version of Node.js: 14.x

**Comment by smhutch** [comment]
This is how I solved it:

## Before
```tsx
const AddStylesCLSX: ComponentExample = () => {
  return (
    <Example description={description} {...meta}>
      <Stack gap={8}>
        <div className={clsx(padded.className, dottedBorder.className)}>
          Dashed
        </div>
        <div className={clsx(padded.className, dashedBorder.className)}>
          Dotted
        </div>
        <div className={clsx(padded.className, solidBorder.className)}>
          Solid
        </div>
      </Stack>
    </Example>
  );
};
```

## After
 ```tsx
const AddStylesCLSX: ComponentExample = () => {
  const cn = {
    padded: padded().className
  }

  return (
    <Example description={description} {...meta}>
      <Stack gap={8}>
        <div className={clsx(cn.padded, dottedBorder().className)}>
          Dashed
        </div>
        <div className={clsx(cn.padded, dashedBorder().className)}>
          Dotted
        </div>
        <div className={clsx(cn.padded, solidBorder().className)}>
          Solid
        </div>
      </Stack>
    </Example>
  );
};
```

I'm aware there are probably better ways to implement this with Stitches using other approaches. This approach is added to our internal docs because the `clsx`

**Comment by peduarte** [comment]
Hey! I already replied on Slack, but will reply here also for transparency. 

`.className` is an internal API. It does return the actual class name, but it won't inject the CSS. 

By removing `.className`, everything should work fine. 

If you want to continue using it (although, be aware that this is internal and undocumented), you have 2 options:

1. Call the function:
```
<div className={component().className} />
```


2. Call the function at the top
```
component();
<div className={component.className} />
```

But hopefully everything should work fine without it 😊

**Comment by peduarte** [comment]
Just seen the comment about `clsx`. Do we have a repro for that? It could be that it doesn't call `toString` internally.

**Comment by smhutch** [comment]
Closing because this is more of a limitation of `clsx` than a limitation of, or issue with, Stitches 👍
