### ISSUE TITLE
@stitches/react 0.2.1 t.insertRule is not a function

### ISSUE THREAD

**Issue by MaximeConan** [modulz/stitches#637]
# Bug report

## Describe the bug

I have a warning in my console when I run test with RTL : `t.insertRule is not a function`. I have this warning on all my components with variants.

I have an other warning on Chrome : `Failed to execute 'insertRule' on 'CSSGroupingRule': the rule '.c-PJLV-javOHm-state-unclickable :hover:not("button"){cursor:default}' is invalid and cannot be parsed.`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

For the first warning, it on all my unit test of UI components which contains variants.

For the second one, the implementation of the style is the following 

```js
export const Row = styled('tr', {
	variants: {
		state: {
			clickable: { ':hover': { cursor: 'pointer' } },
			unclickable: {
				':hover:not("button")': {
					cursor: 'default',
				},
			},
		},
	},
})
```

## Expected behavior

I would like to not have these warnings, or understand why I have them and how to resolve it.

## System information

- macOS
- Chrome
- Stitches/react : 0.2.1

**Comment by peduarte** [comment]
@MaximeConan Hi! Are you styles working as expected?

Warnings are there when something's not quite right. If you see them, but everything looks right to you, then we may have an issue. In which case, we need a minimal reproducible example. 

PS: Do you `:hover` selectors work? In Stitches, they must be prefixed with `&` — `&:hover`
