### ISSUE TITLE
Running `ts-jest` leading to error

### ISSUE THREAD

**Issue by pffigueiredo** [modulz/stitches#645]
# Bug report
## Describe the bug

When running the tests `ts-jest`, on a component styled with Stitches, I'm encountering an error regarding the `createCss` function.

The error looks like this:

   _TypeError: Cannot read property 'length' of undefined_

       5 | export type CSS = StitchesCss<typeof stitches>;
       6 |
    >  7 | const stitches = createCss({
         |                  ^
       8 |   theme: {
       9 |     colors: {
      10 |       shadowLight: 'hsl(206 22% 7% / 35%)',

## To Reproduce

The best way to reproduce this "bug", is simply by running the tests on this [repo](https://github.com/pffigueiredo/test-ui)

`yarn test`

## Expected behavior

The test should run without any errors.

## Screenshots

![image](https://user-images.githubusercontent.com/24414890/122406355-b125c600-cf78-11eb-84a5-5e03979ac690.png)

## System information

- OS: [macOS]
- Version of Stitches: [0.1.9 / 0.2.0]
- Version of Node.js: tested in v14 and v16

## Additional context
The project where I'm dealing with this was based on a [TSDX](https://tsdx.io/) template.

**Comment by jonathantneal** [comment]
This bug is unique to Stitches 0.1.x. It is not present in Stitches v0.2.x.

The cause of the bug in 0.1.x is an incomplete DOM implementation in Jest, inherited from JSDOM.
