### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by diegomarcuz** [modulz/stitches#646]
# Bug report

## Describe the bug

There is a broken link on the [documentation](https://stitches.dev/docs/api#thememap) for the `themeMap` function.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go [here](https://stitches.dev/docs/api#thememap)
2. Click on `default mapping` link at the "Here's a list of the default mapping" text.

**Comment by apollonian** [comment]
Thanks for reporting this. The broken link should be fixed with https://github.com/modulz/stitches-site/pull/84!

**Comment by diegomarcuz** [comment]
Thanks @apollonian
