### ISSUE TITLE
Polymorphic component options in definition

### ISSUE THREAD

**Issue by gojutin** [modulz/stitches#649]
There are a couple features regarding polymorphic component definitions that I think could be useful:

1. The ability to define the default intrinsic element type in the definition.
2. The ability to narrow the element options available in the `as` prop.

```tsx
const Header = styled("header", {});

// Footer extends Header, but is still a "header" element.
const Footer = styled(Header, {});

const Page = () => (
  <Box>
    <Header>My site</Header>
    <Main>Site content</Main>
    <Footer as="footer">2021</Footer>
   {/* Awkward ⬆️ */}
  </Box>
);
```

**Possible Solutions**

1. An `as` property in the definition

```tsx
const Footer = styled(Header, {
  as: {
    default: "footer",
    // The `as` prop is narrowed to these options
    options: ["header", "footer", "div"],
  },
});
```

2. The default element as the third argument, with the `as` property as an array:

```tsx
const Footer = styled(
  Header,
  {
    as: ["header", "footer", "div"],
  },
  "footer"
);
```

Thanks for the consideration!

**Comment by gojutin** [comment]
A couple use cases where I think this could be especially useful:

1. I want to create a `Heading` component and narrow it to h1-h6 elements only
2. I want to create a `Text` element, and narrow it down to only elements that accept text as children

**Comment by gojutin** [comment]
It would also be nice to be able to mark the `as` prop as required:

```tsx
const Heading = styled(Header, {
  as: {
    required: true,
    default: "h1", // discriminated union error (can't combine required and default)
    options: ["h1", "h2", "h3", "h4", "h5", "h6"],
  },
});
```

And, to be able to define variants based on the intrinsic element:

```tsx
const Heading = styled(Header, {
  as: {
    required: true,
    // default: "h1",
    options: ["h1", "h2", "h3", "h4", "h5", "h6"],
  },
  variants: {
    as: {
      // typed from options array above (if provided)
      h1: {
        fontSize: "$3xl",
      },
      h2: {
        fontSize: "$2xl",
      },
      h3: {
        fontSize: "$xl",
      },
      h4: {
        fontSize: "$lg",
      },
      h5: {
        fontSize: "$sm",
      },
      h6: {
        fontSize: "$xs",
      },
    },
  },
});
```

**Comment by dylanklohr** [comment]
Hey, @gojutin! I believe the first feature described above relates closely to https://github.com/modulz/stitches/discussions/507 😄

**Comment by gojutin** [comment]
I realized that the Stitches API already enables you to narrow the `as` prop, as well as specify styles for each polymorphic variant, just by specifying it explicitly in the variants property:

```tsx
  variants: {
    as: {
      h1: {
        fontSize: "$3xl",
      },
      h2: {
        fontSize: "$2xl",
      },
      ...
```

Closing in favor of #507
