### ISSUE TITLE
Add a `createGlobalStyle` function

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#65]
We need to be able to create global function, similar to Styled Component. This should also support tokens and screens, but not variants.

**Comment by christianalfoni** [comment]
Should be pretty straight forward:

```ts
const globalStyle = css.global({
  // styles
})
```

Do the same here as for theme and keyframes, create a `GlobalAtom`. Make sure you handle hashing when server is involved.

**Comment by peduarte** [comment]
@hadihallak FYI ☝️ 

Thanks @christianalfoni

**Comment by jjenzz** [comment]
What are the benefits to consumers by using `css.global` instead of `style(App, {})`?

**Comment by peduarte** [comment]
To me, they are:
- consistency with other APIs
- access to `html`
- access to `body`
