### ISSUE TITLE
Unable to override inherited variants

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#652]
When we compose a Stitches Component that contains variants, we should be able to override its inherited variants. 

```jsx

const Button = styled("button", {
  variants: {
    variant: {
      primary: {
        color: "red"
      }
    }
  },
  defaultVariants: {
    variant: "primary"
  }
});

const NewButton = styled(Button, {
  variants: {
    variant: {
      primary: {
        color: "blue"
      }
    }
  }
});
```

In the example above, `NewButton` overrides the `primary` variant, inherited from `Button`. 

Since `Button` sets `primary `as the default variant, that's also inherited. So we should expect `NewButton` to be blue, but it isn't. 

Repro: https://codesandbox.io/s/stitches-bug-overriding-inherited-variants-7sron?file=/src/App.tsx

UPDATE: The current workaround is to re-define `defaultVariants`
```diff
const NewButton = styled(Button, {
  variants: {
    variant: {
      primary: {
        color: "blue"
      }
    }
  },
+ defaultVariants: {
+   variant: "primary"
+ }
});
```

**Comment by sammdec** [comment]
Im seeing a similar behaviour here but instead of trying to override the variant with another variant, I'm trying to override a single css rule.
```js
const Button = styled("button", {
  variants: {
    variant: {
      primary: {
        color: "red"
      }
    }
  },
  defaultVariants: {
    variant: "primary"
  }
});

const NewButton = styled(Button, {
  color: 'blue
});
```
The `NewButton` component will still show as red

**Comment by peduarte** [comment]
@sammdec that specific behaviour is by design. Variants are always more specific than base rules. If you want to override styles that are being applied from a variant, you gotta override the variant itself - once the bug is fixed 😅

**Comment by sammdec** [comment]
Is that a change from 0.2 as in 0.1.9 that is not the case

**Comment by peduarte** [comment]
`0.1.9` had numerous variant-related issues that weren't implemented as the spec. `0.2.0` is much more accurate to how it should work. Technically speaking, it's not a change, it's a bug fix. But I appreciate the confusion from your point of view, sorry about that. I'll try and document it better 🙏

**Comment by sammdec** [comment]
Yeah I understand your point, so I guess using a default variant is not the way to go if you want to override vas rules of it later.

**Comment by peduarte** [comment]
@sammdec yeah. Or you override variant once this issue is fixed 👍

**Comment by sammdec** [comment]
@peduarte ywah exactly, although that feels a bit clumsy as it’s not obvious especially when it’s set as a default variant

**Comment by hrasoa** [comment]
Hello, I forked the repro: https://codesandbox.io/s/stitches-bug-overriding-inherited-variants-forked-on7d4?file=/src/App.tsx

I created an intermediate ```BaseButton``` which uses ```Button```.
Then ```NewButton``` uses ```BaseButton```.

I was expecting  that ```NewButton``` would override the variant of ```Button```. Is this a bug or by design ?
