### ISSUE TITLE
TypeScript prevents use of animationName inside `styled`

### ISSUE THREAD

**Issue by smhutch** [modulz/stitches#660]
# Bug report

## Describe the bug

I'm unable to set `animationName` or `animation` on an element (it works, but TypeScript errors). TS does not error when this is nested inside `styled`.
 
The TS error:

```
src/components/ContextMenu/ContextMenuContent.tsx:11:3 - error TS2322: Type 'GlobalRule' is not assignable to type 'InternalCSS<TMedias & { initial: ""; }, { borderStyles: {}; borderWidths: {}; colors: { "danger-base": string; "danger-contrast": string; "danger-hover": string; "primary-base": string; "primary-contrast": string; ... 16 more ...; "text-highlight": string; }; ... 10 more ...; zIndices: {}; }, { ...; }, CSSProperties...'.
  Type 'GlobalRule' is not assignable to type '"none"'.

11   animationName: fadeIn,
```

## To Reproduce

1. Go to this [sandbox](https://codesandbox.io/s/cool-ives-582ij?file=/src/App.tsx)
2. View TS error on line 10
3. View no TS error on line 13

## Expected behavior

Allow `animationName` usage inside `styled`, without nesting.

## Screenshots

![CleanShot 2021-07-10 at 13 51 35](https://user-images.githubusercontent.com/7217244/125163660-0e7ef280-e186-11eb-9af2-086ec7afbb8b.png)

## System information

- OS: mac
- Version of Stitches: 0.1.9 and 0.2.1
- Version of Node.js: 14.x

**Comment by peduarte** [comment]
Nice one. TS related stuff are being worked on as we speak 🎉

**Comment by peduarte** [comment]
BW, as a workaround, this should do the trick: `animationName: `${fadeIn}`

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
