### ISSUE TITLE
Support for complex logic

### ISSUE THREAD

**Issue by iam-yan** [modulz/stitches#664]
First, thanks for the great work! I was actually trying to building a similar approach with emtion and tw, which is quite tough....This library really helps!

**Is your feature request related to a problem? Please describe.**
I am struggling with implement complex logic in a clean way.
e.g.:
- Logic OR:`if variantA === '01' || if variantA === '02' || if variantA === '03', then css = ...`
- Weight: When variant `disabled` is `true`, overwrite the background property set by any other variants... This should relate to the weight of each variant, which is now calculated by processing sequence.
- HEXA: in common css-in-js we can do this `${colorToken}D0` to create an 8 digit hex. How might we do this in stitches syntax?
- Undefined: `if variantA !== undefined, then css = ...`
- ...

**Describe the solution you'd like**
Some convention or helpers could be used to declare a complex logic.

**Comment by peduarte** [comment]
Hey! 

Have you checked out the Compound Variants API? I think it should help you. 

Regarding HEXA, you'd have to create a dedicated token. Since tokens get converted to CSS variables, you cant do string manipulation, like concat.

**Comment by iam-yan** [comment]
Hey @peduarte 

Yes. And now I am using it to give `disabled` styles the highest weight.

But how could I declare `variantA is '01' && variantB is not undefined` with the Compound Variants API? I saw your reply in my question in the discussion section. So I guess I would have to repeat a lot here, would'n I?

**Comment by peduarte** [comment]
@iam-yan without knowing exactly what youre tyring to do, yes. would you like to create a sandbox with your example? we can talk about it then

**Comment by iam-yan** [comment]
Thanks, @peduarte .
I'm getting more used to stitches and so far solutions could actually be made with inherit and composing. I'm not sure if there would be some cases require a complex logic, so I'd close this for now~
