### ISSUE TITLE
Locally Scoped Tokens should ignore `undefined` values

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#666]
Should behave the same as CSS properties

```
{
  $$color: undefined
}
```

⬆️  should be ignored, currently, an `undefined` value gets applied

Here's a demo https://codesandbox.io/s/zen-mclaren-fbcyb?file=/src/App.tsx

**Comment by peduarte** [comment]
Still happening 
![CleanShot 2021-08-30 at 10 42 08@2x](https://user-images.githubusercontent.com/372831/131320323-307c3cf8-b041-4488-963a-9c309a302b42.jpg)

**Comment by jonathantneal** [comment]
I’m not seeing this in v1 canary.

<img width="909" alt="image" src="https://user-images.githubusercontent.com/188426/131334102-ca3b39dd-c834-417a-8b98-02ddacdc34d1.png">
<img width="808" alt="image" src="https://user-images.githubusercontent.com/188426/131334133-2c479232-c779-4b2e-8094-3c4e614bee38.png">

https://codesandbox.io/s/infallible-swartz-1qcvm?file=/src/App.tsx

**Comment by peduarte** [comment]
Ok, was codesandbox being weird. Thanks!

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
