### ISSUE TITLE
`styled` API: 1st arg must be a type, then infinite style objects

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#670]
The `styled` API must follow this spec:
```jsx
const Box = styled('div', { color: 'red' }, ...infiniteStyleObjectsOrStitchesComponents)
```

- The 1st argument has to be the `type`: element, Stitches Component, React Component. **Required**
- All other arguments are style objects or Stitches Components. **Optional**

It's crucial that we always communicate what "component" (element, stitches/react component) will be coupled with those styles. Hence the term "Styled Component". This isn't something that can be left out. It's a required argument.

Thanks!

**Comment by rafgraph** [comment]
There's also a TypeScript issue with `...infiniteStyleObjectsOrStitchesComponents`.  The type for `styled` only allows 2 arguments, not an infinite number of arguments.

The multiple style objects is a good solution to #594 -- I was trying it out in [this codesandbox](https://codesandbox.io/s/hopeful-hawking-6nu3w?file=/src/App.tsx) and it adds a separate class for each style object (so it's easy to edit just the shared styles in devtools, etc) 👍 Although there are some specificity issues that need to be worked out (see codesandbox).

One consideration might be to change it from infinite arguments to just a 2nd argument that can be an array to leave the door open for something like #590 in the future without causing a breaking change.
