### ISSUE TITLE
textTransform Typing doesn't accept string even when it matches textTransform property

### ISSUE THREAD

**Issue by smol-honk** [modulz/stitches#673]
# Bug report

## Describe the bug

When using `textTransform` in a stitches react styled component, it requires the value to be `TextTransformProperty` and since I'm grabbing my styling values from a separate object, it complains that my value is of type `string` and not `TextTransformProperty` even though it's one of the css property values: i.e. 'none'.

## To Reproduce

Code Sandbox:

https://codesandbox.io/s/texttransform-bug-x6nc3?file=/src/Text.tsx

1. Go to `Text.tsx`
2. TypeScript typing error can be seen on the `textTransform` property in the Text styled component
3. Confirm that the value is one of the `textTransform` acceptable properties as a string

## Expected behavior

It should accept the value as one of the textTransform css properties without having to cast it.

## Screenshots

<img width="567" alt="image" src="https://user-images.githubusercontent.com/6879164/126844878-f4d07256-927f-4d1b-ae18-d3baf09e372f.png">

Here's the value of `typography.mobile.textTransform`:
<img width="284" alt="image" src="https://user-images.githubusercontent.com/6879164/126845085-791e1b32-e98e-416f-909b-b63f1ffe707f.png">

## System information

- OS: macOs
- Version of Stitches: 0.2.2 & 0.2.3
- Version of Node.js: node v14.17.0 (npm v6.14.13)

## Additional context

When I cast it as `TextTransformProperty` it's fine, but I think adding `| (string | {})` to that type could fix the issue.

**Comment by peduarte** [comment]
Interesting. I think it's because your object is being inferred, so `textTransform` is coming across simply as `string`, instead of `"none"`, or another valid text transform value. 

If you tell TS to basically type them as constants, it should work, for example:
```tsx
export const typography = {
  mobile: {
    textTransform: "none"
  }
} as const;
```

Now TS will know that `textTransform` is `"none"`.

This is a good thing, because if you end up putting an invalid string, it will warn you 😄

**Comment by smol-honk** [comment]
oh my goodness! Thank you so much! I'm still pretty new to TypeScript so sorry I filed this as an issue with the lib!
