### ISSUE TITLE
font-face url import does not seem to work in global function

### ISSUE THREAD

**Issue by Clee681** [modulz/stitches#674]
# Bug report

## Description

I'm not able to import a Google Font using the `@font-face` property within my `global` function. It seems to work when using `@import`.

### `stitches.config.ts`
```ts
// @import works but @font-face does not
const globalStyles = global({
  '@import': [
    "url('https://fonts.googleapis.com/css2?family=Play&display=swap')",
  ],
  '@font-face': [
    {
      fontFamily: 'Play',
      src: "url('https://fonts.googleapis.com/css2?family=Play&display=swap')",
    },
  ],
})
```

### Next.js `_app.tsx`

```ts
import { globalStyles } from '../stitches.config'

function MyApp({ Component, pageProps }: AppProps) {
  useEffect(() => {
    globalStyles()
  }, [])
  return <Component {...pageProps} />
}
```

## Expected behavior

`font-face` global styling should successfully import the google font based on the `url`

## System information

- Version of Stitches: `0.2.3`

**Comment by jonathantneal** [comment]
Hi @Clee681, I see in your example that your `@font-face` URL is not pointed at a font, but is pointed at the CSS file. Might this be your issue?

**Comment by Clee681** [comment]
Oh, you're right! I just blindly copied the import url from google fonts, and it does appear to point to the font-face rules. I'll stick with the import strategy then. Thanks for the assist @jonathantneal! Really loving stitches so far ❤️

**Comment by tiff0000** [comment]
what about using a fonts inside a `/fonts` folder? seems the google font is working, but not when importing directly from uploaded fonts
