### ISSUE TITLE
Deprecate `defaultVariants` in favour of `props` and `defaultProps`

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#688]
After a long discussion internally and with many of our users, we've decided to allow users to create default props when creating a Stitches Component. 

Reasons:
- People want the ability to define custom class names
- People want the ability to set default attributes

As a result, we'll rename `defaultVariants` to `defaultProps`, for the following reasons:
- Variants are also props, so they can be set via `defaultProps`
- Keep the API surface low
- Allow people to define responsive default variants (this is currently not possible with `defaultVariants`)

Additionally, there seems to be a lot of confusion around the fact that `defaultVariants` get inherited by compositions. This breaks most people expectations. There's an issue for it here https://github.com/modulz/stitches/issues/686.

By renaming from `defaultVariants` to `defaultProps` we believe it'll make it clearer that the props will not be carried over - since each component can have different responsibilities and different type, meaning attributes have to be dependant on its type. 

This would also allow people to define an `as` prop. Would this be problematic in terms of types? 

For example:
```tsx
const Button = styled('button', {})
const Link = styled(Button, {
  defaultProps: {
    as: "a",
    href: '' // <- would we get polymorphism here?
  }
})
```

About polymorphism, we need to understand how much this will stall the TS engine. 

Another solution to keep in mind, is to prevent the `as` prop in `defaultProps`, and instead force it to be defined as the type (1st argument)

```tsx
const Button = styled('button', {})
const Link = styled('a', Button, {
  defaultProps: {
    href: '' // <- would we get polymorphism here?
  }
})
```

Are there any pros and cons?

---

**UPDATE:**

After some thought, I think the right course of action is to `restrict the usage of `as` in `defauultProps`.

It creates too many layers of polymorphism, and requires a lot of mental model to understand what's going on. Additionally, it opens up many doors to complex and confusing architecture.

The idea here is that the `as` prop is only available on components returned by `styled()`.

---

**UPDATE 2:**

After even more thoughts, chats, and calls, we've arrived at the following conclusion:
- Carrying over props (variants, etc) to compositions **by default** is confusing and leads to unexpected expectations
- Users want the ability decide which props do get carried over, as it can be a powerful architecture decision when done on purpose 
- Users want the ability to define props within the `styled` function (this is something supported by all `styled()`-like APIs, so it makes sense we support it too, for better interoperability and hopefully more users wanting to migrate over - with more ease)

So if we consider this for a moment, I think we could make this work with the following objects:
- `props`: your component will be initialised with these props and *they will not* carry over to compositions
- `defaultProps`: your component will be initialised with these props and *they will* carry over to compositions

```jsx
const Button = styled('button', {
  variants: {
    outlined: {
      true: {},
    },
    shape: {
      square: {},
      round: {}
    },
    size: {
      small: {}
    }
  },

  props: {
    shape: 'square',
    outlined: true
  },

  defaultProps: {
    size: 'small'
  }
})

() => <Button />
// square, outlined and small
```

```jsx
const RoundedButton = styled(Button, {
  ...styles,
  defaultProps: {
    shape: 'round'
  }
})

() => <RoundedButton />
// small and square
```

```jsx
const IconButton = styled(RoundedButton, {
  ...styles,
  props: {
    outlined: true
  }
})

() => <IconButton />
// small, square and outlined
```

So, the actions for this issue are:
- [ ] Deprecate `defaultVariants`
- [ ] Introduce a `props` object: the component will be initialised with this, and this will not get carried over to compositions
- [ ] Introduce a `defaultProps` object: the component will be initialised with this, and this will get carried over to compositions
- [ ] Ensure `as` key is not allowed in `props` and `defaultProps`

**Comment by rafgraph** [comment]
@peduarte do you see this as a solution to #590? Specifically DOM elements that require a `type` prop, and composing styled components that need to select an active variant.

#### DOM elements that require a `type` prop:
```js
const TextInput = styled('input', { ... });
// but the <input> element should to be paired with a type prop
// so everywhere I use <TextInput> I have to write it like this (which makes it prone to bugs):
<TextInput type="text" {...props} />
```

#### Composing `styled` components that need to select an active variant:
```js
const ButtonBase = styled('button', {
  // styles...
  variants: {
    focus: {
      outline: {
        outline: '2px solid green',
      },
      boxShadow: {
        boxShadow: '0 0 0 2px green',
      },
    },
  },
});

const RoundedButton = styled(ButtonBase, {
  borderRadius: '1000px',
  // etc...
});
// but <RoundedButton> should always use the variant focus="boxShadow"
// so whenever I use <RoundedButton> I have write it like this (which makes it prone to bugs):
<RoundedButton focus="boxShadow" {...props}>Priority Tag</RoundedButton>
// (or wrap it in another React component)
```

**Comment by peduarte** [comment]
@rafgraph Hey! 

> DOM elements that require a type prop:

Yes!

```tsx
const TextInput = styled('input', { 
  defaultProps: {
    type: 'text'
  }
});
```

> Composing styled components that need to select an active variant:


```jsx
const ButtonBase = styled('button', {
  // styles...
  variants: {
    focus: {
      outline: {
        outline: '2px solid green',
      },
      boxShadow: {
        boxShadow: '0 0 0 2px green',
      },
    },
  },
});

const RoundedButton = styled(ButtonBase, {
  borderRadius: '1000px',
  // variants are inherited in compositions
  // so you could set it here as `defaultProps`
  // PS: this is currently possible with `defaultVariants` also
  defaultProps: {
    focus: 'boxShadow'
  }
});

```

**Comment by rafgraph** [comment]
@peduarte Yay!!! I didn't know I could already solve the second case with `defaultVariants`, but now that I think about it, it makes sense, thanks!

**Comment by rafgraph** [comment]
> By renaming from defaultVariants to defaultProps we believe it'll make it clearer that the props will not be carried over - since each component can have different responsibilities and different type, meaning attributes have to be dependant on its type.

If I'm understanding this correctly, then I don't think this makes sense for default props in general (not having default variants carry over makes sense b/c of #629, but not standard default props). Here's why:
```js
const TextInput = styled('input', { 
  defaultProps: {
    type: 'text'
  }
});

// I'd expect LargeTextInput to have `type: 'text'`, but I think you're saying that it won't
const LargeTextInput = styled(TextInput, { fontSize: '48px' });
```

Also, for me at least, I assumed that `defaultProps` would stack as that's how they work currently in composition when props are passed through, so I think this will add more confusion, not make it less confusing (it wasn't until I read #686 and then re-read this issue that I realized it wouldn't work that way).

**Comment by rafgraph** [comment]
I'm also not convinced that #629 is that big of an issue if switching to `defaultProps` that carry over. If a composed component has a default variant prop it should be able to be overridden/reset by setting the prop to `undefined`.

Using the example from #629 and updating it for `defaultProps`:
```js
const BlueBox = styled("div", {
  variants: {
    color: {
      blue: {
        color: "blue"
      }
    }
  },
  defaultProps: {
    color: "blue"
  }
});

// This composes `BlueBox`, adds a base rule, and resets the default variant prop
// so now RedBox renders red instead of blue like in the #629 example
const RedBox = styled(BlueBox, {
  color: "red",
  defaultProps: {
    color: undefined
  },
});
```

**Comment by peduarte** [comment]
@rafgraph yeah, I see where you're coming from. At a conceptual level, carrying over the default variants can make sense, but it breaks a lot of peoples expectations, so that's problematic. It's hard for users to grasp the specificity issue when default variants are defined and inherited because things happen so implicitly. 

I can see your argument for carrying over `defaultProps`, and although in your particular example it could make sense, I think generally it won't. For example:

```jsx
const Button = styled('button', {
  ...baseStyles,
  defualtProps: {
    type: 'button'
  }
})

const Link = styled(Button, {
  ...baseStyles
})

() => <Link /> 
// Now `Link` contains `type="button"`
```

Another reason is that lots of people have asked for the ability to define class names at a component level:
```jsx
const Button = styled('button', {
  ...baseStyles,
  defualtProps: {
    className: 'Button' // this can also be some third-party class, like `shopify-checkout`
  }
})
```

And at this point I start thinking its better to not carry over these component-specific props to avoid confusion and keep the ruler clearer.

I'm curious if the name `props` would somehow communicate that better?

**Comment by rafgraph** [comment]
@peduarte I see where you're coming from, although I think this will cause more issues than are currently anticipated.

The concept that `props`/`defaultProps` disappear when composing components doesn't exist in React. A component's existing/internal/default `props` can be overridden by passed in `props` in composition with the spread `...` operator, but to have `props` disappear I think will break most React engineers mental models of how composition works.

I can see how default variants may be an exception, but I think that's more of an exception specific to how default variants work (because it happens so implicitly) than the norm for `defaultProps`.

I think a majority of use cases will want the `props` to carry over. In your `Button` example, if I'm creating a few different buttons from a base button, I want `type: 'button'` to carry over, only when I change it to a `Link` do I not want it to carry over. For `className`, if it's something generic like `'Button'` I want it applied to most buttons created through composition, and when it's specific like `shopify-checkout` this component is probably use case specific and won't be used in composition.

**BUT... why not have both? Something like `defaultProps` (or `props`) that carry over, and `componentOnlyProps` (or some other specific name) that don't carry over. And `componentOnlyProps` would take precedence over `defaultProps` if there is a conflict.**

**Comment by peduarte** [comment]
I appreciate your comment and feedback, thank you!

I'm thinking. 

But it has been established that default variants can't carry over — this is a feature so changing this is out of the question.

You make some good points about whether `defaultProps` being carried over. I can agree with some of your points.

But having `defaultProps` and `defaultVariants` is a convoluted API and will cause choice paralysis. Variants _are_ props. So what happens when a variant is defined as a default in both places? 

> BUT... why not have both?

I am not totally opposed to the idea of having multiple keys, but this to me is an absolute last option. Even in the example you mentioned above, I find it confusing. I appreciate it may make sense for you, but I don't think it's something that's clear out-of-the-box. 

Im still thinking...

**Comment by rafgraph** [comment]
Sounds good, I appreciate the thought.

> But it has been established that default variants can't carry over — this is a feature so changing this is out of the question.

There are definitely times that I want the variant prop to carry over, so why not let the user choose? Why is it that it can never carry over?

```js
const ButtonBase = styled('button', {
  // styles...
  variants: {
    focus: {
      outline: {
        outline: '2px solid green',
      },
      boxShadow: {
        boxShadow: '0 0 0 2px green',
      },
    },
  },
});

// the `borderRadius: '1000px'` style and `focus: 'boxShadow'` variant prop are intrinsically linked
// and shouldn't be separated when I use RoundedButton in composition
const RoundedButton = styled(ButtonBase, {
  borderRadius: '1000px',
  defaultProps: {
    // variant prop
    focus: 'boxShadow'
  }
});

// DangerButton should have `borderRadius: '1000px'` and `focus: 'boxShadow'`
// but if the variant prop doesn't carry over then it will only have `borderRadius: '1000px'` 😭
const DangerButton = styled(RoundedButton, {
  color: 'red'
})
```

**Comment by peduarte** [comment]
Thanks for that. 

It's a fine line when using examples to back up a feature because we can always make examples that can play in favour or against it. haha

Though I think it's fair to say that there are scenarios where carrying over props do make sense, and others where it doesn't. But ultimately leaving that up to the user. 

So if we consider this for a moment, I think we could make this work with the following objects:
- `props`: your component will be initialised with these props and *they will not* carry over to compositions
- `defaultProps`: your component will be initialised with these props and *they will* carry over to compositions

```jsx
const Button = styled('button', {
  variants: {
    outlined: {
      true: {},
    },
    shape: {
      square: {},
      round: {}
    },
    size: {
      small: {}
    }
  },

  props: {
    shape: 'square',
    outlined: true
  },

  defaultProps: {
    size: 'small'
  }
})

() => <Button />
// square, outlined and small
```

```jsx
const RoundedButton = styled(Button, {
  ...styles,
  defaultProps: {
    shape: 'round'
  }
})

() => <RoundedButton />
// small and square
```

```jsx
const IconButton = styled(RoundedButton, {
  ...styles,
  props: {
    outlined: true
  }
})

() => <IconButton />
// small, square and outlined
```

Thoughts?

**Comment by rafgraph** [comment]
> Though I think it's fair to say that there are scenarios where carrying over props do make sense, and others where it doesn't. As long as it's opt-in, and not the default behaviour, I think I'm cool with it.

That makes sense to me!
![E5xjfo0XsAIENzD](https://user-images.githubusercontent.com/11911299/127685247-33745720-ce87-4317-a831-40284f16a021.jpg)

**Comment by jonathantneal** [comment]
We’ve decided to not support assigning props in components.

**Comment by rafgraph** [comment]
Can you elaborate on why not? See #590 for some reasons why implementing this would be helpful.

**Comment by peduarte** [comment]
@rafgraph Hey! After a many long internal calls, and after carefully considering all the reasons, we've decided that at the moment this isn't a priority for us. We want to keep stitches as lean as it can possibly be. The more features we add to the Styled API, the more we're just allowing people to create complex React Components via the styled function. And we wanna limit it to styles only. If people need extra logic, they're can use React wrap it and make their own component.

**Comment by rafgraph** [comment]
Makes sense. It'd be helpful to add this to the docs... an example wrapped component with TS and ref forwarding that extends the styled component's props. Something like https://github.com/rafgraph/react-interactive#typing-components-that-wrap-interactive

**Comment by rafgraph** [comment]
For example, how do I accomplish the equivalent of the following when wrapping a styled component (including ref forwarding and TS types):
```js
const TextInput = styled('input', {
  color: 'green', 
  defaultProps: {
    type: 'text'
  }
});
```

**Comment by mpkelly** [comment]
@rafgraph @Blakeinstein if you're only using JS then it's very easy. The major issue I am facing is using TS. I wish someone on the Stitches team could provide an example of how create a `styled` HOC like below that has the correct types and supports intellisense. 

Here's how you do it in JS:

```JavaScript
const NumberInput = styled("input", {
  height: 40,
  defaultProps: {
    type: "number"
  }
});

// stitches.config.jsx
import { createStyled } from "@stitches/react";
import React from "react";

const config = createStyled({
  prefix: "",
  tokens: {
    colors: { }
  }
});

export const styled = (type, ...composers) => {
  let defaultProps = {};
  (composers || []).forEach((composer) => {
    if (composer.defaultProps) {
      defaultProps = { ...defaultProps, ...composer.defaultProps };
    }
  });
  const Element = config.styled(type, composers);
  return React.forwardRef((props, ref) => {
    return <Element {...defaultProps} {...props} ref={ref} />;
  });
};

export const { css } = config;

```

Try it here

https://codesandbox.io/s/zen-hellman-3iu4f?file=/src/stitches.config.jsx:0-636

If anyone knows how to type this then please tag me in this issue. Thanks!

**Comment by mpkelly** [comment]
> If people need extra logic, they're can use React wrap it and make their own component.

@peduarte can you give an example of how to do this that is correctly typed? I've tried but it's hard to know the `Composer` param type which is very complex and using `Parameters<typeof styled>` produces `never` which looks like it could be a TS bug related to rest params.

**Comment by rnmp** [comment]
Ran into the same need and came up with this:

``` typescript
export const button = forwardRef<HTMLButtonElement>((props, ref) => (
  <button type="button" {...props} ref={ref} />
))
_button.displayName = 'button'

export const Button = styled(_button, {
  // happy hacking...
})
```

**Comment by 383bd03d** [comment]
```js
const Input = styled("input", {
  ...styles
});

Input.defaultProps = { type: "email" };

export default Input;
```

It's works
