### ISSUE TITLE
TS:1.0 - Error types spreading `StitchesCss` fragments

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#702]
I'm seeing TS errors when spreading `StitchesCss`. Examples below, with minimal test cases that should pass:

### Spread/compose `StitchesCss`

Both of these should work
```tsx
const red: StitchesCss = { color: 'red' };
const text = css({ fontFamily: 'serif', ...red });
```

```tsx
const red: StitchesCss = { color: 'red' };
const text = css({ fontFamily: 'serif' }, red)
```

**Comment by jonathantneal** [comment]
Either in the current canary, or in the canary after the current round of PRs are merged, this is now working.

```tsx
import * as Stitches from '@stitches/react'

const { css } = createStitches()

const red1: Stitches.CSS = { color: 'red' };
const text1 = css({ fontFamily: 'serif', ...red1 });
const red2: Stitches.CSS = { color: 'red' };
const text2 = css({ fontFamily: 'serif' }, red2)

void red1
void text1
void red2
void text2
```

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
