### ISSUE TITLE
Incorrect typings for styled inputs on Canary

### ISSUE THREAD

**Issue by sandgraham** [modulz/stitches#712]
# Bug report

## Describe the bug

On `v1.0.0-canary.5` a styled component created as so:
```tsx
styled('input', { ... })
```
has an `onChange` of `any`.

On `0.2.4` the same styled component's `onChange` is correctly typed as `React.ChangeEvent<HTMLInputElement>`.

## To Reproduce

Here are some sandboxes to compare:

CodeSandbox on 0.2.4: https://codesandbox.io/s/stitches-input-event-0-2-4-1ojvo?file=/src/App.tsx
CodeSandbox on 1.0.0-canary.5: https://codesandbox.io/s/stitches-input-event-canary-mnrpc?file=/src/App.tsx

## Expected behavior

Correctly type intrinsic props.

_It looks like this started in `1.0.0-canary.0`._

**Comment by sandgraham** [comment]
This was fixed in canary.6!

https://codesandbox.io/s/stitches-input-event-canary6-srexp

**Comment by jonathantneal** [comment]
Confirmed! 🎉
