### ISSUE TITLE
TS:1.0 - createTheme return type does not include ThemeTokens when theme class is used

### ISSUE THREAD

**Issue by jake-nz** [modulz/stitches#713]
Without a theme class it's fine: `createTheme(theme)` 

When you try to define the theme class by passing it as the first argument: `createTheme('dark-theme', theme)` the return type is just `{ className: string; selector: string; } & "dark-theme"`

## To Reproduce
```js
const { createTheme } = createStitches({
  theme: { colors: { ...gray } }
})

export const dark = createTheme('dark-theme', {
  colors: { ...grayDark }
})

console.log(dark.colors.gray1)
```
> Property 'colors' does not exist on type '{ className: string; selector: string; } & "dark-theme"'

**Comment by peduarte** [comment]
Hi! This has been released to Stitches v1.1.0

```
yarn add @stitches/react@latest
# or
npm install @stitches/react@latest
```
