### ISSUE TITLE
TS:1.0 - Expression produces a union type that is too complex to represent

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#716]
From our DS.

Code used to repro:

```
const { styled, config } = createStitches({})
type CSS = Stitches.CSS<typeof config>

export const overlayStyles: CSS = {
  backgroundColor: 'rgba(0, 0, 0, .15)',
};

export const Overlay = styled('div', overlayStyles);

```

![image](https://user-images.githubusercontent.com/372831/128827944-bdd6d130-0214-4445-b953-3db5e2e5e8ef.png)

---

I think TS server is crashing, because sometimes this happens and sometimes it doesnt

**Comment by hadihallak** [comment]
this should be fixed. if not then this is a regression

**Comment by peduarte** [comment]
@hadihallak fixed where? Theres been no new pushed to `canary` since this was reported

**Comment by hadihallak** [comment]
late last week I pushed changes to fix it. I've specifically tested against this case back then as I've seen it thrown around on slack 

just re-tested it again now and it's working for me

**Comment by hadihallak** [comment]
the main fix was in [here](https://github.com/modulz/stitches/pull/722/files) and I think @jonathantneal cherry-picked the change from the PR into canary

**Comment by peduarte** [comment]
Gotcha.

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
