### ISSUE TITLE
Type regression for targeting a Stitches component in Canary

### ISSUE THREAD

**Issue by sandgraham** [modulz/stitches#719]
# Bug report

## Describe the bug

[Targeting a stitches component](https://stitches.dev/docs/styling#target-a-stitches-component) gives a type error on canary releases.

## To Reproduce

```tsx
const Inner = styled('div', { ... });
const Outer = styled('div', { [`& ${Inner}`]: { ... } }); // TS error
```

Here are two sandboxes comparing type behavior:

[`1.0.0-canary.7`](https://codesandbox.io/s/stitches-target-stitches-component-canary7-00ksz?file=/src/App.tsx)
[`0.2.4`](https://codesandbox.io/s/stitches-target-stitches-component-0-2-4-wruft?file=/src/App.tsx)

## Additional context

_Seems to have started in `1.0.0-canary.0`_.

**Comment by sandgraham** [comment]
Looks like this was fixed in canary.8!

https://codesandbox.io/s/stitches-target-stitches-component-canary8-rmjy3

**Comment by jonathantneal** [comment]
Confirmed.
