### ISSUE TITLE
Type error for token with CSS type

### ISSUE THREAD

**Issue by cappuc** [modulz/stitches#729]
# Bug report
## Describe the bug

The `CSS` type (`type CSS = Stitches.CSS<typeof stitchesConfig>`) does not support scale tokens.

With `1.0.0-canary.6` and before token values are allowed but not suggested in the type but from `1.0.0-canary.7` token values throw a type error.

## To Reproduce

[https://codesandbox.io/s/stitches-missing-scale-values-in-css-type-3g5te?file=/src/App.tsx](https://codesandbox.io/s/stitches-missing-scale-values-in-css-type-3g5te?file=/src/App.tsx)

## Screenshots

With native css property of style components tokens are suggested and allowed ($test is present)
![native css property](https://user-images.githubusercontent.com/4271608/129745269-3b64b832-bf8e-44f7-b20b-420b846ddd5e.png)

With custom typed css property the token is not suggested (1.0.0-canary.6) ($test is not present)
![custom css property (1.0.0-canary.6)](https://user-images.githubusercontent.com/4271608/129745675-9112c9ff-0c10-4e0e-9c0a-9f0091f5d533.png)

With custom typed css property the token give type error (1.0.0-canary.10) 
![custom css property (1.0.0-canary.10)](https://user-images.githubusercontent.com/4271608/129746959-788d173e-7ec1-4311-a552-2c79f2c6a298.png)

**Comment by cappuc** [comment]
I found the problem. 

Instead of `type CSS = Stitches.CSS<typeof stitchesConfig>` it should be `type CSS = Stitches.CSS<typeof stitchesConfig.config>`

**Comment by peduarte** [comment]
@jonathantneal is this on purpose?

**Comment by jonathantneal** [comment]
@peduarte, yes, where our recommended usage would be like this:

```ts
const { config, css, styled /* etc */ } = createStitches()

type CSS = Stitches.CSS<typeof config>
```
