### ISSUE TITLE
Make `theme.className` inject styles

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#732]
A few users have expected `theme.className` to also inject the styles. Right now, it doesn't, and the workaround is to do `theme.toString()`

This issue is to make `.className` inject the theme styles

**Comment by jonathantneal** [comment]
Added in https://github.com/modulz/stitches/commit/f75e0a8894fe0bc78132d0e5e7713b5b23bbdd66

**Comment by jonathantneal** [comment]
Added tests in 974c588

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
