### ISSUE TITLE
Type regression `scrollMarginLeft` and `scrollMarginRight`

### ISSUE THREAD

**Issue by sandgraham** [modulz/stitches#733]
# Bug report

## Describe the bug

As of `canary.8` there is a type regression on the `scrollMarginLeft` and `scrollMarginRight` css properties.

## To Reproduce

| working? | sandbox |
| --- | --- |
| ✅ | [canary.7](https://codesandbox.io/s/stitches-scrollmarginleft-canary-7-8ds14?file=/src/App.tsx) |
| ❌ | [canary.8](https://codesandbox.io/s/stitches-scrollmarginleft-canary-8-4w5kj?file=/src/App.tsx) |
| ❌ | [canary.15](https://codesandbox.io/s/stitches-scrollmarginleft-canary-15-2itmj?file=/src/App.tsx) |

## Additional context

Interestingly, `scrollMargin` has correct typing.

**Comment by jonathantneal** [comment]
Fixed in 6f5c03bd8c054386503cb9dabf6ffb0aaf071817

**Comment by peduarte** [comment]
@jonathantneal still an issue in `canary.18`

**Comment by jonathantneal** [comment]
This is not the same issue. It is a different issue. We do not currently offer suggestions for nested tokens like `$space$1`. However, we previously allowed any string as a value, which would prevent `$space$1` from throwing a type error. However, permitting any string means TS will not throw a type error when a missing or invalid token is used. This puts us at an impasse.

1. Do we explicitly allow nested tokens? This preserves strict typing, but may conflate suggestions beyond usefulness.
2. Do we allow any string? This preserves suggestions, but drops strict typing.
3. Do we disable string tokens like `$space$1` entirely and only permit explicit usage like `theme.space[1]`? This somewhat preserves suggestions and definitely preserves strict typing, but drops a major feature.

**Comment by peduarte** [comment]
Can it behave just like `marginLeft`?

**Comment by jonathantneal** [comment]
> Can it behave just like `marginLeft`?

Yes. This is option #2, where invalid tokens work.

**Comment by peduarte** [comment]
All CSS Properties should work the same, where they accept a string, tokens (strings), and for some of them, numbers.

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
