### ISSUE TITLE
TS:1.0 - font weight error

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#735]
> Type '"500"' is not assignable to type 'Globals | ScaleValue | FontWeight | undefined'.

this happened when using `css` override, but prob happens everywhere:

```jsx
<Component css={{ fontWeight: '500' }}
```

**Comment by jonathantneal** [comment]
Fixed in d6a594c

**Comment by peduarte** [comment]
Fixed in V1. Please refer to [migration guide](https://stitches.dev/blog/migrating-from-beta-to-v1) and [changelog](https://stitches.dev/blog/stitches-1.0.0)
