### ISSUE TITLE
`@initial` overriding other responsive variant values

### ISSUE THREAD

**Issue by hwhmeikle** [modulz/stitches#737]
# Bug report

## Describe the bug

When using the responsive variant syntax I have observed that the `@initial` value sometimes overrides what is specified at `@md` .

## To Reproduce

Code Sandbox: https://codesandbox.io/s/responsive-variants-t11m4?file=/src/App.tsx

1. Ensure your screen width > 768px (to trigger the '@md' breakpoint)
2. Click the 'Go to PageB' link
3. Observe that on route `/b` the Icon's `@md` value is being overwritten by the `@initial` value
4. Refresh the Code Sandbox rendering window
5. Observe that the `@md` value is now overriding the `@initial` value.
6. Click the 'Go to PageA' link
7. Observe that the Icon's `@md` value is being overwritten by the `@initial` value

## Expected behavior

I would expect that the `@initial` value is always overwritten by `@md` (when we are above > 768px).

## Screenshots

`@initial` overwriting `@md`:

![image](https://user-images.githubusercontent.com/19391152/130873897-06e9ad7f-a194-4b6c-b13d-0b05bdc0fe98.png)

`@md` overwriting `@initial` after refresh:

![image](https://user-images.githubusercontent.com/19391152/130874096-f2be28fe-3d4f-417d-8864-4f4e39ca8dc6.png)

**Comment by peduarte** [comment]
@jonathantneal followed steps provided and verified as a bug.

**Comment by philkeys** [comment]
I've been experience this as well. In the meantime, what would be the best approach to still achieve something like `@initial` and `@bp2` when using styled components. In the docs it recommends not inlining breakpoints, but is that the best option?

**Comment by klaasman** [comment]
I just ran into this issue, any ETA or help needed investigating?

**Comment by hadihallak** [comment]
this is now fixed in #875 and is pending release so i'm gonna keep the issue open until we release it publicly

**Comment by hadihallak** [comment]
This is now fixed in a release candidate under the version `1.2.6-0` under a canary tag.
Should be pretty stable if you'd like to upgrade now but expect a final release sometime next week once we finish migrating our products to use the updated version.
 
Please, don't hesitate in providing us with any feedback regarding this release. very much appreciated 🙏

**Comment by hadihallak** [comment]
Published under `1.2.6` 🎉
