### ISSUE TITLE
Type Errors after upgrading to TypeScript 4.4.2

### ISSUE THREAD

**Issue by acidfernando** [modulz/stitches#742]
# Bug report

## Describe the bug

After upgrading to TypeScript `4.4.2`, some styled components started displaying type errors. I've managed to find out that these errors only appear when using the `styled` function returned by `createCSS` and only when you try to do something like this:

```
export const StyledComponent = styled('div', {
  height: "50px",

  [`& ${SomeOtherStyledComponent}`]: {
    backgroundColor: "blue",
  },
});
```

## To Reproduce

In this [Repro](https://github.com/acidfernando/stitches-repro), navigate to `components/Home.styles.ts` with your editor configured to use typescript 4.4.2 or try to build the project with `yarn build` or `npm run build`

## Expected behavior

No typescript errors

## System information

- OS: macOS
- Version of Stitches: 0.2.5
- Version of Node.js: 14.17.0
- Version of Typescript: 4.4.2

**Comment by acidfernando** [comment]
> Thanks. So, just to confirm, this isnt an issue in `1.0.0-canary.17` and above, right?

Correct

**Comment by jonathantneal** [comment]
Yay! Closing as fixed in v1! ✨
