### ISSUE TITLE
TypeScript regression: nested CSS with selectors "not allowed" in config.utils

### ISSUE THREAD

**Issue by LexSwed** [modulz/stitches#743]
# Bug report [1.0.0-canary.18]

## Describe the bug

When using nested selectors in `utils`, TypeScript highlights the error that `utils` only allowed to return CSS properties:

```tsx
// rest of the config
  utils: {
    size: (value: number) => ({
      width: value,
      height: value
    }),
   // Type '{ $$focusRingColor: string; "&:focus": { outline: string; boxShadow: string; }; }' has no properties in common with type '{ alignContent?: PropertyValue<"backgroundColor"> | "stretch" | OnlyString | "space-around" | "space-between" | "space-evenly" | "center" | "end" | ... 5 more ... | undefined; ... 426 more ...; vectorEffect?: PropertyValue<...> | ... 2 more ... | undefined; }'
    focusRing: (color: PropertyValue<"backgroundColor">) => ({
      $$focusRingColor: `$colors${color}`,
      "&:focus": {
        outline: "none",
        boxShadow: `0 0 0 3px $$focusRingColor`
      }
    })
  },
// rest of the config
```

## To Reproduce

[CodeSandbox](https://codesandbox.io/s/adoring-wing-bzuru?file=/src/stitches.config.ts)

## Expected behavior

Since it works as expected and correct styles applied, I expect TypeScript stop yelling at me.

## System information

- Version of Stitches: 1.0.0-canary.18
- Version of Node.js: 16

**Comment by jonathantneal** [comment]
Hi @LexSwed, would you be able to confirm that this is working as expected in v1.0.0?

https://codesandbox.io/s/magical-hypatia-0r8yv?file=/src/stitches.config.ts

**Comment by LexSwed** [comment]
Yes, indeed, thank you!
