### ISSUE TITLE
Share variants across any component

### ISSUE THREAD

**Issue by hrasoa** [modulz/stitches#755]
**Is your feature request related to a problem? Please describe.**
Maybe I missed it the doc, but I'm in a case where I need to add common focus ring styles on any focusable elements, in instance: ```buttons, links, divs with tabIndex=0, etc...```
My variant:

```js
variants: {
  focusVisible: {
    true: { ...styles }
  }
}
```

```jsx
const Button = styled('button');
const Anchor = styled('a');
const Box = styled('div');

<Button focusVisible>btn</Button>
<Anchor focusVisible>link</Button>
<Box tabIndex={0} focusVisible>div</Box>
// and so on
```

**Describe the solution you'd like**
I would like to be able to define the variant only in one place, and use it anywhere.

**Describe alternatives you've considered**
I was thinking about adding a variant token in the theme:

```js
createStitches({
  theme: {
    ...
    variants: {
      focusVisible: {
        true: { ...styles }
      }
    }
  }
});

**Comment by jonathantneal** [comment]
You can do this with our composition API.

```js
const focusableVariants = css({
	variants: {
	    focusVisible: {
	  	  true: {
	  	      ...styles
	  	  }
	    }
	}
})

const Button = styled('button', focusableVariants, { /* more styles */ })
const Anchor = styled('a', focusableVariants, { /* more styles */ })
const Box = styled('div', focusableVariants, { /* more styles */ })
```

Would you let me know if you think this works well for you?

**Comment by mikeytown19** [comment]
@jonathantneal Awesome, thanks!

**Comment by hrasoa** [comment]
@jonathantneal thank you this is exactly what I wanted.

**Comment by vctormb** [comment]
Is it possible to do something like this? It doesn't show to me the variant coming from `focusableVariants`
```ts
const Button = styled('button', focusableVariants, { defaultVariants: { focusVisible: true } })
```
