### ISSUE TITLE
Consider compressing hashed atomic classnames

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#76]
Currently they are: `brw_3001088182 bbw_115517177 blw_1917871437 bts_1515315272`, wonder if we can keep them shorter in production?

**Comment by christianalfoni** [comment]
@hadihallak asked about the hashing algorithm, if there was any special reason for using the one we use. Nopes, we can use something else which produces shorter names 😄 

I believe styled-components has a pretty nice one, we could just use that. 

https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/utils/hash.js
