### ISSUE TITLE
Ability to use in plain HTML/CSS

### ISSUE THREAD

**Issue by kaelrhys** [modulz/stitches#760]
First of all, I want to say stitches looks like one of the most promising libraries I've seen in a while, following styled system/theme UI. I'm looking to adopt a decent scale enterprise app.

**Is your feature request related to a problem? Please describe.**
I can only use stitches with CSS in JS? No way to export compiled CSS. 

**Describe the solution you'd like**
It would be great if there was a way to compile CSS utilities, tokens and components into a static CSS file.

**Describe alternatives you've considered**
Style dictionary. Tailwind.

**Comment by wobsoriano** [comment]
Not sure if this answers your question but you can use [getCssText](https://stitches.dev/docs/server-side-rendering) to access the css string

**Comment by peduarte** [comment]
Stitches does not currently offer a way to use it without JS

As @wobsoriano said, you can use the `getCssText` API to return the CSS string for a page, but even then, your components need to be authored in JS. 

Good news is that we will start working on a static extraction feature, which will essentially allow users to use Stitches in a similar fashion than CSS Modules. 

So, keep an eye out, and follow us on [Twitter](https://twitter.com/stitchesjs)! 🚀
