### ISSUE TITLE
Can't target Stitches component within :has() pseudo-selector

### ISSUE THREAD

**Issue by kiastorm** [modulz/stitches#766]
# Bug report

## Describe the bug

Following this page in the docs: [Target a Stitches component](https://stitches.dev/docs/framework-agnostic#target-a-stitches-component)

I'm trying to make something like the [Input Group](https://chakra-ui.com/docs/form/input#add-elements-inside-input) component from Chakra UI by using the `has` pseudo selector, but the styles aren't being applied.

## To Reproduce

```
const inputElement = css({
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  position: 'absolute',
  top: '0',
  zIndex: 2,
})

export const leftInputElement = css(inputElement, { insetStart: 0 })
export const rightInputElement = css(inputElement, { insetEnd: 0 })

const StyledInputGroup = styled(DEFAULT_TAG, {
  width: '100%',
  display: 'flex',
  position: 'relative',
  [`&:has(.${leftInputElement})`]: {
    paddingLeft: '$4',
  },
  [`&:has(.${rightInputElement})`]: {
    paddingRight: '$4',
  },
})
```

## Expected behaviour

If `InputGroup` contains an element with `leftInputElement` class, the correct padding should be applied

The `has` pseudo selector doesn't have very good support, so apologies if this is due to that.

**Comment by ricreis394** [comment]
Did you already solved this issue? How?
