### ISSUE TITLE
Dotted format of tokens breaks CSS variables

### ISSUE THREAD

**Issue by lukemorales** [modulz/stitches#774]
# Bug report

## Describe the bug

For a lot of design system libraries such as styled-system, chacka-ui etc, their format of tokens follow the pattern `ui.button.active`.
I've tried to use that format when creating my tokens as we can have tokens for buttons and different variables and different states of those buttons, for example `button.primary.active` and the css broke as you can see in the screenshot, only a dashed format works.
It's a simple thing, don't know if this is the expected behavior but migrating from those libraries to stitches might be a more smooth experience if people can stick with the tokens they were using before rather than have to refactor.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Create theme tokens with the dotted format and use them on any component.

```js
theme: {
  colors: {
   'button.primary.active': 'purple'
  }
}
```

## Expected behavior

Styles should be working correctly

## Screenshots

![CleanShot 2021-09-10 at 11 22 35](https://user-images.githubusercontent.com/14251143/132868714-cd6c5781-f822-484b-b304-26aa47357c56.png)

## System information

- OS: macOS
- Browser (if applies) Edge
- Version of Stitches: 1.1
- Version of Node.js: 14.17.3

**Comment by csantos1113** [comment]
I think, per design, those tokens are not accepted: https://stitches.dev/docs/tokens#naming-convention

> We recommend using camel case, pascal case or snake case for your theme tokens. Other word separators may not work as expected.
> 
> // recommended
> tokenName
> token_name
> token-name
> 
> // avoid
> token.name
> token$name
> token*name
> You can read more about [this here](https://github.com/modulz/stitches/issues/493#issuecomment-801241038).

**Comment by lukemorales** [comment]
Oh, I've completely missed that part of the documentation! Thank you for pointing that out to me @csantos1113
