### ISSUE TITLE
Utils not typed?

### ISSUE THREAD

**Issue by judehunter** [modulz/stitches#779]
# Bug report

## Describe the bug

Might be something wrong with my config, but it seems like defining utils in `createStitches` does not enable me to use intellisense when styling components? To be more precise, the util does not show up at all when typing the key, and thus I also cannot constrain the value type.

The util itself works correctly, just the intellisense isn't.

Definition of util:

![image](https://user-images.githubusercontent.com/32528507/133004983-f8616c43-bfc7-40a6-a5c8-e90500f58206.png)

The `test` util does not show up in the intellisense list:

![image](https://user-images.githubusercontent.com/32528507/133005044-de3b7298-5cfc-463c-8fe4-41bd6cd2e661.png)

## To Reproduce

1. Create a stitches config:
```ts
import {createStitches} from '@stitches/react'
export const {
  styled
} = createStitches({
  utils: {
    test: (value: number) => ({
      margin: value,
    }),
  }
})
```
2. Define a styled component:
```ts
const Button = styled('div', {
  test
})
```
3. Observe the intellisense suggestion list
## Expected behavior

Should suggest the util's name and also properly constrain the value's type. In this case, only numbers should be allowed.

## System information

- OS: Win10
- Version of Stitches: 1.1.0
- Version of TS: 4.4.3

**Comment by peduarte** [comment]
Hey! This should work. Can you provide a reproducible example? Thanks!

**Comment by judehunter** [comment]
hey @peduarte 
it seems like maybe there's something wrong with the vs code on my laptop.
I couldn't reproduce this on codesandbox and I just checked and it works on my desktop.

**Comment by peduarte** [comment]
Great stuff! feel free to close 🔥 Thanks

**Comment by gustavo-dev** [comment]
@judehunter Have you figured out how to fix it? The same thing is happening here (desktop).

**Comment by lewiiiis** [comment]
@peduarte here's an example https://codesandbox.io/s/rough-rgb-kj1dm?file=/src/App.tsx
![image](https://user-images.githubusercontent.com/76946953/146184545-d0b4bd45-1c1a-4f04-a191-7ea1c1513f25.png)
![image](https://user-images.githubusercontent.com/76946953/146184641-f35795eb-8f9b-4771-8622-0a4d354b5b4b.png)
