### ISSUE TITLE
className property of Default Theme exported from createStitches not typed correctly

### ISSUE THREAD

**Issue by lucastobrazil** [modulz/stitches#781]
# Bug report

## Describe the bug

When trying to access the `className` property of the default theme that gets exported from `createStitches()`, TS complains 

```
Property 'className' does not exist on type 'string & { fonts: { default: Token<"default", string, "fonts", "vitality">; caption: Token<"caption", string, "fonts", "vitality">; body: Token<"body", string, "fonts", "vitality">; ... 12 more ...; display900: Token<...>; }; ... 8 more ...; sizes: { ...; }; 
```

## To Reproduce
CSB Link: [https://codesandbox.io/s/stitches-dark-mode-te4ne?file=/src/ColourModeProvider.tsx](https://codesandbox.io/s/stitches-dark-mode-te4ne?file=/src/ColourModeProvider.tsx)

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Open ColourModeProvider.tsx
2. LIne40 - TS complains

## Expected behavior

I am hoping this is just a bug and that both defaultTheme and themes created via `createTheme()` have the className property typed on them

## Screenshots
<img width="1055" alt="Screen Shot 2021-09-14 at 9 35 27 pm" src="https://user-images.githubusercontent.com/8508891/133252007-4b2e8770-da3b-4ec4-a40a-f050b2eb858f.png">

## System information

- OS: MacOS Catalina
- Browser (if applies) Chrome Latest
- Version of Stitches: 1.1.0

**Comment by peduarte** [comment]
Thanks for this! Yes, `defaultTheme` should also have a `className` property on it.

We'll look into this 👀 

For now, would `defaultTheme.toString()` be a good workaround?
