### ISSUE TITLE
Issue with cross origin frame on Shopify stores

### ISSUE THREAD

**Issue by rkumorek** [modulz/stitches#783]
# Bug report

## Describe the bug

On some Shopify stores Stitches seems to throw with cross origin error? It happens when I bundle with Webpack as well as loading via script tag.

It happens on few production stores e.g. [https://alessandrarich.com/](https://alessandrarich.com/) or [https://twinings.co.uk/](https://twinings.co.uk/) but it works on [https://boysmells.com/](https://boysmells.com/). 

See below screenshot.

## Screenshots

<img width="960" alt="css" src="https://user-images.githubusercontent.com/34352395/133392172-f17df3f7-ec67-4c8c-b3d7-751b062710eb.png">

**Comment by peduarte** [comment]
Hey! Thanks for raising an issue.

Off the top of my head, I'm not sure why this would happen. Especially when it works on one and not others. 

Pinging @jonathantneal in case he has any pointers.

**Comment by rkumorek** [comment]
Hey @peduarte

Thanks for quick reply. I think I managed to narrow down the issue to conflicting script which seems to be Hotjar.

In devtools if I block loading script from (loaded via GTM) `https://static.hotjar.com/c/hotjar-1109788.js?sv=7`  Stiches then works as expected.

Unfortunately I don't know anything about Hotjar, how it works and what it does but I will try to dig deeper into the issue here.
