### ISSUE TITLE
Theme tokens cause a TypeScript type error in compound variants

### ISSUE THREAD

**Issue by christianhg** [modulz/stitches#786]
# Bug report

## Describe the bug

Theme tokens cause a TypeScript type error in compound variants.

## To Reproduce

Following [the guide in the docs](https://stitches.dev/docs/typescript#stricter-experience), I've created a CodeSandbox where I use theme tokens in different simple scenarios: https://codesandbox.io/s/cocky-tereshkova-261lk?file=/src/App.tsx

The CodeSandbox demonstrates how TypeScript reports a type error when using tokens in a compound variant:

<img width="887" alt="Screenshot 2021-09-15 at 13 33 35" src="https://user-images.githubusercontent.com/4602382/133425949-ef4a7154-299f-4086-9a1f-33f928842e79.png">

## Expected behavior

Theme tokens can be used as values in compound variants.

---

Thank you for all your hard work. Stitches has been a pretty awesome experience so far, and this is the first problem I've stumbled upon.

**Comment by peduarte** [comment]
Ohh interesting. We may need to update the types there for when used within `compoundVariants`.

Can you please confirm that it does work when used elsewhere? Eg: a root declaration, or within variants?

**Comment by christianhg** [comment]
> Can you please confirm that it does work when used elsewhere? Eg: a root declaration, or within variants?

It does :) The CodeSandbox has these examples as well:

<img width="820" alt="Screenshot 2021-09-15 at 14 22 53" src="https://user-images.githubusercontent.com/4602382/133432618-47566106-f456-4fc5-a5e3-53d91993fccd.png">

**Comment by peduarte** [comment]
Perfect. Sorry, I think I entered an autopilot mode where I immediately ask for reproductions. Thank you!
