### ISSUE TITLE
Nest media queries

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#79]
One thing to keep in mind, once we implement inline media queries (#67) is to have the ability to nest them.

```css
@media (min-width: 400px) {
  @media (hover: hover) {
    // Colm's cool hover effect in dark mode
  }
}
```

This should also work with predefined media (`screens`):
```
{
  medium: {
    hoverSupport: {
      // Colm's cool hover effect in dark mode
    }
  }
}
```

Im setting this as a P2 because it's something that is currently achievable. With inline media queries you can rely on a single media query with the `and` operator. With the screens token, you can do the same 😄

**Comment by colmtuite** [comment]
I upgraded this to priority: 1 because we'll have to push the release date back anyway now.

**Comment by colmtuite** [comment]
Downgraded to Priority: 2 again because:

1. I just noticed it's in the Primary release anyway.
2. I just noticed we're treating this separately from nesting media queries inside variants, which is the more important one imo.

**Comment by hadihallak** [comment]
This can be done now via utils since #112 is merged
