### ISSUE TITLE
Clear roadmap

### ISSUE THREAD

**Issue by darklight9811** [modulz/stitches#792]
Would like to suggest a clear roadmap of the current status of the project (what you are working) and what is intended for stitches (what you plan to work). This would avoid duplicate feature requests, allow the users to understand what is happening and what to expect from stitches.

**Comment by darklight9811** [comment]
For example, I would like to know if there is any plan to support styled component like themes, something entirely controlled by javascript. I know that you are proposing a different approach, but I would love to see this here (is the only thing that I don't like in a sea of things I love)

**Comment by peduarte** [comment]
Sorry, we can't do that right now. Stitches as of now is the final product. New features need to be created as RFC discussions, and then they can go under consideration. 

You're more than welcome to create as many discussions as you'd like, about ideas, features, and we can chat further!
