### ISSUE TITLE
globalCss can throw when given multiple styles

### ISSUE THREAD

**Issue by jonathantneal** [modulz/stitches#794]
# Bug report

The `globalCss` function can throw when given multiple style arguments.

```tsx
import * as Stitches from '@stitches/react'

const { globalCss } = Stitches.createStitches({})

export const globalStyles = globalCss(
	{
		body: {
			margin: 0,
		},
	},
	{
		"*": {
			margin: 0,
			padding: 0,
		},
	}
)
```

## To Reproduce

See reproduction.

## Expected behavior

The styles should not throw.

## System information

- OS: macOS
- Version of Stitches: 1.1.0
- Version of Node.js: 16

**Comment by csantos-nydig** [comment]
This is not still not working I believe: https://github.com/modulz/stitches/issues/842
