### ISSUE TITLE
styled function is generating incorrect CSS custom property

### ISSUE THREAD

**Issue by dungle-scrubs** [modulz/stitches#807]
# Bug report

Following the docs, when doing the following...

```
// stitches.config.js

import { createStitches } from '@stitches/react'

export const { styled } = createStitches({
  theme: {
    colors: {
      violet800: 'hsl(252 62% 54.9%)',
    },
  },
});
```

```
// Component.js

import { styled } from '../stitches.config'

const Button = styled('button', {
  backgroundColor: '$violet800',
});

() => <Button>Button</Button>;
```

There is a css variable created called `--colors-violet800`.  However, the variable applied to the `background-color` property is `var(--violet800)` while it should be `var(--colors-violet800)`.

## Expected behavior

I would expect the component's `background-color` property to have the value `var(--colors-violet800)`

## System information

- OS: macOS
- Browser (if applies) All
- Version of Stitches: 1.2.0
- Version of Node.js: 14.17.6

**Comment by jonathantneal** [comment]
I was unsuccessful at recreating this issue. It appears to be working as expected. See https://codesandbox.io/s/prod-microservice-uulne?file=/src/App.tsx

**Comment by peduarte** [comment]
This sounds unlikely. Need a reproduction please.

**Comment by dungle-scrubs** [comment]
Here's a [minimal reproduction](https://github.com/dungle-scrubs/stitches-styling-bug) where the issue is still happening for me.  Maybe I configured something incorrectly?

**Comment by peduarte** [comment]
@dungle-scrubs This is happening because you're overriding the `themeMap` but passing in an empty object: https://github.com/dungle-scrubs/stitches-styling-bug/blob/main/stitches.config.js#L31-L36

The `themeMap` is there so you can provide and override mappings of scales to properties. 

This is documented here: https://stitches.dev/docs/api#thememap

There's even a note stating:
> Note: this overrides the default mapping. Import `defaultThemeMap` to merge with default.

Hope this helps, thanks!

**Comment by dungle-scrubs** [comment]
Thanks @peduarte , can't believe I missed that.
