### ISSUE TITLE
Feature Proposal: createThemedVariant

### ISSUE THREAD

**Issue by joe-bell** [modulz/stitches#810]
**Is your feature request related to a problem? Please describe.**

One thing I find myself doing regularly with stitches is mapping through themed values to generate my variants

For example, let's look at this demo `grid` style which reduces `theme.space` into a `gap` variant:

```ts
import type * as Stitches from '@stitches/core';
import { css, config } from "./stitches.config";

const { space } = config.theme;

const gap = Object.keys(space).reduce(
  (acc, cv) => ({
    ...acc,
    [cv]: { $$gridGap: `$space$${cv}` },
  }),
  {}
) as { [key in keyof typeof space]: Stitches.CSS };

export const grid = css({
  display: "grid",
  gap: "$$gridGap",
  variants: {
    gap,
  },
  defaultVariants: {
    gap: 4,
  },
});
```

Which can then be used like so:

```tsx
interface IGridProps
  extends React.HTMLAttributes<HTMLDivElement>,
    Stitches.VariantProps<typeof grid> {}

const Grid: React.FC<IGridProps> = ({ className, gap, ...props }) => (
  <div className={grid({ className, gap })} {...props} />
);
```

This solution's OK for one or two components, but it can become tedious and might not be immediately obvious for those expecting Stitches to offer "dynamic variants" from other run-time styling libraries. 

**Describe the solution you'd like**

I'm not _super_ keen on this exact proposed API, but I think something _like_ this could enable users to roll their own themed variants (without having to worry about some of the runtime concerns that come with dynamic themed variants)

```ts
import type * as Stitches from "@stitches/core";
import { css, config, createThemedVariant } from "./stitches.config";

export const grid = css({
  display: "grid",
  gap: "$$gridGap",
  variants: {
    gap: createThemedVariant(
      // theme key
      "space", 
      // variant style (with themed value)
      (spaceKey) => ({
      $$gridGap: `$space$${spaceKey}`,
    })),
  },
  defaultVariants: {
    gap: 4,
  },
});
```

**Describe alternatives you've considered**
An alternative approach to #721 

**Additional context**
This issue was raised following an informal chat of ideas with @peduarte

**Comment by lukemorales** [comment]
The only thing I don't like about this solution is that it limits the usage to theme keys, while cases, where you want property values, are not covered, like in this example https://github.com/modulz/stitches/pull/721#issuecomment-921927344.
Obviously, your proposal is already a better stage than what we have today, but #721 seems like a more complete solution to dynamic variants
