### ISSUE TITLE
Utils seem to return `true` by default when using `createStitches`

### ISSUE THREAD

**Issue by EfstathiadisD** [modulz/stitches#814]
# Bug report

## Describe the bug

I am trying to use the `stitches` utils from on a custom config with version 1.1.0. And when I declare a config from the documentation, I get the following;

```ts
Type '(value: number) => {    margin: number;}' is not assignable to type 'string | number | boolean'.
  Type '(value: number) => {    margin: number;}' is not assignable to type 'true'.
```

It thinks that the `returnType` of `m` should be true, when it should be `{margin: number}` in reality.

## To Reproduce

1. Take the config, in a CodeSandbox, from the documentation regarding utils and check the error.

## Expected behavior

It should return the type by itself, especially when I type it and not default to `true.
## Screenshots

<img width="710" alt="Screenshot 2021-09-25 at 2 55 03 PM" src="https://user-images.githubusercontent.com/48406873/134770747-b5aae35a-0216-40ff-aabb-8c9ec191244b.png">

## System information

- OS: [macOS Big Sur]
- Browser (Chrome, Edge)
- Version of Stitches: [1.1.0]
- Version of Node.js: [14.15.0]

**Comment by EfstathiadisD** [comment]
On `version` 0.2.5, of Stitches everything works out of the freaking Box, so this is some kind of regression, or something that we need to do that should be added to the Docs.

**Comment by peduarte** [comment]
@EfstathiadisD It's not a regression. Version `0.2.5` wasn't properly typed. Have you seen this page in the docs? https://stitches.dev/docs/typescript#type-utils-as-css-properties-and-tokens

**Comment by EfstathiadisD** [comment]
@peduarte Thank you. Fixed it. Closing the issue!

**Comment by mkaralevich** [comment]
I have a similar issue here.

Code copied from the docs:

```ts
utils: {
  bc: (value: Stitches.PropertyValue<"backgroundColor">) => ({
    backgroundColor: value,
    }),
  }
```

<img width="896" alt="image" src="https://user-images.githubusercontent.com/16599920/144685656-ab63ed86-7ed6-47fd-afe3-5deaff8b6723.png">

"@stitches/react": "^1.2.5"
