### ISSUE TITLE
Support for shorthand CSS Properties

### ISSUE THREAD

**Issue by peduarte** [modulz/stitches#82]
In short, we need to be able to parse shorthand properties, eg:
```jsx
styled('a', {
  padding: '5px 10px 7px 10px',
  border: '5px solid red',
  boxShadow: 'inset 0 0 3px red'
})
```

Although this feature is **currently supported**, it relies on an array syntax:
```jsx
styled('a', {
  padding: ["5px", "10px", "15px", "20px"],
  border: ["5px", "solid", "red"]
})
```

> PS: It doesn't _always_ rely on an array, only if you're adding a multi value. Eg. The `margin` shorthand with a single value works fine: `margin: 10`

---

#### Pros
- Better Developer Experience due to typing
- Token-aware values
- No parsing logic (ultimately resulting in better performance)

#### Cons
- Learning curve (albeit small)
- People wanting to copy/paste code may have to refactor

![token-array-autocomplete](https://user-images.githubusercontent.com/372831/89769511-861f4a00-dafd-11ea-89e2-3656a7516e6e.gif)

**☝️  Example of an improved DX due to the array syntax**

#### Pros
- No learning curve
- No refactoring

#### Cons
- Degraded Developer Experience
- Increased library size in order to implement parsing algorithms 
- Potential performance cost when parsing values
  - in CSS the order doesn't matter (eg: `border: solid red 10px` and `border: 10px solid red` are both valid in CSS. Supporting this would result in complex parsing algorithms. This complexity increases when dealing with tokens. And it increases even further if users decide to use their own custom CSS Custom Property, (eg: `border: --var(s3) --var(--primary) solid`)
  - Different parser for different properties (the `font` shorthand property for example is rather complex)
  - More fragile and bug-prone library due to the parsing complexity 

---

We know from other libraries that developers are happy to adapt, given the return they get. 

When Styled Component introduced prop interpolation in CSS template strings, it wasn't like anything devs had seen before, but it got adoption because of the power of being able to change your value based on your props (only later to be discovered that it was possibly a mistake and led to insanely bad UI development decisions - not to mention performance)

When Styled System introduced its Array syntax for variants, it was heavily frowned upon, but it gave people a fast way to responsively change values. So the adoption rate went up.

When Chakra UI introduced a prop-driven pattern to style CSS pseudo (and limited), it was a learning curve for developers, but they adopted since they were getting a lot in return. Adoption rate continues to rise. 

---

What we need to decide is:
- If the value of our library is performance and DX, should we compromise pure CSS shorthand values in favour of the array syntax?
- Writing CSS shorthands promotes a less concise and maintainable codebase. Experienced UI Developers will generally prefer longhands over shorthands. Are we ok with having a library that can ultimate promote better code?
- If we provide a decent set of CSS Utils, like `marginY` and `marginX`, how does that impact peoples perception to shorthands?
- If we want to support raw CSS values, should we:
  - Add a parser so we can convert the value into atomic classes containing its longhand property?
  - Should we go with Otion's approach, to create an atomic class out of the shorthand property?

Please feel free to raise any more questions that I may have missed.

Let's try and open up and small and direct discussion on this. I will then create some actionable issues out of the conclusion. 

/cc @christianalfoni @colmtuite @StephenHaney @hadihallak @jjenzz

**Comment by colmtuite** [comment]
The main question for me is are they mutually exclusive? The DX benefits are cool, but I think it's just a non-starter to not support such fundamental CSS features. Can we not have both?

The lib should aim to be a CSS superset, not a subset. Removing basic CSS features is a bad idea imo.

**Comment by peduarte** [comment]
> Can we not have both?

Yes, we can have both. I think it's a matter of weighing the pros and cons in terms of performance and development in order to write bullet proof parsers 🙂 Then making a call whether that has to be done in the initial release. (or should we wait for people to ask... see how many do)

**Comment by jjenzz** [comment]
I'm personally okay with the stitches core only supporting array syntax for shorthands. 

We can always release a separate babel plugin that allows people to write string shorthands if that's something they really **must** have but I'm not convinced we should include that overhead in the core... at least for the initial release. 

My preference would be to see how our users find the improved DX the array can offer and use that package to track string popularity. If it's something people complain about a lot and the package has loads of downloads we could consider moving to core then, based on real data.

**Comment by hadihallak** [comment]
> The lib should aim to be a CSS superset, not a subset. Removing basic CSS features is a bad idea imo.
I agree with Colm on this one. 

> When Styled Component introduced prop interpolation in CSS template strings, it wasn't like anything devs had seen before, but it got adoption because of the power of being able to change your value based on your props 

I think this comes back to the point Colm mentioned about being a CSS superset. 
props interpolations were an added feature. it wasn't something that omitted any existing CSS features so if you choose to, you could write normal CSS without any props interpolations.

I think part of why SC is so successful is that it's so flexible and is suitable to people with all sorts of experience so someone coming from a pure CSS background would be able to write styled-components without much hassle.
it doesn't try to impose a certain right way of doing things on users which I think should be something we aim to do if we want the library to be widely adopted and not just used by the experienced top something-percent.

**Comment by peduarte** [comment]
I'm pretty confident that developers will adapt if what they get in return improves their workflow 🙂 

> it wasn't something that omitted any existing CSS features

Ah! But this doesn't omit a feature though. It just changes the value syntax 😄 The feature is still there! 

It is no different to how Styled Component changed the value syntax of the `animation` value.

<details>
<summary>Take a peek if you dare</summary>
 
You can't write normal CSS value, you need to interpolate the animation name since it's a JS variable. It's a syntax change. To add to this, animations don't work in object styles and they don't work in just a template string. You need to call the `css` function. 

```js
// Normal CSS syntax
const styles = `
  animation: rotate 2s linear infinite;
`

// ❌ This will throw an error! 
const styles = `
  animation: ${rotate} 2s linear infinite;
`

// ❌ This will throw an error! 
const styles = {
  animation: `${rotate} 2s linear infinite`
}

// ✅ This will work as intended
const styles = css`
  animation: ${rotate} 2s linear infinite;
`
```
</details>

**Comment by colmtuite** [comment]
The discussion so far is missing the point. This decision is not based on performance, DX, or syntax. It's purely about adoption.

There is a useful debate around performance, DX, and syntax, but that's between arrays, e.g. `padding: ["5px", "10px", "15px", "20px"]`, and utils, e.g. `pt: 1, pr: 2, pb: 3, pl: 4`. I think utils wins here, and I don't think it's close. There is no value in arrays when we have custom property aliases that ship with the lib. But that's for a separate debate.

Comparing arrays and shorthand support here is missing the point. Right now, we need to decide how to handle shorthand properties, which has nothing to do with arrays or DX.

> I think part of why SC is so successful is that it's so flexible and is suitable to people with all sorts of experience so someone coming from a pure CSS background would be able to write styled-components without much hassle. it doesn't try to impose a certain right way of doing things on users which I think should be something we aim to do if we want the library to be widely adopted and not just used by the experienced top something-percent.

This ☝️  We already know how some libs get widespread adoption and others don't. The way to get widespread adoption is to appeal to a wide variety of people, use cases, and skillsets.

Releasing the lib and waiting for feedback is not a viable strategy. People are not going to ask for shorthand support. They're just going to try the lib, become really confused, then bail.

We just have two decisions to make here:

1. Should we support shorthand properties at all?
2. If we are supporting shorthand properties, to what extent?

### Should we support shorthand properties at all?

It seems like this decision has already been made. The lib already supports shorthand properties to some extent. It supports single values for `margin` and `padding`. It supports `border` shorthand in a single, specific order. There's also an open issue to add support for `border: none`.

I think this is a good decision. If the lib doesn't support the most basic CSS patterns like `margin: 8px`, then most devs are just going to be really confused when trying it. They're not going to check the docs, or ask on a forum, or ping us on Twitter...they're just going to bail.

If anyone thinks we should drop support for shorthand properties, I'd love to hear an argument. But arrays have nothing to do with it. There are things we can do to replace shorthand, like arrays and utils, but the decision here is whether we should support regular shorthand or not.

### To what extent should we support shorthand support?

My take is, just a bit further than we currently are. I think we should support the following, at a minimum:

```
margin: '10px',
margin: '10px 20px',
margin: '10px 20px 30px',
margin: '10px 20px 30px 40px',

padding: '10px',
padding: '10px 20px',
padding: '10px 20px 30px',
padding: '10px 20px 30px 40px',

borderRadius: '10px',
borderRadius: '10px 20px',
borderRadius: '10px 20px 30px',
borderRadius: '10px 20px 30px 40px',

border: 'width style color',
border: 'none',

boxShadow: 'inset x y blur spread color',
boxShadow: 'x y blur spread color inset',
// boxShadow also needs to support chaining

transition: 'property duration easing delay',
// transition also needs to support chaining

animation: // whatever abdul has done already

background: // I'm not sure

font: // I'm not sure
```

Note: This is just my suggestion off the top of my head. I've almost certainly missed some important permutations, I'm just trying to communicate how I think we should go about handling the issue.

**Comment by christianalfoni** [comment]
Hi there 😄 

After some thinking I just wanted to chime in with a couple of comments on implementations related to what you have discussed this far.

Implementation wise shorthands needs to become arrays under the hood to evaluate each value, so the only addition to support string representation with chaining would be something like: `typeof value === 'string' ? value.split(',').map(part => part.split(' ')) : value`. So I would state the adoption argument wins, as supporting it should be a one liner. And since they need to become arrays anyways, might as well allow that syntax, as it will allow typed tokens on shorthands (`border: ['SIZE_1', 'solid', 'RED_500']`)

The really tricky part is the ordering. If we can not rely on order, we have to rely on some identifier for each value. Also these values could be tokens, so need to evaluate the value behind the token. Which is even trickier, for example:

```ts
border: 'SIZE_1 solid RED_500'
```

As I understand borders can have their values in any order, but there is nothing indicating in the tokens what category they are part of. So both `SIZE_1` and `RED_500` would have to check both `colors` and `sizes` category to find a match. Stuff like that...

If we were to force an order it would be way simpler... and arguably better code... at least more consistent code 😄 But that is also a question of adoption again.

But yeah, I would encourage to settle on *"We support string and array representation of shorthands"* and move the discussion to the question of supporting "any order" or a "set order", as that has most impact on the codebase I believe 🤔

**Comment by colmtuite** [comment]
Hey Christian, thanks for stopping by!

Makes sense to me. No harm in supporting arrays in addition to strings.

The token issues are a mess imo. I have an issue drafted to remove a bunch of tokens from the spec. I don't think it makes sense to abstract properties like `borderStyle`, which only accept a predefined set of values.

So, simply removing a bunch of tokens would help us here. But I'm hesitant to do so, because deviating from a relatively popular spec will cause issues, obviously.

**Comment by christianalfoni** [comment]
Happy to give my input 😄 

Yeah, we just grabbed the stuff from [system-ui](https://system-ui.com/theme/) and things like `borderStyle` is really weird. So think it is wise to take a hard look at what are actually valuable tokens 😂 

But yeah, I would suggest trying to come up with a parser, it is a super fun project 😄 So just some thoughts:

```ts
{
  someShorthand: (config) => (value) => {
    // Force the structure of chaining with values [ [...values...] ] 
    const chains = typeof value === 'string' ? value.split(',').map(part => part.split(' ')) : Array.isArray(value[0]) ? value : [value] 
    const css = chains.reduce((aggr, values) => {
      // Go through values and add/append css longhand
      // If token is found, go grab it from there
    }, {})
  }
}
```

So you could maybe get to a shorthand API that looks something like:

```ts
// Create mappers that takes the config, current css definition and the value. Kinda like a reducer
const borderStyleMapper = (config, css, value) => {
  if (['solid', 'dashed'].includes(value)) {
    return { ...css, borderStyleLeft: value, borderStyleTop: value, borderStyleBottom: value, borderStyleRight: value }
  }

  return css
}

const borderColorMapper = (config, css, value) => {
  if (config.tokens.colors[value] || value.matches(colorRegExp)) {
    const val =  config.tokens.colors[value] || value
    return { ...css, borderBottomColor:  val, borderLeftColor: val, borderTopColor: val, borderRightColor: val }
  }

  return css
}

const borderSizeMapper = () => ...

// Now shorthands can be created by basically mapping array values to one or multiple mappers. The mappers
// themselves handles the ordering, basically by not touching the css if their mapper is not relevant
const shorthands = {
  border: createShortHand([
    borderStyleMapper, borderSizeMapper, borderColorMapper
  ]),
  // could use "pattern matching" to match mappers with number of values passed in
  padding: createShortHand([
    paddingMapper
  ], [
    paddingHorizontalMapper,
    paddingVerticalMapper,
  ])
}
```

Okay... just some ideas 😄 The code would now basically be these mappers and then you have one `createShortHand` function which prepares the values and executes the mapping.

**Comment by peduarte** [comment]
Great discussion so far! Thanks @colmtuite for steering it in the right direction 💪 

@christianalfoni I agree with pretty much everything you said, thanks for that.

Personally I think allowing strings in a specific order is a good compromise. I think most people usually write it in the same order anyway, specially for border. 

I think good developer warnings would be very helpful if we can identify that a string wasn't written in an expected order. We would have very good docs, which would be linked from the warning too. Explaining the order that each supported shorthand.

**Comment by colmtuite** [comment]
Ok, it's decided then. We'll keep support for shorthand properties and expand it to support more properties and value permutations.

I've already opened an issue, let's track it there #81 .

**Comment by jjenzz** [comment]
> [...] as supporting it should be a one liner.

Apologies folks, I understood differently from the cons in the description but if that's the case then I agree we should 💯 support it! Thanks @christianalfoni

**Comment by hadihallak** [comment]
> [...] as supporting it should be a one liner.

just wanted to note that this isn't always the case since splitting by a comma and space isn't reliable when the value could contain things like quoted strings and css functions as they already contain spaces and commas so we'd need a separate value into array parser for the job.

**Comment by peduarte** [comment]
@hadihallak don't forget slashes ;)

**Comment by jjenzz** [comment]
Ah 😅 well I'm more of a "let's try things and adapt with evidence" kinda gal. 

I don't mind if we make it part of core, I just think the adapt part is harder then because if we decide later to remove it for any reason, taking things away from the minority is often met with uproar and that's when folk bail. Comparatively, marketing as an early stages lib and adding stuff in response to users feedback is usually praised.

I personally don't think people will bail if it's not part of the lib but we're all speculating here and decision has already been made, so I'm happy to go with the consensus ☺️
