### ISSUE TITLE
[Question] Can I use dollar sign($) for variants?

### ISSUE THREAD

**Issue by hg-pyun** [modulz/stitches#825]
## Description
When I use dollar sign in variant, It doesn't work. I think it related token spec, but I can't see spec document.
If it's not a spec, I think it's a bug. If it's a specification, I think it should be specified in the document.

## Code
![image](https://user-images.githubusercontent.com/10627668/135806396-a05ee995-4c6b-469a-94bd-6cb7fe9a04ff.png)

**Comment by peduarte** [comment]
Hi, this isnt allowed on purpose. Dollar signs are reserved for tokens.

But if you feel strongly about this, please feel free to open up a discussion

Thanks!

**Comment by jared-paperspace** [comment]
Y'all should document this breaking change in your migration docs. This completely rug pulled us moving from alpha.
