### ISSUE TITLE
Next.js 12 and React 18 `getCSSText` not rendering styles SSR

### ISSUE THREAD

**Issue by Kinbaum** [modulz/stitches#863]
# Bug report

## Describe the bug

After creating a Next.js 12 application with React 18 and a basic Stitches config, the `getCSSText` function does not collect styles from the page during SSR, which causes a FOUC.

## To Reproduce

<details>
<summary>package.json</summary>

```json
{
    "scripts": {
        "dev": "next dev",
        "build": "next build",
        "start": "next start"
    },
    "dependencies": {
        "@radix-ui/colors": "^0.1.7",
        "@stitches/react": "^1.2.5",
        "next": "^12.0.2-canary.2",
        "react": "^18.0.0-alpha-6c3dcc7a4-20211027",
        "react-dom": "^18.0.0-alpha-6c3dcc7a4-20211027"
    },
    "devDependencies": {
        "@types/react": "17.0.33",
        "@typescript-eslint/eslint-plugin": "^5.2.0",
        "@typescript-eslint/parser": "^5.2.0",
        "eslint": "<8.0.0",
        "eslint-config-next": "^12.0.1",
        "typescript": "4.4.4"
    }
}
```
</details>

<details>
<summary>next.config.js</summary>

```js
module.exports = {
    experimental: {
        reactRoot: true,
        concurrentFeatures: true,
        serverComponents: true
    }
};
```
</details>

<details>
<summary>tsconfig.json</summary>

```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@/stitches.config": [ "stitches.config" ]
        },
        "target": "es5",
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": false,
        "forceConsistentCasingInFileNames": true,
        "noEmit": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "node",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "jsx": "preserve",
        "incremental": true
    },
    "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
    "exclude": ["node_modules"]
}

```
</details>

<details>
<summary>stitches.config.ts</summary>

```ts
import { blue } from '@radix-ui/colors';
import { createStitches } from '@stitches/react';

const stitches = createStitches({
    theme: {
        colors: {
            ...blue
        }
    }
});

export const { config, getCssText, globalCss, keyframes, styled, theme } = stitches;
```
</details>

<details>
<summary>pages/_document.tsx</summary>

```tsx
import { getCssText } from '@/stitches.config';
import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
    return (
        <Html>
            <Head>
                <style id="stitches" dangerouslySetInnerHTML={ { __html: getCssText() } } />
            </Head>
            <body>
                <Main />
                <NextScript />
            </body>
        </Html>
    );
}
```
</details>

<details>
<summary>pages/_app.tsx</summary>

```tsx
import { AppProps } from 'next/app';

export default function MyApp({ Component, pageProps }: AppProps) {
    return <Component { ...pageProps } />;
}
```
</details>

<details>
<summary>pages/index.tsx</summary>

```tsx
import { styled } from '@/stitches.config';

const H1 = styled('h1', {
    backgroundColor: '$blue11'
});

export default function Page() {
    return (
        <H1>React Server Components in Next.js</H1>
    );
}
```
</details>

## Expected behavior

I would expect that the SSR rendered page would have collected the styles from the given page so there is no FOUC, however, there are no matching css declarations when viewing the source of the page.

## Screenshots

Here you can see that there is no matching rule for this className. I've simply set the background color for this element.

<img width="1499" alt="Screen Shot 2021-10-28 at 8 43 51 AM" src="https://user-images.githubusercontent.com/6590356/139257502-e95a5312-0e96-4722-9d9f-f026a9853542.png">

Here is the page source when downgrading Next to 11.1.2. You'll notice that the CSS is rendered properly on the server

<img width="1496" alt="Screen Shot 2021-10-28 at 9 22 02 AM" src="https://user-images.githubusercontent.com/6590356/139264232-14a12901-91d5-49a1-860a-29c1dbdfc54a.png">

## System information

- OS: Mac
- Next.js: v12.0.2-canary.2
- React: v18.0.0-alpha-6c3dcc7a4-20211027
- ReactDOM: v18.0.0-alpha-6c3dcc7a4-20211027
- Stitches: v1.2.5
- Version of Node.js: v16.5.0

**Comment by StephenHaney** [comment]
Streaming SSR w/ React 18 is a major change for dynamic CSS-in-JS libs and unsupported at the moment.

There's a thread here from the React team on what CSS-in-JS libs need to do to support React 18 SSR, good reading material:
https://github.com/reactwg/react-18/discussions/110

At the moment, we're reviewing this info and deciding on the best path towards support.

**Comment by Kinbaum** [comment]
This is a really great resource. Thank you for sharing. Looking forward to what you come up with.

**Comment by b2rsp** [comment]
Right now i am thinking of moving a large code of Sass to Stiches but i am cautios if you guys are going to support this streaming SSR w react 18, is that planned or expected to be working on future?

**Comment by peduarte** [comment]
@b2rsp hi, yeah, we're considering it but would require some strategic changes - static extraction

**Comment by b2rsp** [comment]
@peduarte Thanks for feedback, either way we started migrating our system from less into stiches and so far realy enjoying it. Just looking foward to see about to see the streaming server SSR since that will be really good for page load perceived performance.

**Comment by jimzer** [comment]
Any news on Stiches with React 18 :) ?
