### ISSUE TITLE
Make sure that classes are hashed in non-SSR apps (CRA)

### ISSUE THREAD

**Issue by hadihallak** [modulz/stitches#87]
Noticed this while working with `animationDuration` and `animationDirection`
they will map to atomic classes that start with `ad` so `ad_1`, `ad_2`, `a_x`

the funny thing is that some ad-blocking extensions will mistake these as ads and will apply `display:none` to them 😄 

Overall, I'm leaning towards disabling these short incremental classes that get generated when the library is running client-side and completely rely on hashed versions even if it's a tiny bit more costly as this would be more consistent and might even solve #72 since currently react complains during hydration that the dom isn't matching when SSR isn't enabled.

**Comment by peduarte** [comment]
haha brilliant. 

I do think there's a certain benefit of showing the abbreviated property though. Do you think we'd have the same issue if that was at the end of the hash?

**Comment by christianalfoni** [comment]
I just have to say I am so impressed by how thorough you are @hadihallak 😂

**Comment by hadihallak** [comment]
@peduarte 
I think it should be fine in this case. should we open an issue to disable them in production as I don't think this behavior is limited to development mode currently 

@christianalfoni that's only because I'm enjoying my time playing around with it 😄 
kudos to you for making it an enjoyable experience

**Comment by peduarte** [comment]
@hadihallak I think this only happens in development. Here's a [vercel preview build](https://stitches-site.modulz-deploys.com/), inspect the buttons, they're built with Stitches. The classnames don't seem to contain the abbreviated property name

**Comment by hadihallak** [comment]
@peduarte I think that's because you're using SSR which forces hashed classes. I believe in a CRA app things will be different

**Comment by hadihallak** [comment]
fixed in #120
