### ISSUE TITLE
Third party tools break on `insertRule`

### ISSUE THREAD

**Issue by safaaleigh** [modulz/stitches#873]
**Is your feature request related to a problem? Please describe.**

In configuring a third party tool called [hotjar](https://www.hotjar.com) with our site built with stitches, we were told by their support team that they aren't able to work with frameworks that use [`insertRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule) to inject stylesheets.

We've also tried a number of other tools that appear to also not be compatible with `insertRule`:
- [Inspectlet](https://www.inspectlet.com)
- [Lucky Orange](https://www.luckyorange.com)
- [SmartLook](https://www.smartlook.com/?utm_adgroup=Brand&utm_source=bing&utm_medium=cpc&utm_campaign=US_brand&utm_term=smartlook&utm_content=Brand)
- [MouseFlow](https://mouseflow.com)

**Describe the solution you'd like**

We'd like to be able to build stylesheets in a way that doesn't rely on `insertRule` in production.

**Describe alternatives you've considered**

- Using another `CSSStyleSheet` API to manipulate styles
- Generating css stylesheets at build time that can be applied in production without relying on `insertRule`

**Additional context**

The result of this issue is that our site works for users in typical browsers, but isn't supported when replaying session using hotjar and styles created with stitches just don't get applied.

**Comment by oeduardoal** [comment]
Hey @safaaleigh! Here at @grupoboticario, while our team had been building a design system we faced this problem. The solution was creating a package to capture the CSS CSSOM and inject in a tag style in head. Works like well.

We based our researchs for this problem with:
- https://github.com/styled-components/styled-components/issues/1603
- https://help.hotjar.com/hc/en-us/articles/115012499507-Platforms-and-Frameworks-not-Compatible-with-Hotjar
- https://engineering.brighthr.com/blog-posts/hotjar-styled-components-fix/

Basically this solution is: 

```
const Recording = {
  conditions: () => window?.hj?.settings?.record,
  selector: () => document.querySelectorAll("head style"),
  timeout: 1000,
  init: function ({ conditions, selector, timeout }) {
    this.conditions = conditions || this.conditions;
    this.selector = selector || this.selector;
    this.timeout = timeout || this.timeout;
  },
  run: () => {
    if (typeof window === "undefined") return;
    const syncStyles = document.createElement("style");
    syncStyles.type = "text/css";
    syncStyles.dataset.flora = true;
    document.head.insertBefore(syncStyles, document.head.children[0]);

    // start styles sync
    let lastStyles;
    const updateStyles = () => {
      const styleNodes = [].slice.call(Recording.selector());

      if (!styleNodes.length) return;

      const styles = styleNodes
        .filter((node) => !node.dataset.flora)
        .map(({ sheet }) =>
          [].slice
            .call(sheet.cssRules)
            .filter((rule) => rule.cssText.includes(".flora")) // prefix name in `createStitches` function
            .map((rule) => rule.cssText)
            .join(" ")
        )
        .join(" ");

      if (styles === lastStyles) return;

      syncStyles.textContent = styles;
      lastStyles = styles;
    };

    // start updating interval
    const startInterval = window.setInterval(() => {
      if (!Recording.conditions()) return;
      window.clearInterval(startInterval);
      window.setInterval(() => {
        window.requestAnimationFrame(() => {
          updateStyles();
        });
      }, 500);
    }, 50);
  },
};

Recording.run();

export default Recording;
```

I've been thinking to move this, to a package and publish.

**Comment by safaaleigh** [comment]
@oeduardoal Thank you so much for this! We were able to implement something along these lines and now our HotJar recordings working!

I'd love to collaborate on a package, let me know if you make a repo and I can help test it out.

**Comment by safaaleigh** [comment]
@oeduardoal In case you're interested, here's the code we ended up going with using Typescript and a few more functional patterns:

```ts
declare global {
  interface Window {
    hj: any;
  }
}

function handleRequestAnimationFrame() {
  const elements = document.querySelectorAll<HTMLStyleElement>('head style');

  if (!elements.length) return '';

  return Array.from(elements)
    .reduce<string[]>((previousValue, element) => {
      if (element.dataset.hotjarWorkaround) return previousValue;

      if (!element.sheet) return previousValue;

      const rulesString = Array.from(element.sheet.cssRules)
        .reduce<string[]>((previousRuleValue, rule) => {
          if (!rule.cssText.includes('.sibi')) return previousRuleValue;
          return previousRuleValue.concat(rule.cssText);
        }, [])
        .join(' ');

      return previousValue.concat(rulesString);
    }, [])
    .join(' ');
}

export function hotjarWorkaround() {
  if (typeof window === 'undefined') return;

  const syncStyles = document.createElement('style');
  syncStyles.dataset.hotjarWorkaround = 'true';
  syncStyles.type = 'text/css';

  // insert style element into head
  document.head.insertBefore(syncStyles, document.head.children[0]);

  // start styles update interval

  const intervalID = window.setInterval(() => {
    const isHotjarRecording = window?.hj?.settings?.record;
    if (!isHotjarRecording) return;

    window.clearInterval(intervalID);

    let lastStyles: string;

    window.setInterval(() => {
      window.requestAnimationFrame(() => {
        const styles = handleRequestAnimationFrame();
        if (styles === lastStyles) return;

        syncStyles.textContent = styles;
        lastStyles = styles;
      });
    }, 500);
  }, 50);
}
```

**Comment by jillesmc** [comment]
Hi @safaaleigh and @oeduardoal. 👋🏻 
Is this solution still valid nowadays?

**Comment by azuline** [comment]
We do something similar, except for LogRocket. It is still working for us.

**Comment by Linkmetal** [comment]
Hi! I'm having this problem, I'm using hotjar on a nextjs app with stitches and all the styled components are broken. I've tried a couple of the solutions above and nothing worked. 

Is this problem still happening or it should be fixed and the cause of the broken styles is a different one?

**Comment by arturLMoretti** [comment]
I could get the "record" property this way -> window?.hjSiteSettings?.record

**Comment by iamFIREcracker** [comment]
> Hey @safaaleigh! Here at @grupoboticario, while our team had been building a design system we faced this problem. The solution was creating a package to capture the CSS CSSOM and inject in a tag style in head. Works like well.
> 
> We based our researchs for this problem with:
> 
> * [Add bundles that switch off insertRule/speedy mode while maintaining a prod env styled-components/styled-components#1603](https://github.com/styled-components/styled-components/issues/1603)
> * https://help.hotjar.com/hc/en-us/articles/115012499507-Platforms-and-Frameworks-not-Compatible-with-Hotjar
> * https://engineering.brighthr.com/blog-posts/hotjar-styled-components-fix/
> 
> Basically this solution is:
> 
> ```js
> const Recording = {
>   conditions: () => window?.hj?.settings?.record,
>   selector: () => document.querySelectorAll("head style"),
>   timeout: 1000,
>   init: function ({ conditions, selector, timeout }) {
>     this.conditions = conditions || this.conditions;
>     this.selector = selector || this.selector;
>     this.timeout = timeout || this.timeout;
>   },
>   run: () => {
>     if (typeof window === "undefined") return;
>     const syncStyles = document.createElement("style");
>     syncStyles.type = "text/css";
>     syncStyles.dataset.flora = true; // identify our style node tag
>     document.head.insertBefore(syncStyles, document.head.children[0]);
> 
>     // start styles sync
>     let lastStyles;
>     const updateStyles = () => {
>       const styleNodes = [].slice.call(Recording.selector());
> 
>       if (!styleNodes.length) return;
> 
>       const styles = styleNodes
>         .filter((node) => !node.dataset.flora) // filter do not add previous style node tag
>         .map(({ sheet }) =>
>           [].slice
>             .call(sheet.cssRules)
>             .filter((rule) => rule.cssText.includes(".flora")) // prefix name in `createStitches` function
>             .map((rule) => rule.cssText)
>             .join(" ")
>         )
>         .join(" ");
> 
>       if (styles === lastStyles) return;
> 
>       syncStyles.textContent = styles;
>       lastStyles = styles;
>     };
> 
>     // start updating interval
>     const startInterval = window.setInterval(() => {
>       if (!Recording.conditions()) return;
>       window.clearInterval(startInterval);
>       window.setInterval(() => {
>         window.requestAnimationFrame(() => {
>           updateStyles();
>         });
>       }, 500);
>     }, 50);
>   },
> };
> 
> Recording.run();
> 
> export default Recording;
> ```
> 
> I've been thinking to move this, to a package and publish. 🚀

Watch out!  The above script might cause your site to crash the browser tab (Out of memory exception) when the Dark Reader extension (https://darkreader.org/) is toggled on:

- This script creates a new STYLE element
- DarkReader sees it, and creates new css override rules
- This scripts sees new css and adds it to the STYLE element
- DarkReader sees it, and creates new css override rules
- ...

The solution for us was to add `class="darkreader"` to the new STYLE element, effectively instructing DarkReadre to skip it (and break out of the infinite loop):

```diff
     if (typeof window === "undefined") return;
     const syncStyles = document.createElement("style");
     syncStyles.type = "text/css";
+    syncStyles.classList = ["darkreader"]; // tell Darkreader to ignore this tag
     syncStyles.dataset.flora = true; // identify our style node tag
     document.head.insertBefore(syncStyles, document.head.children[0]);   
```

Anyways, thanks again for the original snippet: you are a time saver!

**Comment by harrisonhenri** [comment]
Hey guys. Is anyone experiencing problems with this workaround when the user connection is slow?
