### ISSUE TITLE
TS Error: Type 'Values[Scale][Token]' does not satisfy the constraint 'string | number'

### ISSUE THREAD

**Issue by dlehmhus** [modulz/stitches#878]
# Bug report

## Describe the bug

Typescript constraint error when trying to compile with the typescript CLI via `tsc`.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone [example repo](https://github.com/dlehmhus/stitches-ts-error-example)
2. `npm install`
3. `npm run build`

## Expected behavior

No error.

## Screenshots

<img width="1085" alt="Screenshot 2021-11-23 at 09 25 18" src="https://user-images.githubusercontent.com/27899554/142992314-cb220516-72a3-4b1a-8b31-c9f80939374f.png">

## System information

- OS: macOS 12.0.1
- Version of Stitches: 1.2.5
- Version of Typescript: 4.5.2
- Version of Node.js: 14.17.0

## Additional context

This error does not occur with typescript 4.4.4.

**Comment by vinimedeiros13** [comment]
got this error having typescript version 4.4.4

**Comment by hadihallak** [comment]
Fixed in 1.2.7
