### ISSUE TITLE
WebkitBackgroundClip not supported?

### ISSUE THREAD

**Issue by MaximeHeckel** [modulz/stitches#889]
# Bug report

## Describe the bug

It looks like `WebkitBackgroundClip` is not supported by Stitches. The property is applied as `background-clip` in the compiled styles but doesn't have any effect.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Try to add the following to your code:

```jsx
const Text = styled('p', {});

// ...

<Text
  css={{
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    background: `linear-gradient(
        91.83deg,
        pink 2.26%,
        red 145.81%
      )`
  }}
  >
  Almost before we knew it, we had left the ground.
</Text>
```

Noticed that the following is being rendered:

<img width="970" alt="Screen Shot 2021-12-05 at 9 37 54 PM" src="https://user-images.githubusercontent.com/2974412/144778211-de571de8-e0d9-4950-9a88-cb3105b6a81a.png">

## Expected behavior

When moving the `WebkitBackgroundClip: 'text'` property as inline style (i.e. in the `style` prop) everything works as expected. That's a good workaround for now, but I'd love to add a "gradient" variant to my Stitches component 😄 

This is the expected result:
<img width="970" alt="Screen Shot 2021-12-05 at 9 37 00 PM" src="https://user-images.githubusercontent.com/2974412/144778136-4fcedbd2-24e6-4382-af34-b4b650198a8c.png">

## Screenshots

(See above)

## System information

- OS: macOS
- Browser (if applies) all
- Version of Stitches: 1.2.5
- Version of Node.js: v14.17.0

**Comment by peduarte** [comment]
Hey, it works but you're overriding it with the `background` property 😄 

Try this:
```jsx
{
  WebkitBackgroundClip: "text",
  WebkitTextFillColor: "transparent",
  backgroundImage: `linear-gradient(
        91.83deg,
        pink 2.26%,
        red 145.81%
      )`
}
```

**Comment by MaximeHeckel** [comment]
Works like a charm 🪄 

Thank you for the quick reply! That makes total sense 😄
