### ISSUE TITLE
Introduce the concept of breakpoints?

### ISSUE THREAD

**Issue by hadihallak** [modulz/stitches#90]
now that we've decided that screens is the wrong word and that they are not limited to viewport breakpoints in #84 

I think we need a different thing just for breakpoint because if you have a hover media query/screen, would it be right that it would map to a responsive variant like so? 
`<Button color={{"hoverMedia": red}} />`

https://codesandbox.io/s/flamboyant-solomon-hm643?file=/src/App.js

**Comment by peduarte** [comment]
I don't think this is necessary right now. It totally makes sense to want to switch a component variant based on a `@supports` media. You may have a variant for the button that controls the `pointer` property, and you may only wanna add to devices that support it (so no touch device)

**Comment by colmtuite** [comment]
Yeah I'm not sure I see the issue? Responsive variants don't _have_ to use all media queries at once, just the ones you specify, right? There are plenty of reasons why you'd want to apply a media query in the JSX.

I don't know the pseudo syntax for the `css` prop so I'll just make up some bullshit syntax for an example.

`<Button css={{ "hoverMedia" { '&:hover': { // my hover rule inside the hover media query } } }} />`
`<Button color="orange, prefersDark: black" />`

Media queries can be anything and there are use cases for applying all sorts of media queries in all sorts of scenarios.

**Comment by hadihallak** [comment]
Sounds good 👍
