### ISSUE TITLE
[Documentation] update misleading breakpoints example

### ISSUE THREAD

**Issue by seedy** [modulz/stitches#901]
Reviewing changelog and solved issues on stitches `1.2.6`, I'm not sure to understand [stitches example regarding breakpoints configuration](https://stitches.dev/docs/responsive-styles#configure-your-breakpoints): this example makes no sense for common usage of breakpoints.

It describes breakpoints that do overlap, which might in the end bring issues with variants inside components for unexperienced developers.

I don't have any use case for breakpoints which do overlap, but maybe I'm wrong.

In scenarii with device sizes, I think we **always** want to make sure breakpoints don't overlap, because by design, devices have size limits.

https://codesandbox.io/s/stitches-ci-cra-forked-fdrgb?file=/src/App.tsx

I think this example fooled people, as we can notice in https://github.com/modulz/stitches/issues/725
In this issue, I also noticed recommendations to use range syntax from media-queries level4 spec, but I fear it is still widely unsupported (https://developer.mozilla.org/en-US/docs/Web/CSS/@media#browser_compatibility). (Topic likely out of scope, sorry)

**Describe the solution you'd like**

I think simply giving an example with min/max media values for each breakpoint would make usage clearer for beginners or diagonal-readers (:sweat_smile: )

**Before**

![image](https://user-images.githubusercontent.com/3367393/146361231-eb2bb504-2f3d-40b3-9921-d3a2195e46ab.png)

**Proposal**
![image](https://user-images.githubusercontent.com/3367393/146361463-852c5b57-60bb-4f2f-a681-ef2bdb4cf2cb.png)

WDYT?

If anyone confirms that my proposal makes sense, I might try to push a PR myself. Else, please correct me.

**Comment by seedy** [comment]
NB: It seems range syntax for media queries is still unsupported on the majority of browsers. I guess the previous syntax would be enough already.

**Comment by knpwrs** [comment]
> this example makes no sense for common usage of breakpoints

> I don't have any use case for breakpoints which do overlap, but maybe I'm wrong.

I'm not sure I follow, "overlapping" breakpoints is how most mobile-first CSS frameworks are designed. See, for instance, https://github.com/twbs/bootstrap/blob/a3f27c67e8e3041858e18ac201a384332be14303/scss/_variables.scss#L279-L293 and https://github.com/tailwindlabs/tailwindcss/blob/ec911c73f08c81b7088246484379f2efce97a667/stubs/defaultConfig.stub.js#L6-L12.

**Comment by seedy** [comment]
@knpwrs Thanks for being the first one to answer :pray:

**Comment by knpwrs** [comment]
It takes some getting used to, but essentially you need to embrace the cascade in CSS. The idea is that you design for "mobile first" (with no media queries) and then as the browser grows to certain widths you apply overrides. Since the larger-width overrides are inside of media queries, the rules there have higher specificity, so they get applied overriding the non-media query styles. The larger min-width styles should also override the smaller min-width styles, and order shouldn't matter as far as I'm aware.

**Comment by seedy** [comment]
> It takes some getting used to, but essentially you need to embrace the cascade in CSS. The idea is that you design for "mobile first" (with no media queries) and then as the browser grows to certain widths you apply overrides. Since the larger-width overrides are inside of media queries, the rules there have higher specificity, so they get applied overriding the non-media query styles. The larger min-width styles should also override the smaller min-width styles, and order shouldn't matter as far as I'm aware.
> 
> Tools like sizzy are useful to have as well: https://sizzy.co/

Totally agree with you, that's what I had in mind. I just think using a library which still doesn't reliably behave with such rules makes the whole task clunky :sweat_smile:

**Comment by seedy** [comment]
Closing in favor of https://github.com/modulz/stitches/issues/917
