### ISSUE TITLE
Tailwind: Cannot set border-style on single edge

### ISSUE THREAD

**Issue by geirsagberg** [modulz/stitches#92]
Hi, thanks for a great library, I just started using @stitches/css with @stitches/tailwind and it works really well!

I have however ran into a strange snag: I can't find a way to set the border-style for a single edge:

![image](https://user-images.githubusercontent.com/594564/90136278-35655680-dd74-11ea-8661-dc4dec4bd192.png)

see https://codesandbox.io/s/hungry-flower-slxwo?file=/src/App.tsx

**Comment by peduarte** [comment]
Hi, the tailwind package is now deprecated. @christianalfoni might continue this in his own repo thought 👍
