### ISSUE TITLE
Setting cursor breaks the rest of styled CSS

### ISSUE THREAD

**Issue by DeathRight** [modulz/stitches#944]
# Bug report

## Describe the bug

When setting 'cursor: "pointer"' using styled, it breaks the rest of the styled CSS for some reason.

## To Reproduce

`const StyledButton = styled("button", {backgroundColor: '...', cursor: 'pointer'})`
--> backgroundColor is not applied. Remove cursor CSS, and it is. Very strange...

## Expected behavior

Not to break the rest of the styled CSS lol.

## System information

- OS: Windows
- Browser: Opera GX
- Version of Stitches: 1.2.6
- Version of Node.js: 16.13.1

## Additional context

Easy workaround is to just create another StyledComponent using the first (with the rest of the CSS) and only having the cursor set there.

`const StyledButton1 = styled("button", {backgroundColor: '...', ...});
const StyledButton = styled(StyledButton1, {cursor: 'pointer'})`
--> Works as expected
Really not sure what's going on here -- cursor is the only attribute I've found that breaks. The bug doesn't make sense, so hopefully it's somehow me-specific, but I swear I'm not lying haha.

**Comment by StephenHaney** [comment]
That seems quite odd indeed... I tried to repro here:
https://codesandbox.io/s/musing-mendeleev-byxgv?file=/src/App.js

But it appears to be working as intended for me. Can you reproduce in a sandbox?

**Comment by DeathRight** [comment]
> That seems quite odd indeed... I tried to repro here: https://codesandbox.io/s/musing-mendeleev-byxgv?file=/src/App.js
> 
> But it appears to be working as intended for me. Can you reproduce in a sandbox?

Alright, I'm not sure what happened, but after trying to reproduce it myself and the issue not presenting itself, I went back and tested my own code without the workaround, and it works now... Sorry for the trouble! I swear I tested it several times before creating the issue, maybe something weird was going on with my browser or setup at the time... who knows...

**Comment by StephenHaney** [comment]
No worries, glad to hear that it's working!
