### ISSUE TITLE
TS: expects `children: never` when using `styled(Component, {})`  

### ISSUE THREAD

**Issue by jjenzz** [modulz/stitches#96]
https://codesandbox.io/s/objective-sunset-3rpyp

The primitives have their own type so we cannot style any of our primitives using this API atm.

![image](https://user-images.githubusercontent.com/175330/90255919-db7c9380-de3c-11ea-8aff-5566194e8cc1.png)

![image](https://user-images.githubusercontent.com/175330/90255940-e33c3800-de3c-11ea-8cfb-c7b2f01efa5e.png)

**Comment by peduarte** [comment]
Without React.FC we get a different error https://codesandbox.io/s/recursing-http-ge42v?file=/src/App.tsx

**Comment by christianalfoni** [comment]
I believe this was fixed with: https://github.com/modulz/stitches/commit/842a55bb0447cd01c08dd6f267477924fd74f66d as well

**Comment by hadihallak** [comment]
@christianalfoni 👋  just an FYI that most type issues are already fixed as part of #134 which I will be merging in the next hours

**Comment by hadihallak** [comment]
Fixed in #134
