### ISSUE TITLE
transition property not working properly with styled function

### ISSUE THREAD

**Issue by lucasvsouza28** [modulz/stitches#964]
# Bug report

## Describe the bug

I've tried to create a simple progressbar component using the `styled` function.
The problem i'm facing is that the `transition` property are being setted, but the animation is not working.
I've changed the `styled` function to `css` function and the animation works properly with no changes in the component styles.

My question is: the `styled` function are equivalent to `css`? Should them behave the same?

## created with ```styled``` function
![styled_not_animated](https://user-images.githubusercontent.com/23587471/155001078-8c369854-4443-47c1-855a-3ccbe56bd65f.gif)

## created with ```css``` function
![css_animated](https://user-images.githubusercontent.com/23587471/155001139-e2c10fff-cc1e-43b7-8ae4-f1c8a6d68045.gif)

## Additional context
I've created this codesandbox with the 2 examples:
https://codesandbox.io/s/still-platform-t62on3?file=/src/App.js

**Comment by hadihallak** [comment]
Now that i see the codesandbox, the issue is that you're creating the styled components inside another component. if you move them to the module scope like in this codesandbox then everything should work correctly https://codesandbox.io/s/quizzical-wright-46flem?file=/src/App.js

**Comment by lucasvsouza28** [comment]
Oh thank you!

So, if i want to use the component props/state to compose property values, i should do it inline with ```css``` or ```style``` property?

**Comment by hadihallak** [comment]
Yes.
